package owonctl_test

import (
	"bytes"
	"errors"
	"io"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonctl"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// failingWriter reports one configured output failure.
//
// Example: PrintMessage must preserve a broken-pipe cause for callers.
type failingWriter struct {
	Cause error
}

// Write returns the configured failure without accepting bytes.
//
// Example: a closed stdout pipe is modeled by returning errors.New from Write.
func (writer failingWriter) Write(_ []byte) (int, error) {
	return 0, writer.Cause
}

// TestPrintMessagePropagatesOutputFailure verifies JSON output is not silently dropped.
//
// Example: a collector can classify a broken pipe with errors.Is.
func TestPrintMessagePropagatesOutputFailure(t *testing.T) {
	expected := errors.New("broken output")
	err := owonctl.PrintMessage(failingWriter{Cause: expected}, &pb.DeviceInfo{Model: "HDS2202S"})
	require.ErrorIs(t, err, expected)
}

// TestPrintMessageRejectsNilInputs verifies output contracts before protobuf marshaling.
//
// Example: nil message and writer values return errors instead of panicking.
func TestPrintMessageRejectsNilInputs(t *testing.T) {
	var configuration *owonctl.ErrConfiguration
	err := owonctl.PrintMessage(nil, &pb.DeviceInfo{})
	require.ErrorAs(t, err, &configuration)
	require.Equal(t, "output", configuration.Field)
	err = owonctl.PrintMessage(io.Discard, nil)
	require.ErrorAs(t, err, &configuration)
	require.Equal(t, "message", configuration.Field)
}

// TestPrintMessageRejectsTypedNilInputs verifies interface nils do not serialize silently.
//
// Example: a nil *bytes.Buffer or *DeviceInfo is rejected before marshaling or writing.
func TestPrintMessageRejectsTypedNilInputs(t *testing.T) {
	var output *bytes.Buffer
	var configuration *owonctl.ErrConfiguration
	err := owonctl.PrintMessage(output, &pb.DeviceInfo{})
	require.ErrorAs(t, err, &configuration)
	require.Equal(t, "output", configuration.Field)

	var message *pb.DeviceInfo
	err = owonctl.PrintMessage(io.Discard, message)
	require.ErrorAs(t, err, &configuration)
	require.Equal(t, "message", configuration.Field)
}
