package main

import (
	"bytes"
	"context"
	"errors"
	"net"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonlog"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonserver"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc"
)

// startupOutput signals the exact transition from binding to serving readiness.
//
// Example: cancellation tests wait for readiness without sleeping or polling.
type startupOutput struct {
	Ready     chan struct{}
	Logs      bytes.Buffer
	readyOnce sync.Once
}

// TestServeInstrumentReportsShutdownAfterCleanup composes native ownership with a real listener.
//
// Example: signal cancellation releases the instrument and socket before reporting shutdown.
func TestServeInstrumentReportsShutdownAfterCleanup(t *testing.T) {
	path := filepath.Join(unixListenerTestDir(t), "owond.sock")
	backend := new(startupBackend)
	service, session, err := composeService(t.Context(), backend, owonsession.Config{ExpectedSerial: "serial"}, owonserver.ServerConfig{})
	require.NoError(t, err)
	server := grpc.NewServer()
	pb.RegisterOwonServiceServer(server, service)
	logs := &startupOutput{Ready: make(chan struct{})}
	ctx, err := owonlog.WithContext(t.Context(), owonlog.Config{Level: logger.LevelInfo, Service: "owond"}, logs)
	require.NoError(t, err)
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	result := make(chan error, 1)
	observability.Go(ctx,
		// runInstrument joins daemon serving and hardware cleanup before returning.
		//
		// Example: the final result proves both ownership boundaries are released.
		func(ctx context.Context) {
			result <- serveInstrument(ctx, server, session, options{Endpoint: owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path}, Serial: "serial"})
		},
	)
	<-logs.Ready
	require.Zero(t, backend.Closes.Load())
	cancel()
	require.NoError(t, <-result)
	require.EqualValues(t, 1, backend.Closes.Load())
	require.Contains(t, logs.Logs.String(), "instrument closed")
	_, err = os.Lstat(path)
	require.ErrorIs(t, err, os.ErrNotExist)
	listener, err := openListener(t.Context(), owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path})
	require.NoError(t, err)
	require.NoError(t, listener.Close())
}

// Write acknowledges the daemon's startup message and releases the waiting test.
//
// Example: the listener is bound before the readiness channel closes.
func (output *startupOutput) Write(data []byte) (int, error) {
	n, err := output.Logs.Write(data)
	if strings.Contains(string(data), "gRPC listening") {
		output.readyOnce.Do(
			// announceReadiness publishes the first successful bind to the test.
			//
			// Example: later cleanup messages cannot signal readiness twice.
			func() { close(output.Ready) },
		)
	}
	return n, err
}

// TestGRPCServeLoopAcceptsStopBeforeServe verifies the other legal startup/shutdown ordering.
//
// Example: cancellation before the serving goroutine starts remains successful shutdown.
func TestGRPCServeLoopAcceptsStopBeforeServe(t *testing.T) {
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	server := grpc.NewServer()
	server.Stop()
	result := make(chan error, 1)
	grpcServeLoop{Server: server, Listener: listener, Result: result}.Run(t.Context())
	require.NoError(t, <-result)
	require.NoError(t, closeListener(listener))
}

// TestServeGRPCCancellationReleasesSocketAndLock checks ownership through the real serving path.
//
// Example: after cancellation another daemon can immediately bind the same endpoint.
func TestServeGRPCCancellationReleasesSocketAndLock(t *testing.T) {
	path := filepath.Join(unixListenerTestDir(t), "owond.sock")
	config := options{Endpoint: owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path}, Serial: "fixture"}
	ctx, cancel := context.WithCancel(t.Context())
	defer cancel()
	ready := make(chan struct{})
	logs := &startupOutput{Ready: ready}
	ctx, err := owonlog.WithContext(ctx, owonlog.Config{Level: logger.LevelInfo, Service: "owond"}, logs)
	require.NoError(t, err)
	result := make(chan error, 1)
	observability.Go(ctx,
		// runDaemon serves a real Unix socket until the test cancels its lifetime.
		//
		// Example: the result channel proves Serve has ended before filesystem checks.
		func(ctx context.Context) {
			result <- serveGRPC(ctx, grpc.NewServer(), config)
		},
	)
	<-ready
	cancel()
	require.NoError(t, <-result)
	require.Contains(t, logs.Logs.String(), "serial=fixture")
	require.Contains(t, logs.Logs.String(), "grpc_listen="+path)
	require.Contains(t, logs.Logs.String(), "service=owond")
	_, err = os.Lstat(path)
	require.ErrorIs(t, err, os.ErrNotExist)
	listener, err := openListener(t.Context(), config.Endpoint)
	require.NoError(t, err)
	require.NoError(t, listener.Close())
}

// TestServeInstrumentJoinsCleanupFailure prevents an unsuccessful close from claiming shutdown.
//
// Example: a foreign socket path and native close failure remain separately inspectable.
func TestServeInstrumentJoinsCleanupFailure(t *testing.T) {
	path := filepath.Join(unixListenerTestDir(t), "owond.sock")
	require.NoError(t, os.WriteFile(path, []byte("foreign"), 0o600))
	closeCause := errors.New("native close failed")
	backend := &startupBackend{CloseErrors: []error{closeCause}}
	_, session, err := composeService(t.Context(), backend, owonsession.Config{ExpectedSerial: "serial"}, owonserver.ServerConfig{})
	require.NoError(t, err)
	var output bytes.Buffer
	ctx, err := owonlog.WithContext(t.Context(), owonlog.Config{Level: logger.LevelInfo, Service: "owond"}, &output)
	require.NoError(t, err)
	err = serveInstrument(ctx, grpc.NewServer(), session, options{Endpoint: owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path}})
	require.ErrorContains(t, err, "non-socket")
	require.ErrorIs(t, err, closeCause)
	require.NotContains(t, output.String(), "instrument closed")
	require.NotContains(t, output.String(), "gRPC listening")
	require.EqualValues(t, 1, backend.Closes.Load())
	require.NoError(t, session.CloseContext(t.Context()))
}

// TestServeGRPCStartupFailuresReleaseOwnership checks bind failures return promptly.
//
// Example: a foreign file at the socket path remains intact after failed startup.
func TestServeGRPCStartupFailuresReleaseOwnership(t *testing.T) {
	path := filepath.Join(unixListenerTestDir(t), "owond.sock")
	config := options{Endpoint: owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path}, Serial: "fixture"}
	require.NoError(t, os.WriteFile(path, []byte("foreign"), 0o600))
	require.ErrorContains(t, serveGRPC(t.Context(), grpc.NewServer(), config), "non-socket")
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, "foreign", string(data))
}
