package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// AcquisitionPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: a requested peak-detect mode becomes AcquisitionModePeakDetect while an omitted memory depth stays nil.
func AcquisitionPatchFromProto(value *pb.SetAcquisitionRequest) *owonmodel.AcquisitionPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.AcquisitionPatch{
		Mode:         convertPointer[pb.AcquisitionMode, owonmodel.AcquisitionMode](value.Mode),
		AverageCount: clonePointer(value.AverageCount),
		MemoryDepth:  convertPointer[pb.AcquisitionMemoryDepth, owonmodel.AcquisitionMemoryDepth](value.MemoryDepth),
	}
	return result
}

// AcquisitionStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: an observed average count is copied independently while the memory-depth text is retained.
func AcquisitionStateToProto(value *owonmodel.AcquisitionState) *pb.AcquisitionState {
	if value == nil {
		return nil
	}
	result := &pb.AcquisitionState{
		Mode:         pb.AcquisitionMode(value.Mode),
		AverageCount: clonePointer(value.AverageCount),
		MemoryDepth:  value.MemoryDepth,
	}
	return result
}
