package owonrpc_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestPackageBoundaries keeps native device access independent from RPC and client code independent from USB.
//
// Example: a CLI-only installation can build without libusb or CGO.
func TestPackageBoundaries(t *testing.T) {
	for _, test := range []struct {
		Path      string
		Forbidden []string
	}{
		{"../owonmodel", []string{"google.golang.org/grpc", "google.golang.org/protobuf", "github.com/google/gousb", "/owonrpc", "/owonusb"}},
		{"../owonusb", []string{"google.golang.org/grpc", "google.golang.org/protobuf", "/owonrpc"}},
		{".", []string{"github.com/google/gousb", "/owonusb", "/owoncontrol", "/owonsession"}},
		{"./owonserver", []string{"github.com/google/gousb", "/owonusb", "/owoncontrol", "/owonsession"}},
		{"./owonclient", []string{"github.com/google/gousb", "/owonusb", "/owonserver", "/owoncontrol", "/owonsession"}},
		{"../../cmd/owonctl", []string{"github.com/google/gousb", "/owonusb", "/owonserver"}},
		{"../../cmd/owonweb", []string{"github.com/google/gousb", "/owonusb", "/owonserver"}},
	} {
		output, err := exec.Command("go", "list", "-deps", test.Path).CombinedOutput()
		require.NoError(t, err, "%s: %s", test.Path, output)
		for _, dependency := range test.Forbidden {
			require.NotContains(t, string(output), dependency, test.Path)
		}
	}
}

// TestGeneratedDirectoryContainsOnlyGeneratorOutput prevents authored policy from entering the generated package.
//
// Example: regeneration can replace every file in autogenerated without losing handwritten code.
func TestGeneratedDirectoryContainsOnlyGeneratorOutput(t *testing.T) {
	entries, err := os.ReadDir("autogenerated")
	require.NoError(t, err)
	require.Len(t, entries, 2)
	for _, entry := range entries {
		require.False(t, entry.IsDir())
		require.True(t, strings.HasSuffix(entry.Name(), ".pb.go"))
		data, err := os.ReadFile(filepath.Join("autogenerated", entry.Name()))
		require.NoError(t, err)
		require.Contains(t, string(data), "Code generated by protoc-gen-go")
	}
}
