package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// ChannelPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: an explicit false Display value stays present and can be changed without mutating the request.
func ChannelPatchFromProto(value *pb.SetChannelRequest) *owonmodel.ChannelPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.ChannelPatch{
		Channel:          owonmodel.Channel(value.Channel),
		Display:          clonePointer(value.Display),
		Coupling:         convertPointer[pb.Coupling, owonmodel.Coupling](value.Coupling),
		ProbeAttenuation: clonePointer(value.ProbeAttenuation),
		Scale:            clonePointer(value.Scale),
		OffsetDivisions:  clonePointer(value.OffsetDivisions),
		BandwidthLimit:   clonePointer(value.BandwidthLimit),
		Inversion:        clonePointer(value.Inversion),
	}
	return result
}

// ChannelStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a fractional ScreenHeaderOffset is copied without rounding it to an integer write offset.
func ChannelStateToProto(value *owonmodel.ChannelState) *pb.ChannelState {
	if value == nil {
		return nil
	}
	result := &pb.ChannelState{
		Channel:            pb.Channel(value.Channel),
		Display:            value.Display,
		Coupling:           pb.Coupling(value.Coupling),
		ProbeAttenuation:   value.ProbeAttenuation,
		Scale:              value.Scale,
		ScreenHeaderOffset: clonePointer(value.ScreenHeaderOffset),
	}
	return result
}
