package owonrpc

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestCommandConversionUsesNativeValidation ensures CLI preflight and server execution share framing policy.
//
// Example: unknown modes and compound SCPI commands fail without device I/O.
func TestCommandConversionUsesNativeValidation(t *testing.T) {
	_, err := CommandFromProto(nil)
	var invalidRequest *ErrInvalidInput
	require.ErrorAs(t, err, &invalidRequest)
	for _, mode := range []pb.ResponseMode{pb.ResponseMode_RESPONSE_MODE_NONE, pb.ResponseMode_RESPONSE_MODE_ASCII_LINE, pb.ResponseMode_RESPONSE_MODE_OWON_LENGTH_PREFIXED} {
		command, err := CommandFromProto(&pb.ExecuteRequest{Command: "*IDN?", ResponseMode: mode})
		require.NoError(t, err)
		require.Equal(t, "*IDN?", command.Text)
		require.EqualValues(t, mode, command.ResponseMode)
	}
	for _, request := range []*pb.ExecuteRequest{{Command: "*IDN?"}, {Command: "*IDN?", ResponseMode: 999}, {Command: "*IDN?;:RUN", ResponseMode: pb.ResponseMode_RESPONSE_MODE_ASCII_LINE}} {
		_, err := CommandFromProto(request)
		var invalidCommand *owonprotocol.ErrInvalidCommand
		require.ErrorAs(t, err, &invalidCommand)
	}
}
