package owonrpc

import (
	"fmt"

	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// CommandFromProto copies explicit framing and applies the native command validator.
//
// Example: CLI preparation rejects a compound command before dialing the daemon.
func CommandFromProto(request *pb.ExecuteRequest) (owonprotocol.Command, error) {
	if request == nil {
		return owonprotocol.Command{}, &ErrInvalidInput{Reason: "execute request is nil"}
	}
	command := owonprotocol.Command{Text: request.Command, ResponseMode: owonprotocol.ResponseMode(request.ResponseMode)}
	if err := owonprotocol.ValidateCommand(command); err != nil {
		return owonprotocol.Command{}, err
	}
	return command, nil
}

// ErrInvalidInput identifies invalid RPC input.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrInvalidInput struct {
	Reason string
	Cause  error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrInvalidInput) Error() string {
	if err == nil {
		return "invalid RPC input"
	}
	detail := err.Reason
	if detail == "" {
		detail = "invalid RPC input"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrInvalidInput) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}
