package owonrpc

import (
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// TestControlDomainsRejectMalformedJSON verifies closed write domains at the public parsing boundary.
//
// Example: fractional symmetry and unknown load names cannot become device commands.
func TestControlDomainsRejectMalformedJSON(t *testing.T) {
	t.Parallel()
	for _, testCase := range []struct {
		JSON    string
		Request proto.Message
	}{
		{`{"symmetryPercent":50.5}`, &pb.SetGeneratorRequest{}},
		{`{"symmetryPercent":"NaN"}`, &pb.SetGeneratorRequest{}},
		{`{"symmetryPercent":2147483648}`, &pb.SetGeneratorRequest{}},
		{`{"load":"unknown"}`, &pb.SetGeneratorRequest{}},
		{`{"range":"unknown"}`, &pb.SetDmmRequest{}},
		{`{"memoryDepth":"16K"}`, &pb.SetAcquisitionRequest{}},
	} {
		require.Error(t, protojson.Unmarshal([]byte(testCase.JSON), testCase.Request), testCase.JSON)
	}
}

// TestControlDomainDescriptors distinguishes writable selectors from observed values.
//
// Example: integer symmetry writes coexist with the documented floating-point query representation.
func TestControlDomainDescriptors(t *testing.T) {
	t.Parallel()
	for _, testCase := range []struct {
		Message  protoreflect.Name
		Field    protoreflect.Name
		Kind     protoreflect.Kind
		Presence bool
	}{
		{"SetGeneratorRequest", "symmetry_percent", protoreflect.Int32Kind, true},
		{"GeneratorState", "symmetry_percent", protoreflect.DoubleKind, false},
		{"SetGeneratorRequest", "load", protoreflect.EnumKind, true},
		{"GeneratorState", "load", protoreflect.EnumKind, false},
		{"SetDmmRequest", "range", protoreflect.EnumKind, true},
		{"DmmState", "range", protoreflect.EnumKind, false},
		{"SetAcquisitionRequest", "memory_depth", protoreflect.EnumKind, true},
		{"AcquisitionState", "memory_depth", protoreflect.StringKind, false},
	} {
		field := pb.File_pkg_owonrpc_owon_proto.Messages().ByName(testCase.Message).Fields().ByName(testCase.Field)
		require.Equal(t, testCase.Kind, field.Kind(), testCase.Message)
		require.Equal(t, testCase.Presence, field.HasPresence(), testCase.Message)
	}
}
