package owonrpc

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// conversionPointer allocates one independent present field for conversion expectations.
//
// Example: a pointer to 3.5 distinguishes amplitude from a neighboring offset of 4.5.
func conversionPointer[T any](value T) *T { return &value }

// TestEveryRequestFieldHasItsOwnMapping detects omitted fields and accidental swaps independently of presence checks.
//
// Example: each generator quantity has a distinct value so frequency cannot silently become period.
func TestEveryRequestFieldHasItsOwnMapping(t *testing.T) {
	require.Equal(t, &owonmodel.ChannelPatch{
		Channel:          owonmodel.Channel2,
		Display:          conversionPointer(true),
		Coupling:         conversionPointer(owonmodel.CouplingGround),
		ProbeAttenuation: conversionPointer(10.0),
		Scale:            conversionPointer("2.00V"),
		OffsetDivisions:  conversionPointer(int64(-123)),
		BandwidthLimit:   conversionPointer(false),
		Inversion:        conversionPointer(true),
	}, ChannelPatchFromProto(&pb.SetChannelRequest{
		Channel:          pb.Channel_CHANNEL_2,
		Display:          conversionPointer(true),
		Coupling:         conversionPointer(pb.Coupling_COUPLING_GROUND),
		ProbeAttenuation: conversionPointer(10.0),
		Scale:            conversionPointer("2.00V"),
		OffsetDivisions:  conversionPointer(int64(-123)),
		BandwidthLimit:   conversionPointer(false),
		Inversion:        conversionPointer(true),
	}))

	require.Equal(t, &owonmodel.AcquisitionPatch{
		Mode:         conversionPointer(owonmodel.AcquisitionModePeakDetect),
		AverageCount: conversionPointer(uint32(128)),
		MemoryDepth:  conversionPointer(owonmodel.AcquisitionMemoryDepth8K),
	}, AcquisitionPatchFromProto(&pb.SetAcquisitionRequest{
		Mode:         conversionPointer(pb.AcquisitionMode_ACQUISITION_MODE_PEAK_DETECT),
		AverageCount: conversionPointer(uint32(128)),
		MemoryDepth:  conversionPointer(pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_8K),
	}))

	require.Equal(t, &owonmodel.HorizontalPatch{
		Scale:           conversionPointer("20us"),
		OffsetDivisions: conversionPointer(int64(-9007199254740993)),
	}, HorizontalPatchFromProto(&pb.SetHorizontalRequest{
		Scale:           conversionPointer("20us"),
		OffsetDivisions: conversionPointer(int64(-9007199254740993)),
	}))

	require.Equal(t, &owonmodel.TriggerPatch{
		Source:     conversionPointer(owonmodel.TriggerSourceChannel2),
		Coupling:   conversionPointer(owonmodel.CouplingDC),
		Slope:      conversionPointer(owonmodel.TriggerSlopeFalling),
		LevelVolts: conversionPointer(1.25),
		Sweep:      conversionPointer(owonmodel.TriggerSweepNormal),
	}, TriggerPatchFromProto(&pb.SetTriggerRequest{
		Source:     conversionPointer(pb.TriggerSource_TRIGGER_SOURCE_CHANNEL_2),
		Coupling:   conversionPointer(pb.Coupling_COUPLING_DC),
		Slope:      conversionPointer(pb.TriggerSlope_TRIGGER_SLOPE_FALLING),
		LevelVolts: conversionPointer(1.25),
		Sweep:      conversionPointer(pb.TriggerSweep_TRIGGER_SWEEP_NORMAL),
	}))

	selectors := []*pb.MeasurementSelector{
		{
			Channel: pb.Channel_CHANNEL_2,
			Kind:    pb.MeasurementKind_MEASUREMENT_KIND_PERIOD,
		},
		nil,
	}
	nativeSelectors := []*owonmodel.MeasurementSelector{
		{
			Channel: owonmodel.Channel2,
			Kind:    owonmodel.MeasurementKindPeriod,
		},
		nil,
	}

	require.Equal(t, &owonmodel.MeasurementPatch{
		Display:        conversionPointer(false),
		ReplaceVisible: conversionPointer(true),
		Visible:        nativeSelectors,
	}, MeasurementPatchFromProto(&pb.SetMeasurementRequest{
		Display:        conversionPointer(false),
		ReplaceVisible: conversionPointer(true),
		Visible:        selectors,
	}))

	require.Equal(t, &owonmodel.StateRequest{
		Measurements:        nativeSelectors,
		IncludeScreenHeader: true,
		IncludeControls:     false,
	}, StateRequestFromProto(&pb.GetStateRequest{
		Measurements:        selectors,
		IncludeScreenHeader: true,
		IncludeControls:     false,
	}))

	require.Equal(t, &owonmodel.GeneratorPatch{
		Waveform:          conversionPointer(owonmodel.GeneratorWaveformRamp),
		FrequencyHz:       conversionPointer(1.5),
		PeriodSeconds:     conversionPointer(2.5),
		AmplitudeVolts:    conversionPointer(3.5),
		OffsetVolts:       conversionPointer(4.5),
		HighVolts:         conversionPointer(5.5),
		LowVolts:          conversionPointer(6.5),
		SymmetryPercent:   conversionPointer(int32(7)),
		PulseWidthSeconds: conversionPointer(8.5),
		RisingSeconds:     conversionPointer(9.5),
		FallingSeconds:    conversionPointer(10.5),
		DutyPercent:       conversionPointer(11.5),
		Load:              conversionPointer(owonmodel.GeneratorLoadOn),
		Output:            conversionPointer(true),
	}, GeneratorPatchFromProto(&pb.SetGeneratorRequest{
		Waveform:          conversionPointer(pb.GeneratorWaveform_GENERATOR_WAVEFORM_RAMP),
		FrequencyHz:       conversionPointer(1.5),
		PeriodSeconds:     conversionPointer(2.5),
		AmplitudeVolts:    conversionPointer(3.5),
		OffsetVolts:       conversionPointer(4.5),
		HighVolts:         conversionPointer(5.5),
		LowVolts:          conversionPointer(6.5),
		SymmetryPercent:   conversionPointer(int32(7)),
		PulseWidthSeconds: conversionPointer(8.5),
		RisingSeconds:     conversionPointer(9.5),
		FallingSeconds:    conversionPointer(10.5),
		DutyPercent:       conversionPointer(11.5),
		Load:              conversionPointer(pb.GeneratorLoad_GENERATOR_LOAD_ON),
		Output:            conversionPointer(true),
	}))

	require.Equal(t, &owonmodel.DMMPatch{
		Function:    conversionPointer(owonmodel.DMMFunctionCurrent),
		CurrentType: conversionPointer(owonmodel.DMMCurrentTypeAC),
		Relative:    conversionPointer(true),
		Range:       conversionPointer(owonmodel.DMMRangeMV),
		AutoRange:   conversionPointer(false),
	}, DMMPatchFromProto(&pb.SetDmmRequest{
		Function:    conversionPointer(pb.DmmFunction_DMM_FUNCTION_CURRENT),
		CurrentType: conversionPointer(pb.DmmCurrentType_DMM_CURRENT_TYPE_AC),
		Relative:    conversionPointer(true),
		Range:       conversionPointer(pb.DmmRange_DMM_RANGE_MV),
		AutoRange:   conversionPointer(false),
	}))
}

// TestEveryResultFieldHasItsOwnMapping checks every public native result field against a complete wire expectation.
//
// Example: distinct physical quantities and raw byte sequences cannot be exchanged during conversion.
func TestEveryResultFieldHasItsOwnMapping(t *testing.T) {
	instant := time.Unix(1234567, 987654321).UTC()
	native := &owonmodel.StateSnapshot{
		Device: &owonmodel.DeviceInfo{
			Manufacturer: "OWON",
			Model:        "HDS2202S",
			Serial:       "serial",
			Firmware:     "firmware",
			VendorID:     123,
			ProductID:    456,
			Capabilities: []owonmodel.Capability{owonmodel.CapabilityMultimeter, owonmodel.CapabilityScreenWaveform},
		},
		Measurements: []*owonmodel.Measurement{
			{
				Channel: owonmodel.Channel2,
				Kind:    owonmodel.MeasurementKindMinimum,
				Value:   -1.25,
				Unit:    "V",
				Raw:     "-1.250V",
			},
			nil,
		},
		Channels: []*owonmodel.ChannelState{
			{
				Channel:            owonmodel.Channel1,
				Display:            true,
				Coupling:           owonmodel.CouplingAC,
				ProbeAttenuation:   100,
				Scale:              "10V",
				ScreenHeaderOffset: conversionPointer(-7.25),
			},
			nil,
		},
		Acquisition: &owonmodel.AcquisitionState{
			Mode:         owonmodel.AcquisitionModeSample,
			AverageCount: conversionPointer(uint32(64)),
			MemoryDepth:  "observed-depth",
		},
		Horizontal: &owonmodel.HorizontalState{
			Scale:              "50us",
			ScreenHeaderOffset: conversionPointer(13.5),
		},
		Trigger: &owonmodel.TriggerState{
			Source:   owonmodel.TriggerSourceChannel2,
			Coupling: owonmodel.CouplingDC,
			Slope:    owonmodel.TriggerSlopeFalling,
			Level:    -3.75,
			Sweep:    owonmodel.TriggerSweepSingle,
			Status:   "STOP",
		},
		Generator: &owonmodel.GeneratorState{
			Waveform:          owonmodel.GeneratorWaveformSquare,
			FrequencyHz:       1.5,
			PeriodSeconds:     2.5,
			AmplitudeVolts:    3.5,
			OffsetVolts:       4.5,
			HighVolts:         5.5,
			LowVolts:          6.5,
			SymmetryPercent:   7.5,
			PulseWidthSeconds: 8.5,
			RisingSeconds:     9.5,
			FallingSeconds:    10.5,
			DutyPercent:       11.5,
			Load:              owonmodel.GeneratorLoadOff,
			Output:            true,
		},
		DMM: &owonmodel.DMMState{
			Function:    owonmodel.DMMFunctionCurrent,
			CurrentType: owonmodel.DMMCurrentTypeAC,
			Relative:    true,
			Range:       owonmodel.DMMRangeV,
			AutoRange:   false,
		},
		ScreenHeaderJSON: []byte{0, 127, 255},
		CapturedAt:       instant,
	}

	want := &pb.StateSnapshot{
		Device: &pb.DeviceInfo{
			Manufacturer: "OWON",
			Model:        "HDS2202S",
			Serial:       "serial",
			Firmware:     "firmware",
			VendorId:     123,
			ProductId:    456,
			Capabilities: []pb.Capability{pb.Capability_CAPABILITY_MULTIMETER, pb.Capability_CAPABILITY_SCREEN_WAVEFORM},
		},
		Measurements: []*pb.Measurement{
			{
				Channel: pb.Channel_CHANNEL_2,
				Kind:    pb.MeasurementKind_MEASUREMENT_KIND_MINIMUM,
				Value:   -1.25,
				Unit:    "V",
				Raw:     "-1.250V",
			},
			nil,
		},
		Channels: []*pb.ChannelState{
			{
				Channel:            pb.Channel_CHANNEL_1,
				Display:            true,
				Coupling:           pb.Coupling_COUPLING_AC,
				ProbeAttenuation:   100,
				Scale:              "10V",
				ScreenHeaderOffset: conversionPointer(-7.25),
			},
			nil,
		},
		Acquisition: &pb.AcquisitionState{
			Mode:         pb.AcquisitionMode_ACQUISITION_MODE_SAMPLE,
			AverageCount: conversionPointer(uint32(64)),
			MemoryDepth:  "observed-depth",
		},
		Horizontal: &pb.HorizontalState{
			Scale:              "50us",
			ScreenHeaderOffset: conversionPointer(13.5),
		},
		Trigger: &pb.TriggerState{
			Source:   pb.TriggerSource_TRIGGER_SOURCE_CHANNEL_2,
			Coupling: pb.Coupling_COUPLING_DC,
			Slope:    pb.TriggerSlope_TRIGGER_SLOPE_FALLING,
			Level:    -3.75,
			Sweep:    pb.TriggerSweep_TRIGGER_SWEEP_SINGLE,
			Status:   "STOP",
		},
		Generator: &pb.GeneratorState{
			Waveform:          pb.GeneratorWaveform_GENERATOR_WAVEFORM_SQUARE,
			FrequencyHz:       1.5,
			PeriodSeconds:     2.5,
			AmplitudeVolts:    3.5,
			OffsetVolts:       4.5,
			HighVolts:         5.5,
			LowVolts:          6.5,
			SymmetryPercent:   7.5,
			PulseWidthSeconds: 8.5,
			RisingSeconds:     9.5,
			FallingSeconds:    10.5,
			DutyPercent:       11.5,
			Load:              pb.GeneratorLoad_GENERATOR_LOAD_OFF,
			Output:            true,
		},
		Dmm: &pb.DmmState{
			Function:    pb.DmmFunction_DMM_FUNCTION_CURRENT,
			CurrentType: pb.DmmCurrentType_DMM_CURRENT_TYPE_AC,
			Relative:    true,
			Range:       pb.DmmRange_DMM_RANGE_V,
			AutoRange:   false,
		},
		ScreenHeaderJson: []byte{0, 127, 255},
		CapturedAt:       timestamppb.New(instant),
	}

	require.Equal(t, want, StateSnapshotToProto(native))

	require.Equal(t, &pb.DmmMeasurement{
		Function:   conversionPointer(pb.DmmFunction_DMM_FUNCTION_RESISTANCE),
		Value:      123.5,
		Unit:       "ohm",
		Raw:        "123.50 ohm",
		CapturedAt: timestamppb.New(instant),
	}, DMMMeasurementToProto(&owonmodel.DMMMeasurement{
		Function:   conversionPointer(owonmodel.DMMFunctionResistance),
		Value:      123.5,
		Unit:       "ohm",
		Raw:        "123.50 ohm",
		CapturedAt: instant,
	}))

	require.Equal(t, &pb.Waveform{
		Channel:          pb.Channel_CHANNEL_2,
		Data:             []byte{1, 255, 0, 128},
		Encoding:         "raw",
		ScreenHeaderJson: []byte{2, 3},
		CapturedAt:       timestamppb.New(instant),

		Metadata: &pb.WaveformMetadata{
			SampleCount:       conversionPointer(uint64(99)),
			SampleRateHz:      1000,
			SampleEncoding:    "unknown",
			XOriginSeconds:    conversionPointer(1.25),
			XIncrementSeconds: conversionPointer(2.5),
			YOriginVolts:      conversionPointer(-3.75),
			YIncrementVolts:   conversionPointer(4.125),
			DataLengthBytes:   4,
		},
	}, WaveformToProto(&owonmodel.Waveform{
		Channel:          owonmodel.Channel2,
		Data:             []byte{1, 255, 0, 128},
		Encoding:         "raw",
		ScreenHeaderJSON: []byte{2, 3},
		CapturedAt:       instant,

		Metadata: &owonmodel.WaveformMetadata{
			SampleCount:       conversionPointer(uint64(99)),
			SampleRateHz:      1000,
			SampleEncoding:    "unknown",
			XOriginSeconds:    conversionPointer(1.25),
			XIncrementSeconds: conversionPointer(2.5),
			YOriginVolts:      conversionPointer(-3.75),
			YIncrementVolts:   conversionPointer(4.125),
			DataLengthBytes:   4,
		},
	}))
}
