package owonrpc

import (
	"math"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owoncontrol"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestRequestConversionsPreservePresenceAndOwnership verifies optional fields and exact integer writes survive the boundary.
//
// Example: a present false and an offset above float64 precision remain independent native values.
func TestRequestConversionsPreservePresenceAndOwnership(t *testing.T) {
	zero, no, scale, offset := 0.0, false, "", int64(9007199254740993)
	coupling := pb.Coupling_COUPLING_DC
	channel := &pb.SetChannelRequest{
		Channel:          pb.Channel_CHANNEL_2,
		Display:          &no,
		Coupling:         &coupling,
		ProbeAttenuation: &zero,
		Scale:            &scale,
		OffsetDivisions:  &offset,
		BandwidthLimit:   &no,
		Inversion:        &no,
	}
	got := ChannelPatchFromProto(channel)
	require.Equal(t, owonmodel.Channel2, got.Channel)
	require.Equal(t, owonmodel.CouplingDC, *got.Coupling)
	require.Equal(t, offset, *got.OffsetDivisions)
	require.False(t, *got.Display)

	*got.Display, *got.OffsetDivisions, *got.Coupling, *got.Scale, *got.ProbeAttenuation = true, 0, owonmodel.CouplingAC, "1V", 10
	*got.BandwidthLimit, *got.Inversion = true, true
	require.False(t, no)
	require.Equal(t, int64(9007199254740993), offset)
	require.Equal(t, pb.Coupling_COUPLING_DC, coupling)
	require.Empty(t, scale)
	require.Zero(t, zero)

	horizontal := HorizontalPatchFromProto(&pb.SetHorizontalRequest{
		Scale:           &scale,
		OffsetDivisions: &offset,
	})
	require.Equal(t, offset, *horizontal.OffsetDivisions)

	*horizontal.OffsetDivisions = 0
	require.Equal(t, int64(9007199254740993), offset)

	selector := &pb.MeasurementSelector{
		Channel: pb.Channel_CHANNEL_1,
		Kind:    pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY,
	}
	state := StateRequestFromProto(&pb.GetStateRequest{
		Measurements:        []*pb.MeasurementSelector{nil, selector},
		IncludeControls:     true,
		IncludeScreenHeader: true,
	})
	require.Nil(t, state.Measurements[0])
	require.Equal(t, owonmodel.MeasurementKindFrequency, state.Measurements[1].Kind)
	require.True(t, state.IncludeControls)
	require.True(t, state.IncludeScreenHeader)

	state.Measurements[1].Channel = owonmodel.Channel2
	require.Equal(t, pb.Channel_CHANNEL_1, selector.Channel)
	require.Nil(t, StateRequestFromProto(&pb.GetStateRequest{}).Measurements)
	require.NotNil(t, StateRequestFromProto(&pb.GetStateRequest{Measurements: []*pb.MeasurementSelector{}}).Measurements)

	measurement := MeasurementPatchFromProto(&pb.SetMeasurementRequest{
		Display:        &no,
		ReplaceVisible: &no,
		Visible:        []*pb.MeasurementSelector{selector, nil},
	})
	require.False(t, *measurement.Display)
	require.False(t, *measurement.ReplaceVisible)
	require.Nil(t, measurement.Visible[1])

	measurement.Visible[0].Kind = owonmodel.MeasurementKindUnknown
	require.Equal(t, pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY, selector.Kind)

	request := WaveformRequestFromProto(&pb.GetWaveformRequest{
		Channel: pb.Channel_CHANNEL_2,
		Screen:  true,
	})
	require.Equal(t, &owonmodel.WaveformRequest{
		Channel: owonmodel.Channel2,
		Screen:  true,
	}, request)
}

// TestControlConversionsRetainUnsupportedAndUnknownValues preserves native validation as the single policy owner.
//
// Example: known AVERAGE reaches transport admission while an unknown mode reaches ErrInvalidRequest.
func TestControlConversionsRetainUnsupportedAndUnknownValues(t *testing.T) {
	for _, mode := range []pb.AcquisitionMode{
		pb.AcquisitionMode_ACQUISITION_MODE_AVERAGE,
		pb.AcquisitionMode(math.MaxInt32),
		pb.AcquisitionMode(math.MinInt32),
	} {
		patch := AcquisitionPatchFromProto(&pb.SetAcquisitionRequest{Mode: &mode})
		require.EqualValues(t, mode, *patch.Mode)
		err := new(owoncontrol.Controller).SetAcquisition(t.Context(), patch)
		if mode == pb.AcquisitionMode_ACQUISITION_MODE_AVERAGE {
			var unavailable *owoncontrol.ErrUnavailable
			require.ErrorAs(t, err, &unavailable)
		} else {
			var invalid *owonmodel.ErrInvalidRequest
			require.ErrorAs(t, err, &invalid)
		}
	}

	count, depth := uint32(0), pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_8K
	acquisition := AcquisitionPatchFromProto(&pb.SetAcquisitionRequest{
		AverageCount: &count,
		MemoryDepth:  &depth,
	})
	require.Zero(t, *acquisition.AverageCount)
	require.Equal(t, owonmodel.AcquisitionMemoryDepth8K, *acquisition.MemoryDepth)

	*acquisition.AverageCount = 8
	require.Zero(t, count)

	zero, no := 0.0, false
	source, coupling, slope, sweep := pb.TriggerSource_TRIGGER_SOURCE_CHANNEL_2, pb.Coupling_COUPLING_DC, pb.TriggerSlope_TRIGGER_SLOPE_FALLING, pb.TriggerSweep_TRIGGER_SWEEP_SINGLE
	trigger := TriggerPatchFromProto(&pb.SetTriggerRequest{
		Source:     &source,
		Coupling:   &coupling,
		Slope:      &slope,
		LevelVolts: &zero,
		Sweep:      &sweep,
	})
	require.Equal(t, owonmodel.TriggerSourceChannel2, *trigger.Source)
	require.Equal(t, owonmodel.CouplingDC, *trigger.Coupling)
	require.Equal(t, owonmodel.TriggerSlopeFalling, *trigger.Slope)
	require.Zero(t, *trigger.LevelVolts)
	require.Equal(t, owonmodel.TriggerSweepSingle, *trigger.Sweep)

	function, current, voltageRange := pb.DmmFunction_DMM_FUNCTION_VOLTAGE, pb.DmmCurrentType_DMM_CURRENT_TYPE_DC, pb.DmmRange_DMM_RANGE_MV
	dmm := DMMPatchFromProto(&pb.SetDmmRequest{
		Function:    &function,
		CurrentType: &current,
		Range:       &voltageRange,
		Relative:    &no,
		AutoRange:   &no,
	})
	require.Equal(t, owonmodel.DMMFunctionVoltage, *dmm.Function)
	require.Equal(t, owonmodel.DMMCurrentTypeDC, *dmm.CurrentType)
	require.Equal(t, owonmodel.DMMRangeMV, *dmm.Range)
	require.False(t, *dmm.Relative)
	require.False(t, *dmm.AutoRange)

	wave, load, symmetry := pb.GeneratorWaveform_GENERATOR_WAVEFORM_PULSE, pb.GeneratorLoad_GENERATOR_LOAD_OFF, int32(0)
	generator := GeneratorPatchFromProto(&pb.SetGeneratorRequest{
		Waveform:          &wave,
		FrequencyHz:       &zero,
		PeriodSeconds:     &zero,
		AmplitudeVolts:    &zero,
		OffsetVolts:       &zero,
		HighVolts:         &zero,
		LowVolts:          &zero,
		SymmetryPercent:   &symmetry,
		PulseWidthSeconds: &zero,
		RisingSeconds:     &zero,
		FallingSeconds:    &zero,
		DutyPercent:       &zero,
		Load:              &load,
		Output:            &no,
	})
	require.Equal(t, owonmodel.GeneratorWaveformPulse, *generator.Waveform)
	require.Equal(t, owonmodel.GeneratorLoadOff, *generator.Load)
	for _, number := range []*float64{
		generator.FrequencyHz,
		generator.PeriodSeconds,
		generator.AmplitudeVolts,
		generator.OffsetVolts,
		generator.HighVolts,
		generator.LowVolts,
		generator.PulseWidthSeconds,
		generator.RisingSeconds,
		generator.FallingSeconds,
		generator.DutyPercent,
	} {
		require.NotNil(t, number)
		require.Zero(t, *number)
		*number = 1
		require.Zero(t, zero)
	}

	require.Zero(t, *generator.SymmetryPercent)
	require.False(t, *generator.Output)
}

// TestResultConversionsPreserveNestedPresenceAndOwnership verifies observed fields remain separate from control writes.
//
// Example: fractional header offsets and zero sample counts retain presence without sharing memory.
func TestResultConversionsPreserveNestedPresenceAndOwnership(t *testing.T) {
	offset, count, samples := 1.25, uint32(0), uint64(0)
	instant := time.Unix(123, 456).UTC()
	state := &owonmodel.StateSnapshot{
		Device: &owonmodel.DeviceInfo{
			Manufacturer: "OWON",
			Model:        "HDS2202S",
			Serial:       "serial",
			Firmware:     "1",
			VendorID:     0x5345,
			ProductID:    0x1234,
			Capabilities: []owonmodel.Capability{owonmodel.CapabilityOscilloscope},
		},
		Measurements: []*owonmodel.Measurement{
			{
				Channel: owonmodel.Channel1,
				Kind:    owonmodel.MeasurementKindFrequency,
				Value:   12.5,
				Unit:    "Hz",
				Raw:     "12.5",
			},
			nil,
		},
		Channels: []*owonmodel.ChannelState{
			{
				Channel:            owonmodel.Channel2,
				Display:            true,
				Coupling:           owonmodel.CouplingDC,
				ProbeAttenuation:   10,
				Scale:              "1V",
				ScreenHeaderOffset: &offset,
			},
			nil,
		},
		Acquisition: &owonmodel.AcquisitionState{
			Mode:         owonmodel.AcquisitionModeAverage,
			AverageCount: &count,
			MemoryDepth:  "raw-depth",
		},
		Horizontal: &owonmodel.HorizontalState{
			Scale:              "20us",
			ScreenHeaderOffset: &offset,
		},
		Trigger: &owonmodel.TriggerState{
			Source:   owonmodel.TriggerSourceChannel1,
			Coupling: owonmodel.CouplingAC,
			Slope:    owonmodel.TriggerSlopeRising,
			Level:    0.25,
			Sweep:    owonmodel.TriggerSweepAuto,
			Status:   "RUN",
		},
		Generator: &owonmodel.GeneratorState{
			Waveform:          owonmodel.GeneratorWaveformSine,
			FrequencyHz:       1,
			PeriodSeconds:     2,
			AmplitudeVolts:    3,
			OffsetVolts:       4,
			HighVolts:         5,
			LowVolts:          6,
			SymmetryPercent:   7.5,
			PulseWidthSeconds: 8,
			RisingSeconds:     9,
			FallingSeconds:    10,
			DutyPercent:       11,
			Load:              owonmodel.GeneratorLoadOn,
			Output:            true,
		},
		DMM: &owonmodel.DMMState{
			Function:    owonmodel.DMMFunctionVoltage,
			CurrentType: owonmodel.DMMCurrentTypeDC,
			Relative:    true,
			Range:       owonmodel.DMMRangeV,
			AutoRange:   true,
		},
		ScreenHeaderJSON: []byte{0, 255},
		CapturedAt:       instant,
	}
	got := StateSnapshotToProto(state)
	require.Equal(t, instant, got.CapturedAt.AsTime())
	require.Equal(t, uint32(0x5345), got.Device.VendorId)
	require.Equal(t, uint32(0x1234), got.Device.ProductId)
	require.Equal(t, "serial", got.Device.Serial)
	require.Equal(t, []pb.Capability{pb.Capability_CAPABILITY_OSCILLOSCOPE}, got.Device.Capabilities)
	require.Equal(t, 12.5, got.Measurements[0].Value)
	require.Nil(t, got.Measurements[1])
	require.Nil(t, got.Channels[1])
	require.Equal(t, offset, *got.Channels[0].ScreenHeaderOffset)
	require.Equal(t, "raw-depth", got.Acquisition.MemoryDepth)
	require.Zero(t, *got.Acquisition.AverageCount)
	require.Equal(t, 7.5, got.Generator.SymmetryPercent)
	require.Equal(t, pb.DmmRange_DMM_RANGE_V, got.Dmm.Range)

	got.Device.Capabilities[0], got.Measurements[0].Value, got.ScreenHeaderJson[0], *got.Horizontal.ScreenHeaderOffset = pb.Capability_CAPABILITY_MULTIMETER, 0, 1, 0
	require.Equal(t, owonmodel.CapabilityOscilloscope, state.Device.Capabilities[0])
	require.Equal(t, 12.5, state.Measurements[0].Value)
	require.Equal(t, []byte{0, 255}, state.ScreenHeaderJSON)
	require.Equal(t, 1.25, offset)

	waveform := &owonmodel.Waveform{
		Channel:          owonmodel.Channel1,
		Data:             []byte{0, 255},
		Encoding:         "raw",
		ScreenHeaderJSON: []byte("{}"),
		CapturedAt:       instant,
		Metadata: &owonmodel.WaveformMetadata{
			SampleCount:       &samples,
			SampleRateHz:      1,
			SampleEncoding:    "unverified",
			XOriginSeconds:    &offset,
			XIncrementSeconds: &offset,
			YOriginVolts:      &offset,
			YIncrementVolts:   &offset,
			DataLengthBytes:   2,
		},
	}
	wire := WaveformToProto(waveform)
	require.Zero(t, wire.Sequence)
	require.Zero(t, *wire.Metadata.SampleCount)
	require.Equal(t, instant, wire.CapturedAt.AsTime())
	require.Equal(t, uint64(2), wire.Metadata.DataLengthBytes)

	wire.Data[0], wire.ScreenHeaderJson[0], *wire.Metadata.SampleCount, *wire.Metadata.YOriginVolts = 1, '[', 99, 2
	require.Equal(t, []byte{0, 255}, waveform.Data)
	require.Equal(t, []byte("{}"), waveform.ScreenHeaderJSON)
	require.Zero(t, samples)
	require.Equal(t, 1.25, offset)

	function := owonmodel.DMMFunctionVoltage
	dmm := DMMMeasurementToProto(&owonmodel.DMMMeasurement{
		Function:   &function,
		Value:      1.25,
		Unit:       "V",
		Raw:        "1.25 V",
		CapturedAt: instant,
	})
	require.Equal(t, pb.DmmFunction_DMM_FUNCTION_VOLTAGE, *dmm.Function)
	require.Equal(t, instant, dmm.CapturedAt.AsTime())

	*dmm.Function = pb.DmmFunction_DMM_FUNCTION_CURRENT
	require.Equal(t, owonmodel.DMMFunctionVoltage, function)
}

// TestConversionsPreserveNil verifies absent messages and optional fields stay absent.
//
// Example: omitted generator state never becomes an empty populated wire message.
func TestConversionsPreserveNil(t *testing.T) {
	for _, value := range []any{
		ChannelPatchFromProto(nil),
		AcquisitionPatchFromProto(nil),
		HorizontalPatchFromProto(nil),
		TriggerPatchFromProto(nil),
		MeasurementPatchFromProto(nil),
		GeneratorPatchFromProto(nil),
		DMMPatchFromProto(nil),
		StateRequestFromProto(nil),
		WaveformRequestFromProto(nil),
		MeasurementSelectorFromProto(nil),
		DeviceInfoToProto(nil),
		StateSnapshotToProto(nil),
		MeasurementToProto(nil),
		ChannelStateToProto(nil),
		AcquisitionStateToProto(nil),
		HorizontalStateToProto(nil),
		TriggerStateToProto(nil),
		GeneratorStateToProto(nil),
		DMMStateToProto(nil),
		DMMMeasurementToProto(nil),
		WaveformToProto(nil),
		WaveformMetadataToProto(nil),
	} {
		require.Nil(t, value)
	}

	require.Equal(t, new(owonmodel.ChannelPatch), ChannelPatchFromProto(new(pb.SetChannelRequest)))
	require.Equal(t, new(owonmodel.AcquisitionPatch), AcquisitionPatchFromProto(new(pb.SetAcquisitionRequest)))
	require.Equal(t, new(owonmodel.HorizontalPatch), HorizontalPatchFromProto(new(pb.SetHorizontalRequest)))
	require.Equal(t, new(owonmodel.TriggerPatch), TriggerPatchFromProto(new(pb.SetTriggerRequest)))
	require.Equal(t, new(owonmodel.MeasurementPatch), MeasurementPatchFromProto(new(pb.SetMeasurementRequest)))
	require.Equal(t, new(owonmodel.GeneratorPatch), GeneratorPatchFromProto(new(pb.SetGeneratorRequest)))
	require.Equal(t, new(owonmodel.DMMPatch), DMMPatchFromProto(new(pb.SetDmmRequest)))

	state := StateSnapshotToProto(new(owonmodel.StateSnapshot))
	require.Nil(t, state.Generator)
	require.Nil(t, state.Dmm)
	require.Nil(t, state.Channels)
	require.Nil(t, state.Measurements)
}
