package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// DMMPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: an explicit false Relative value becomes a present native field rather than an omitted setting.
func DMMPatchFromProto(value *pb.SetDmmRequest) *owonmodel.DMMPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.DMMPatch{
		Function:    convertPointer[pb.DmmFunction, owonmodel.DMMFunction](value.Function),
		CurrentType: convertPointer[pb.DmmCurrentType, owonmodel.DMMCurrentType](value.CurrentType),
		Relative:    clonePointer(value.Relative),
		Range:       convertPointer[pb.DmmRange, owonmodel.DMMRange](value.Range),
		AutoRange:   clonePointer(value.AutoRange),
	}
	return result
}

// DMMStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: DC voltage and its selected range retain their corresponding wire enum values.
func DMMStateToProto(value *owonmodel.DMMState) *pb.DmmState {
	if value == nil {
		return nil
	}
	result := &pb.DmmState{
		Function:           pb.DmmFunction(value.Function),
		CurrentType:        pb.DmmCurrentType(value.CurrentType),
		Relative:           value.Relative,
		Range:              pb.DmmRange(value.Range),
		AutoRange:          value.AutoRange,
		ObservedRangeToken: value.ObservedRangeToken,
	}
	return result
}

// DMMMeasurementToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a voltage reading retains its raw reply and capture time while an absent function stays nil.
func DMMMeasurementToProto(value *owonmodel.DMMMeasurement) *pb.DmmMeasurement {
	if value == nil {
		return nil
	}
	result := &pb.DmmMeasurement{
		Function:   convertPointer[owonmodel.DMMFunction, pb.DmmFunction](value.Function),
		Value:      value.Value,
		Unit:       value.Unit,
		Raw:        value.Raw,
		CapturedAt: timestamppb.New(value.CapturedAt),
	}
	return result
}
