package owonrpc_test

import (
	"context"
	"net"
	"net/url"
	"path/filepath"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owoncontrol"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonserver"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// countedUnixListener observes accepted connections without changing normal socket behavior.
//
// Example: a truncated-filename decoy must accept zero connections during a successful intended RPC.
type countedUnixListener struct {
	net.Listener
	Accepted atomic.Int32
}

// Accept records successful kernel socket connections before returning them to gRPC.
//
// Example: the intended listener counts the public client's sole connection.
func (listener *countedUnixListener) Accept() (net.Conn, error) {
	connection, err := listener.Listener.Accept()
	if err == nil {
		listener.Accepted.Add(1)
	}
	return connection, err
}

// serveUnixControlFixture registers production service logic on a real Unix socket.
//
// Example: endpoint tests exercise the native gRPC resolver rather than a recording-only dialer.
func serveUnixControlFixture(
	t *testing.T,
	path string,
	backend owonsession.Backend,
) *countedUnixListener {
	t.Helper()
	listener, err := net.Listen("unix", path)
	require.NoError(t, err)
	counted := &countedUnixListener{Listener: listener}
	server := grpc.NewServer(owonserver.GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(server, requireNewServer(t, newTestInstrument(t, backend)))
	done := make(chan error, 1)
	observability.Go(t.Context(),
		// serveFixture owns the accept loop until the test's cleanup joins it.
		//
		// Example: no socket worker survives its temporary directory.
		func(context.Context) { done <- server.Serve(counted) })
	t.Cleanup(
		// stopFixture joins gRPC after it closes the owned listener.
		//
		// Example: temporary socket removal happens after all serving work ends.
		func() {
			server.Stop()
			require.NoError(t, <-done)
		})
	return counted
}

// newUnixControlClient connects production service and client implementations through a kernel socket.
//
// Example: domain tests exercise actual protobuf RPCs with a controlled command-recording backend.
func newUnixControlClient(
	t *testing.T,
	backend owonsession.Backend,
) *owonclient.Client {
	t.Helper()
	path := filepath.Join(t.TempDir(), "instrument")
	serveUnixControlFixture(t, path, backend)
	endpoint := owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path}
	target, err := endpoint.Target()
	require.NoError(t, err)
	connection, err := grpc.NewClient(target, grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	t.Cleanup(
		// closeConnection releases the client before stopping its server.
		//
		// Example: a completed domain case leaves no RPC connection behind.
		func() { require.NoError(t, connection.Close()) })
	client, err := owonclient.NewClient(connection)
	require.NoError(t, err)
	return client
}

// TestUnixTargetDialsExactSocket verifies punctuation survives the real resolver and Unix listener boundary.
//
// Example: scope#name reaches that socket while the truncated scope decoy remains untouched.
func TestUnixTargetDialsExactSocket(t *testing.T) {
	for _, suffix := range []string{"#name", "?name", "%name", " name", "осциллограф"} {
		directory := t.TempDir()
		decoy := serveUnixControlFixture(t, filepath.Join(directory, "scope"), &scriptedBackend{Responses: map[string][]byte{"*IDN?": []byte("OWON,HDS2202S,25061855,V2.6.0")}})
		path := filepath.Join(directory, "scope"+suffix)
		intended := serveUnixControlFixture(t, path, &scriptedBackend{Responses: map[string][]byte{"*IDN?": []byte("OWON,HDS2202S,25061855,V2.6.0")}})
		encoded := &url.URL{Scheme: "unix", Path: path}
		endpoint, err := owonrpc.ParseEndpoint(encoded.String())
		require.NoError(t, err)
		target, err := endpoint.Target()
		require.NoError(t, err)
		connection, err := grpc.NewClient(target, grpc.WithTransportCredentials(insecure.NewCredentials()))
		require.NoError(t, err)
		client, err := owonclient.NewClient(connection)
		require.NoError(t, err)
		ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
		info, callErr := client.DeviceInfo(ctx)
		cancel()
		require.NoError(t, connection.Close())
		require.NoError(t, callErr)
		require.Equal(t, "25061855", info.Serial)
		require.Positive(t, intended.Accepted.Load(), suffix)
		require.Zero(t, decoy.Accepted.Load(), suffix)
	}
}

// newTestInstrument constructs an instrument backed by one deterministic recorder.
//
// Example: control tests use it to assert the exact SCPI command sequence.
func newTestInstrument(
	t *testing.T,
	backend owonsession.Backend,
) *owoncontrol.Controller {
	t.Helper()
	transport, err := owonsession.New(backend, owonsession.Config{ExpectedSerial: "25061855"})
	require.NoError(t, err)
	instrument, err := owoncontrol.New(transport, owonmodel.DeviceIdentity{})
	require.NoError(t, err)

	return instrument
}

// scriptedBackend records transport activity and returns deterministic results.
//
// Example: tests configure one timeout followed by one successful exchange.
type scriptedBackend struct {
	Commands       []string
	ExchangeErrors []error
	ReopenCalls    int
	ReopenedSerial owonmodel.SerialNumber
	ReopenError    error
	Responses      map[string][]byte
	CloseErrors    []error
	CloseCalls     int
}

// Exchange records one command and returns its scripted response.
//
// Example: a configured first error models an ambiguous USB transfer.
func (backend *scriptedBackend) Exchange(
	_ context.Context,
	command owonprotocol.Command,
) ([]byte, error) {
	backend.Commands = append(backend.Commands, command.Text)
	if len(backend.ExchangeErrors) > 0 {
		err := backend.ExchangeErrors[0]
		backend.ExchangeErrors = backend.ExchangeErrors[1:]
		if err != nil {
			return nil, err
		}
	}
	return append([]byte(nil), backend.Responses[command.Text]...), nil
}

// ReopenAndValidate records the expected serial and returns its scripted error.
//
// Example: recovery tests assert that serial validation precedes a new write.
func (backend *scriptedBackend) ReopenAndValidate(
	_ context.Context,
	serial owonmodel.SerialNumber,
) error {
	backend.ReopenCalls++
	backend.ReopenedSerial = serial
	return backend.ReopenError
}

// Close satisfies Backend for deterministic tests.
//
// Example: no resources are owned by this in-memory backend.
func (backend *scriptedBackend) Close(_ context.Context) error {
	backend.CloseCalls++
	if len(backend.CloseErrors) == 0 {
		return nil
	}
	err := backend.CloseErrors[0]
	backend.CloseErrors = backend.CloseErrors[1:]

	return err
}

// requireNewServer constructs a valid test service or stops the current test.
//
// Example: gRPC harness setup registers its returned server implementation.
func requireNewServer(
	t *testing.T,
	instrument *owoncontrol.Controller,
) *owonserver.Server {
	t.Helper()
	server, err := owonserver.NewServer(instrument)
	require.NoError(t, err)

	return server
}
