package owonrpc

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestEnumCorrespondence guards the fixed-width numeric contract used by explicit field conversions.
//
// Example: changing a native enum's order cannot silently change its wire meaning.
func TestEnumCorrespondence(t *testing.T) {
	for _, value := range []struct {
		Name   string
		Native int32
		Wire   int32
	}{
		{"ChannelUnspecified", int32(owonmodel.ChannelUnspecified), int32(pb.Channel_CHANNEL_UNSPECIFIED)},
		{"Channel1", int32(owonmodel.Channel1), int32(pb.Channel_CHANNEL_1)},
		{"Channel2", int32(owonmodel.Channel2), int32(pb.Channel_CHANNEL_2)},
		{"CouplingUnspecified", int32(owonmodel.CouplingUnspecified), int32(pb.Coupling_COUPLING_UNSPECIFIED)},
		{"CouplingAC", int32(owonmodel.CouplingAC), int32(pb.Coupling_COUPLING_AC)},
		{"CouplingDC", int32(owonmodel.CouplingDC), int32(pb.Coupling_COUPLING_DC)},
		{"CouplingGround", int32(owonmodel.CouplingGround), int32(pb.Coupling_COUPLING_GROUND)},
		{"AcquisitionModeUnspecified", int32(owonmodel.AcquisitionModeUnspecified), int32(pb.AcquisitionMode_ACQUISITION_MODE_UNSPECIFIED)},
		{"AcquisitionModeSample", int32(owonmodel.AcquisitionModeSample), int32(pb.AcquisitionMode_ACQUISITION_MODE_SAMPLE)},
		{"AcquisitionModePeakDetect", int32(owonmodel.AcquisitionModePeakDetect), int32(pb.AcquisitionMode_ACQUISITION_MODE_PEAK_DETECT)},
		{"AcquisitionModeAverage", int32(owonmodel.AcquisitionModeAverage), int32(pb.AcquisitionMode_ACQUISITION_MODE_AVERAGE)},
		{"AcquisitionMemoryDepthUnspecified", int32(owonmodel.AcquisitionMemoryDepthUnspecified), int32(pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_UNSPECIFIED)},
		{"AcquisitionMemoryDepth4K", int32(owonmodel.AcquisitionMemoryDepth4K), int32(pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_4K)},
		{"AcquisitionMemoryDepth8K", int32(owonmodel.AcquisitionMemoryDepth8K), int32(pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_8K)},
		{"TriggerSourceUnspecified", int32(owonmodel.TriggerSourceUnspecified), int32(pb.TriggerSource_TRIGGER_SOURCE_UNSPECIFIED)},
		{"TriggerSourceChannel1", int32(owonmodel.TriggerSourceChannel1), int32(pb.TriggerSource_TRIGGER_SOURCE_CHANNEL_1)},
		{"TriggerSourceChannel2", int32(owonmodel.TriggerSourceChannel2), int32(pb.TriggerSource_TRIGGER_SOURCE_CHANNEL_2)},
		{"TriggerSourceExternal", int32(owonmodel.TriggerSourceExternal), int32(pb.TriggerSource_TRIGGER_SOURCE_EXTERNAL)},
		{"TriggerSlopeUnspecified", int32(owonmodel.TriggerSlopeUnspecified), int32(pb.TriggerSlope_TRIGGER_SLOPE_UNSPECIFIED)},
		{"TriggerSlopeRising", int32(owonmodel.TriggerSlopeRising), int32(pb.TriggerSlope_TRIGGER_SLOPE_RISING)},
		{"TriggerSlopeFalling", int32(owonmodel.TriggerSlopeFalling), int32(pb.TriggerSlope_TRIGGER_SLOPE_FALLING)},
		{"TriggerSweepUnspecified", int32(owonmodel.TriggerSweepUnspecified), int32(pb.TriggerSweep_TRIGGER_SWEEP_UNSPECIFIED)},
		{"TriggerSweepAuto", int32(owonmodel.TriggerSweepAuto), int32(pb.TriggerSweep_TRIGGER_SWEEP_AUTO)},
		{"TriggerSweepNormal", int32(owonmodel.TriggerSweepNormal), int32(pb.TriggerSweep_TRIGGER_SWEEP_NORMAL)},
		{"TriggerSweepSingle", int32(owonmodel.TriggerSweepSingle), int32(pb.TriggerSweep_TRIGGER_SWEEP_SINGLE)},
		{"MeasurementKindUnspecified", int32(owonmodel.MeasurementKindUnspecified), int32(pb.MeasurementKind_MEASUREMENT_KIND_UNSPECIFIED)},
		{"MeasurementKindUnknown", int32(owonmodel.MeasurementKindUnknown), int32(pb.MeasurementKind_MEASUREMENT_KIND_UNKNOWN)},
		{"MeasurementKindMaximum", int32(owonmodel.MeasurementKindMaximum), int32(pb.MeasurementKind_MEASUREMENT_KIND_MAXIMUM)},
		{"MeasurementKindMinimum", int32(owonmodel.MeasurementKindMinimum), int32(pb.MeasurementKind_MEASUREMENT_KIND_MINIMUM)},
		{"MeasurementKindPeakToPeak", int32(owonmodel.MeasurementKindPeakToPeak), int32(pb.MeasurementKind_MEASUREMENT_KIND_PEAK_TO_PEAK)},
		{"MeasurementKindAmplitude", int32(owonmodel.MeasurementKindAmplitude), int32(pb.MeasurementKind_MEASUREMENT_KIND_AMPLITUDE)},
		{"MeasurementKindAverage", int32(owonmodel.MeasurementKindAverage), int32(pb.MeasurementKind_MEASUREMENT_KIND_AVERAGE)},
		{"MeasurementKindPeriod", int32(owonmodel.MeasurementKindPeriod), int32(pb.MeasurementKind_MEASUREMENT_KIND_PERIOD)},
		{"MeasurementKindFrequency", int32(owonmodel.MeasurementKindFrequency), int32(pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY)},
		{"GeneratorWaveformUnspecified", int32(owonmodel.GeneratorWaveformUnspecified), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_UNSPECIFIED)},
		{"GeneratorWaveformSine", int32(owonmodel.GeneratorWaveformSine), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINE)},
		{"GeneratorWaveformSquare", int32(owonmodel.GeneratorWaveformSquare), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_SQUARE)},
		{"GeneratorWaveformRamp", int32(owonmodel.GeneratorWaveformRamp), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_RAMP)},
		{"GeneratorWaveformPulse", int32(owonmodel.GeneratorWaveformPulse), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_PULSE)},
		{"GeneratorWaveformAmpALT", int32(owonmodel.GeneratorWaveformAmpALT), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_AMP_ALT)},
		{"GeneratorWaveformAttALT", int32(owonmodel.GeneratorWaveformAttALT), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_ATT_ALT)},
		{"GeneratorWaveformStairDown", int32(owonmodel.GeneratorWaveformStairDown), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_STAIR_DOWN)},
		{"GeneratorWaveformStairUpDown", int32(owonmodel.GeneratorWaveformStairUpDown), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_STAIR_UP_DOWN)},
		{"GeneratorWaveformStairUp", int32(owonmodel.GeneratorWaveformStairUp), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_STAIR_UP)},
		{"GeneratorWaveformBesselJ", int32(owonmodel.GeneratorWaveformBesselJ), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_BESSEL_J)},
		{"GeneratorWaveformBesselY", int32(owonmodel.GeneratorWaveformBesselY), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_BESSEL_Y)},
		{"GeneratorWaveformSinc", int32(owonmodel.GeneratorWaveformSinc), int32(pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINC)},
		{"GeneratorLoadUnspecified", int32(owonmodel.GeneratorLoadUnspecified), int32(pb.GeneratorLoad_GENERATOR_LOAD_UNSPECIFIED)},
		{"GeneratorLoadOn", int32(owonmodel.GeneratorLoadOn), int32(pb.GeneratorLoad_GENERATOR_LOAD_ON)},
		{"GeneratorLoadOff", int32(owonmodel.GeneratorLoadOff), int32(pb.GeneratorLoad_GENERATOR_LOAD_OFF)},
		{"DMMFunctionUnspecified", int32(owonmodel.DMMFunctionUnspecified), int32(pb.DmmFunction_DMM_FUNCTION_UNSPECIFIED)},
		{"DMMFunctionVoltage", int32(owonmodel.DMMFunctionVoltage), int32(pb.DmmFunction_DMM_FUNCTION_VOLTAGE)},
		{"DMMFunctionCurrent", int32(owonmodel.DMMFunctionCurrent), int32(pb.DmmFunction_DMM_FUNCTION_CURRENT)},
		{"DMMFunctionResistance", int32(owonmodel.DMMFunctionResistance), int32(pb.DmmFunction_DMM_FUNCTION_RESISTANCE)},
		{"DMMFunctionCapacitance", int32(owonmodel.DMMFunctionCapacitance), int32(pb.DmmFunction_DMM_FUNCTION_CAPACITANCE)},
		{"DMMFunctionDiode", int32(owonmodel.DMMFunctionDiode), int32(pb.DmmFunction_DMM_FUNCTION_DIODE)},
		{"DMMFunctionContinuity", int32(owonmodel.DMMFunctionContinuity), int32(pb.DmmFunction_DMM_FUNCTION_CONTINUITY)},
		{"DMMRangeUnspecified", int32(owonmodel.DMMRangeUnspecified), int32(pb.DmmRange_DMM_RANGE_UNSPECIFIED)},
		{"DMMRangeOn", int32(owonmodel.DMMRangeOn), int32(pb.DmmRange_DMM_RANGE_ON)},
		{"DMMRangeMV", int32(owonmodel.DMMRangeMV), int32(pb.DmmRange_DMM_RANGE_MV)},
		{"DMMRangeV", int32(owonmodel.DMMRangeV), int32(pb.DmmRange_DMM_RANGE_V)},
		{"DMMCurrentTypeUnspecified", int32(owonmodel.DMMCurrentTypeUnspecified), int32(pb.DmmCurrentType_DMM_CURRENT_TYPE_UNSPECIFIED)},
		{"DMMCurrentTypeAC", int32(owonmodel.DMMCurrentTypeAC), int32(pb.DmmCurrentType_DMM_CURRENT_TYPE_AC)},
		{"DMMCurrentTypeDC", int32(owonmodel.DMMCurrentTypeDC), int32(pb.DmmCurrentType_DMM_CURRENT_TYPE_DC)},
		{"CapabilityUnspecified", int32(owonmodel.CapabilityUnspecified), int32(pb.Capability_CAPABILITY_UNSPECIFIED)},
		{"CapabilityOscilloscope", int32(owonmodel.CapabilityOscilloscope), int32(pb.Capability_CAPABILITY_OSCILLOSCOPE)},
		{"CapabilityWaveformGenerator", int32(owonmodel.CapabilityWaveformGenerator), int32(pb.Capability_CAPABILITY_WAVEFORM_GENERATOR)},
		{"CapabilityMultimeter", int32(owonmodel.CapabilityMultimeter), int32(pb.Capability_CAPABILITY_MULTIMETER)},
		{"CapabilityScreenWaveform", int32(owonmodel.CapabilityScreenWaveform), int32(pb.Capability_CAPABILITY_SCREEN_WAVEFORM)},
		{"ResponseModeUnspecified", int32(owonprotocol.ResponseModeUnspecified), int32(pb.ResponseMode_RESPONSE_MODE_UNSPECIFIED)},
		{"ResponseModeNone", int32(owonprotocol.ResponseModeNone), int32(pb.ResponseMode_RESPONSE_MODE_NONE)},
		{"ResponseModeASCII", int32(owonprotocol.ResponseModeASCII), int32(pb.ResponseMode_RESPONSE_MODE_ASCII_LINE)},
		{"ResponseModeLengthPrefixed", int32(owonprotocol.ResponseModeLengthPrefixed), int32(pb.ResponseMode_RESPONSE_MODE_OWON_LENGTH_PREFIXED)},
	} {
		require.Equal(t, value.Wire, value.Native, value.Name)
	}
}
