package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// GeneratorPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: waveform and frequency settings are copied while an omitted output switch stays nil.
func GeneratorPatchFromProto(value *pb.SetGeneratorRequest) *owonmodel.GeneratorPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.GeneratorPatch{
		Waveform:          convertPointer[pb.GeneratorWaveform, owonmodel.GeneratorWaveform](value.Waveform),
		FrequencyHz:       clonePointer(value.FrequencyHz),
		PeriodSeconds:     clonePointer(value.PeriodSeconds),
		AmplitudeVolts:    clonePointer(value.AmplitudeVolts),
		OffsetVolts:       clonePointer(value.OffsetVolts),
		HighVolts:         clonePointer(value.HighVolts),
		LowVolts:          clonePointer(value.LowVolts),
		SymmetryPercent:   clonePointer(value.SymmetryPercent),
		PulseWidthSeconds: clonePointer(value.PulseWidthSeconds),
		RisingSeconds:     clonePointer(value.RisingSeconds),
		FallingSeconds:    clonePointer(value.FallingSeconds),
		DutyPercent:       clonePointer(value.DutyPercent),
		Load:              convertPointer[pb.GeneratorLoad, owonmodel.GeneratorLoad](value.Load),
		Output:            clonePointer(value.Output),
	}
	return result
}

// GeneratorStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a sine-wave setting retains its frequency in Hz and amplitude in volts as separate fields.
func GeneratorStateToProto(value *owonmodel.GeneratorState) *pb.GeneratorState {
	if value == nil {
		return nil
	}
	result := &pb.GeneratorState{
		Waveform:          pb.GeneratorWaveform(value.Waveform),
		FrequencyHz:       value.FrequencyHz,
		PeriodSeconds:     value.PeriodSeconds,
		AmplitudeVolts:    value.AmplitudeVolts,
		OffsetVolts:       value.OffsetVolts,
		HighVolts:         value.HighVolts,
		LowVolts:          value.LowVolts,
		SymmetryPercent:   value.SymmetryPercent,
		PulseWidthSeconds: value.PulseWidthSeconds,
		RisingSeconds:     value.RisingSeconds,
		FallingSeconds:    value.FallingSeconds,
		DutyPercent:       value.DutyPercent,
		Load:              pb.GeneratorLoad(value.Load),
		Output:            value.Output,
	}
	return result
}
