package owonrpc

import (
	"slices"

	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// GeneratorPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: waveform and frequency settings are copied while an omitted output switch stays nil.
func GeneratorPatchFromProto(value *pb.SetGeneratorRequest) *owonmodel.GeneratorPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.GeneratorPatch{
		Waveform:          convertPointer[pb.GeneratorWaveform, owonmodel.GeneratorWaveform](value.Waveform),
		FrequencyHz:       clonePointer(value.FrequencyHz),
		PeriodSeconds:     clonePointer(value.PeriodSeconds),
		AmplitudeVolts:    clonePointer(value.AmplitudeVolts),
		OffsetVolts:       clonePointer(value.OffsetVolts),
		HighVolts:         clonePointer(value.HighVolts),
		LowVolts:          clonePointer(value.LowVolts),
		SymmetryPercent:   clonePointer(value.SymmetryPercent),
		PulseWidthSeconds: clonePointer(value.PulseWidthSeconds),
		RisingSeconds:     clonePointer(value.RisingSeconds),
		FallingSeconds:    clonePointer(value.FallingSeconds),
		DutyPercent:       clonePointer(value.DutyPercent),
		Load:              convertPointer[pb.GeneratorLoad, owonmodel.GeneratorLoad](value.Load),
		Output:            clonePointer(value.Output),
	}
	return result
}

// GeneratorStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a sine-wave setting retains its frequency in Hz and amplitude in volts as separate fields.
func GeneratorStateToProto(value *owonmodel.GeneratorState) *pb.GeneratorState {
	if value == nil {
		return nil
	}
	result := &pb.GeneratorState{
		Waveform:          pb.GeneratorWaveform(value.Waveform),
		FrequencyHz:       value.FrequencyHz,
		PeriodSeconds:     value.PeriodSeconds,
		AmplitudeVolts:    value.AmplitudeVolts,
		OffsetVolts:       value.OffsetVolts,
		HighVolts:         value.HighVolts,
		LowVolts:          value.LowVolts,
		SymmetryPercent:   value.SymmetryPercent,
		PulseWidthSeconds: value.PulseWidthSeconds,
		RisingSeconds:     value.RisingSeconds,
		FallingSeconds:    value.FallingSeconds,
		DutyPercent:       value.DutyPercent,
		Load:              pb.GeneratorLoad(value.Load),
		Output:            value.Output,
	}
	return result
}

// GeneratorOperationResultToProto converts an observed native generator result with presence-aware readbacks.
//
// Example: an omitted waveform context remains absent while an observed OFF output retains its explicit false value.
func GeneratorOperationResultToProto(value *owonmodel.GeneratorOperationResult) *pb.GeneratorOperationResult {
	if value == nil {
		return nil
	}
	result := &pb.GeneratorOperationResult{
		Delivery:        pb.GeneratorDeliveryStatus(value.Delivery),
		CompletedWrites: slices.Clone(value.CompletedWrites),
		Observation:     generatorObservationToProto(value.Observation),
		Compensation:    generatorOutputCompensationToProto(value.Compensation),
	}
	return result
}

// generatorObservationToProto converts context and logical output readbacks without adding electrical claims.
//
// Example: a malformed raw waveform token is retained with no guessed enum value.
func generatorObservationToProto(value *owonmodel.GeneratorObservation) *pb.GeneratorObservation {
	if value == nil {
		return nil
	}
	result := &pb.GeneratorObservation{
		Context: generatorWaveformContextToProto(value.Context),
		Output: &pb.GeneratorOutputObservation{
			Status: pb.GeneratorObservationStatus(value.Output.Status),
			Value:  clonePointer(value.Output.Value),
			Token:  value.Output.Token,
			Raw:    value.Output.Raw,
			Reason: value.Output.Reason,
		},
	}
	if !value.CapturedAt.IsZero() {
		result.CapturedAt = timestamppb.New(value.CapturedAt)
	}
	return result
}

// generatorWaveformContextToProto converts explicit requested and observed waveform presence.
//
// Example: an unknown observed token leaves Observed nil while preserving ObservedToken.
func generatorWaveformContextToProto(value owonmodel.GeneratorWaveformContext) *pb.GeneratorWaveformContext {
	return &pb.GeneratorWaveformContext{
		Requested:     convertPointer[owonmodel.GeneratorWaveform, pb.GeneratorWaveform](value.Requested),
		Observed:      convertPointer[owonmodel.GeneratorWaveform, pb.GeneratorWaveform](value.Observed),
		ObservedToken: value.ObservedToken,
		ObservedRaw:   value.ObservedRaw,
		Reason:        value.Reason,
		Match:         pb.GeneratorContextStatus(value.Match),
	}
}

// generatorOutputCompensationToProto converts operation-local logical output restoration state.
//
// Example: a verified OFF restoration carries both requested and observed false presence.
func generatorOutputCompensationToProto(value owonmodel.GeneratorOutputCompensation) *pb.GeneratorOutputCompensation {
	return &pb.GeneratorOutputCompensation{
		Requested: clonePointer(value.Requested),
		Observed:  clonePointer(value.Observed),
		Status:    pb.GeneratorOutputCompensationStatus(value.Status),
	}
}
