package owonrpc

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/encoding/protojson"
)

// TestGeneratorBuiltinWireMappings preserves eight named enum values across JSON and native conversion.
//
// Example: STAIR_UP_DOWN maps to native value eight with independently owned optional fields.
func TestGeneratorBuiltinWireMappings(t *testing.T) {
	for index, suffix := range []string{"AMP_ALT", "ATT_ALT", "STAIR_DOWN", "STAIR_UP_DOWN", "STAIR_UP", "BESSEL_J", "BESSEL_Y", "SINC"} {
		var wire pb.SetGeneratorRequest
		require.NoError(t, protojson.Unmarshal([]byte(fmt.Sprintf(`{"waveform":"GENERATOR_WAVEFORM_%s","output":false}`, suffix)), &wire))
		require.Equal(t, pb.GeneratorWaveform(index+5), *wire.Waveform)
		native := GeneratorPatchFromProto(&wire)
		require.Equal(t, owonmodel.GeneratorWaveform(index+5), *native.Waveform)
		require.NoError(t, native.Validate())
		require.NotNil(t, native.Output)
		require.False(t, *native.Output)
		*wire.Output = true
		*wire.Waveform = pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINE
		require.False(t, *native.Output)
		require.Equal(t, owonmodel.GeneratorWaveform(index+5), *native.Waveform)
		require.Equal(t, pb.GeneratorWaveform(index+5), GeneratorStateToProto(&owonmodel.GeneratorState{Waveform: *native.Waveform}).Waveform)
	}
	unknown := pb.GeneratorWaveform(999)
	native := GeneratorPatchFromProto(&pb.SetGeneratorRequest{Waveform: &unknown})
	require.Equal(t, owonmodel.GeneratorWaveform(999), *native.Waveform)
	require.Nil(t, native.Output)
	var invalid *owonmodel.ErrInvalidRequest
	require.ErrorAs(t, native.Validate(), &invalid)
}

// TestGeneratorOperationResultToProtoRetainsUnknownContextAndExplicitFalse verifies additive presence conversion.
//
// Example: a malformed raw waveform token keeps Observed nil while an explicit false output remains present.
func TestGeneratorOperationResultToProtoRetainsUnknownContextAndExplicitFalse(t *testing.T) {
	waveform := owonmodel.GeneratorWaveformSine
	output := false
	result := GeneratorOperationResultToProto(&owonmodel.GeneratorOperationResult{
		Delivery: owonmodel.GeneratorDeliveryPartialOrUnknown,
		Observation: &owonmodel.GeneratorObservation{
			Context: owonmodel.GeneratorWaveformContext{
				Requested:     &waveform,
				ObservedToken: "FUTURE_WAVE",
				ObservedRaw:   "FUTURE_WAVE",
				Reason:        "FUNCTION? reply token is unknown",
				Match:         owonmodel.GeneratorContextUnknown,
			},
			Output: owonmodel.GeneratorOutputObservation{
				Status: owonmodel.GeneratorObservationObserved,
				Value:  &output,
				Token:  "OFF",
				Raw:    "OFF",
			},
		},
		Compensation: owonmodel.GeneratorOutputCompensation{
			Requested: &output,
			Status:    owonmodel.GeneratorOutputCompensationVerified,
		},
	})
	require.Equal(t, pb.GeneratorDeliveryStatus_GENERATOR_DELIVERY_PARTIAL_OR_UNKNOWN, result.Delivery)
	require.NotNil(t, result.Observation.Context.Requested)
	require.Nil(t, result.Observation.Context.Observed)
	require.Equal(t, "FUTURE_WAVE", result.Observation.Context.ObservedToken)
	require.Equal(t, "FUTURE_WAVE", result.Observation.Context.ObservedRaw)
	require.Equal(t, "FUNCTION? reply token is unknown", result.Observation.Context.Reason)
	require.NotNil(t, result.Observation.Output.Value)
	require.False(t, result.Observation.Output.GetValue())
	require.NotNil(t, result.Compensation.Requested)
	require.False(t, result.Compensation.GetRequested())
}
