package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// HorizontalPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: an integer OffsetDivisions value above float64 precision remains exact.
func HorizontalPatchFromProto(value *pb.SetHorizontalRequest) *owonmodel.HorizontalPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.HorizontalPatch{
		Scale:           clonePointer(value.Scale),
		OffsetDivisions: clonePointer(value.OffsetDivisions),
	}
	return result
}

// HorizontalStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: an absent ScreenHeaderOffset stays nil rather than becoming an observed zero.
func HorizontalStateToProto(value *owonmodel.HorizontalState) *pb.HorizontalState {
	if value == nil {
		return nil
	}
	result := &pb.HorizontalState{
		Scale:              value.Scale,
		ScreenHeaderOffset: clonePointer(value.ScreenHeaderOffset),
	}
	return result
}
