package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// DeviceInfoToProto converts native values to wire fields with independent mutable ownership.
//
// Example: identity text and USB identifiers are retained while the capability slice is copied independently.
func DeviceInfoToProto(value *owonmodel.DeviceInfo) *pb.DeviceInfo {
	if value == nil {
		return nil
	}
	result := &pb.DeviceInfo{
		Manufacturer: value.Manufacturer,
		Model:        value.Model,
		Serial:       string(value.Serial),
		Firmware:     value.Firmware,
		VendorId:     uint32(value.VendorID),
		ProductId:    uint32(value.ProductID),
		Capabilities: nil,
	}
	if value.Capabilities != nil {
		result.Capabilities = make([]pb.Capability, len(value.Capabilities))
		for index, item := range value.Capabilities {
			result.Capabilities[index] = pb.Capability(item)
		}
	}
	return result
}
