package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// MeasurementSelectorFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: a CH1 frequency selector becomes Channel1 with MeasurementKindFrequency.
func MeasurementSelectorFromProto(value *pb.MeasurementSelector) *owonmodel.MeasurementSelector {
	if value == nil {
		return nil
	}
	result := &owonmodel.MeasurementSelector{
		Channel: owonmodel.Channel(value.Channel),
		Kind:    owonmodel.MeasurementKind(value.Kind),
	}
	return result
}

// MeasurementToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a frequency result retains its numeric value, Hz unit, and original device text.
func MeasurementToProto(value *owonmodel.Measurement) *pb.Measurement {
	if value == nil {
		return nil
	}
	result := &pb.Measurement{
		Channel: pb.Channel(value.Channel),
		Kind:    pb.MeasurementKind(value.Kind),
		Value:   value.Value,
		Unit:    value.Unit,
		Raw:     value.Raw,
	}
	return result
}

// MeasurementPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: the display switch is copied independently and nil entries in the visible-selector list stay nil.
func MeasurementPatchFromProto(value *pb.SetMeasurementRequest) *owonmodel.MeasurementPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.MeasurementPatch{
		Display:        clonePointer(value.Display),
		Visible:        nil,
		ReplaceVisible: clonePointer(value.ReplaceVisible),
	}
	if value.Visible != nil {
		result.Visible = make([]*owonmodel.MeasurementSelector, len(value.Visible))
		for index, item := range value.Visible {
			result.Visible[index] = MeasurementSelectorFromProto(item)
		}
	}
	return result
}
