package owonrpc

import (
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/encoding/protojson"
)

// TestOffsetJSONRejectsFractionalWrites verifies integer grammar at the public JSON boundary.
//
// Example: a fractional channel patch cannot reach the device, even with a valid display field.
func TestOffsetJSONRejectsFractionalWrites(t *testing.T) {
	t.Parallel()
	for _, value := range []string{`0.25`, `"-0.25"`, `"NaN"`, `"Infinity"`, `"9223372036854775808"`, `"-9223372036854775809"`} {
		var request pb.SetChannelRequest
		err := protojson.Unmarshal([]byte(`{"channel":"CHANNEL_1","display":true,"offsetDivisions":`+value+`}`), &request)
		require.Error(t, err, value)
	}
}
