package owonrpc_test

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// TestEventRoundTripPreservesTypedPayload verifies the stream's typed oneof wire contract.
//
// Example: a frequency measurement survives protobuf serialization without losing its kind.
func TestEventRoundTripPreservesTypedPayload(t *testing.T) {
	t.Parallel()

	want := &pb.Event{
		Timestamp: timestamppb.New(time.Unix(123, 456)),
		Sequence:  42,
		Payload: &pb.Event_State{
			State: &pb.StateSnapshot{
				Device: &pb.DeviceInfo{Model: "HDS2202S"},
				Measurements: []*pb.Measurement{
					{Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY, Value: 1000},
				},
			},
		},
	}
	encoded, err := proto.Marshal(want)
	require.NoError(t, err)
	got := new(pb.Event)
	require.NoError(t, proto.Unmarshal(encoded, got))
	require.True(t, proto.Equal(want, got))
}

// TestDescriptorUsesStableNamespace verifies generated service metadata and method paths.
//
// Example: GetDeviceInfo is addressed as `/xaionaro.owon.OwonService/GetDeviceInfo`.
func TestDescriptorUsesStableNamespace(t *testing.T) {
	t.Parallel()

	file := pb.File_pkg_owonrpc_owon_proto
	require.Equal(t, protoreflect.FullName("xaionaro.owon"), file.Package())
	service := file.Services().ByName("OwonService")
	require.NotNil(t, service)
	require.Equal(t, "/xaionaro.owon.OwonService/GetDeviceInfo", pb.OwonService_GetDeviceInfo_FullMethodName)
	require.Equal(t, protoreflect.FullName("xaionaro.owon.OwonService.GetWaveform"), service.Methods().ByName("GetWaveform").FullName())
}

// TestExecuteRequestRetainsExplicitModes verifies raw command framing remains caller-selected.
//
// Example: NONE, ASCII_LINE, and OWON_LENGTH_PREFIXED retain distinct enum values.
func TestExecuteRequestRetainsExplicitModes(t *testing.T) {
	t.Parallel()

	require.NotEqual(t, pb.ResponseMode_RESPONSE_MODE_NONE, pb.ResponseMode_RESPONSE_MODE_ASCII_LINE)
	require.NotEqual(t, pb.ResponseMode_RESPONSE_MODE_ASCII_LINE, pb.ResponseMode_RESPONSE_MODE_OWON_LENGTH_PREFIXED)
	request := &pb.ExecuteRequest{Command: "*IDN?", ResponseMode: pb.ResponseMode_RESPONSE_MODE_ASCII_LINE}
	require.Equal(t, "*IDN?", request.GetCommand())
	require.Equal(t, pb.ResponseMode_RESPONSE_MODE_ASCII_LINE, request.GetResponseMode())
}

// TestControlDescriptorPreservesPresenceAndFieldNumbers verifies breaking wire drift is detected.
//
// Example: trigger level remains an optional double at field four after regeneration.
func TestControlDescriptorPreservesPresenceAndFieldNumbers(t *testing.T) {
	t.Parallel()

	file := pb.File_pkg_owonrpc_owon_proto
	triggerLevel := file.Messages().ByName("SetTriggerRequest").Fields().ByName("level_volts")
	require.Equal(t, protoreflect.FieldNumber(4), triggerLevel.Number())
	require.Equal(t, protoreflect.DoubleKind, triggerLevel.Kind())
	require.True(t, triggerLevel.HasPresence())
	for _, name := range []protoreflect.Name{"SetHorizontalRequest", "SetChannelRequest"} {
		offset := file.Messages().ByName(name).Fields().ByName("offset_divisions")
		require.NotNil(t, offset)
		require.Equal(t, protoreflect.Int64Kind, offset.Kind())
		require.True(t, offset.HasPresence())
	}
	for _, name := range []protoreflect.Name{"HorizontalState", "ChannelState"} {
		offset := file.Messages().ByName(name).Fields().ByName("screen_header_offset")
		require.NotNil(t, offset)
		require.Equal(t, protoreflect.DoubleKind, offset.Kind())
		require.True(t, offset.HasPresence())
	}
	averageCount := file.Messages().ByName("AcquisitionState").Fields().ByName("average_count")
	require.True(t, averageCount.HasPresence())
	dmmFunction := file.Messages().ByName("DmmMeasurement").Fields().ByName("function")
	require.True(t, dmmFunction.HasPresence())
	waveformMetadata := file.Messages().ByName("WaveformMetadata")
	sampleCount := waveformMetadata.Fields().ByName("sample_count")
	require.Equal(t, protoreflect.FieldNumber(1), sampleCount.Number())
	require.True(t, sampleCount.HasPresence())
	dataLength := waveformMetadata.Fields().ByName("data_length_bytes")
	require.Equal(t, protoreflect.FieldNumber(8), dataLength.Number())
	require.Equal(t, protoreflect.Uint64Kind, dataLength.Kind())
}

// TestCurrentProtoJSONRoundTripPreservesPresence verifies the intentionally breaking schema's JSON contract.
//
// Example: exact integer offsets, fractional voltages, and zero sample counts remain present after JSON transport.
func TestCurrentProtoJSONRoundTripPreservesPresence(t *testing.T) {
	t.Parallel()

	offset := int64(9007199254740993)
	levelVolts := 0.25
	sampleCount := uint64(0)
	want := &pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{
		Metadata: &pb.WaveformMetadata{SampleCount: &sampleCount},
	}}, Timestamp: timestamppb.Now()}
	request := &pb.SetHorizontalRequest{OffsetDivisions: &offset}
	trigger := &pb.SetTriggerRequest{LevelVolts: &levelVolts}

	for _, message := range []proto.Message{want, request, trigger} {
		encoded, err := protojson.Marshal(message)
		require.NoError(t, err)
		decoded := message.ProtoReflect().Type().New().Interface()
		require.NoError(t, protojson.Unmarshal(encoded, decoded))
		switch typed := decoded.(type) {
		case *pb.Event:
			require.NotNil(t, typed.GetWaveform().GetMetadata().SampleCount)
		case *pb.SetHorizontalRequest:
			require.NotNil(t, typed.OffsetDivisions)
			require.Equal(t, offset, *typed.OffsetDivisions)
		case *pb.SetTriggerRequest:
			require.NotNil(t, typed.LevelVolts)
			require.Equal(t, levelVolts, *typed.LevelVolts)
		default:
			require.FailNowf(t, "unexpected protobuf type", "unexpected protobuf type %T", decoded)
		}
	}
}
