package owonrpc

import (
	"fmt"
	"time"

	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

const (
	// DefaultSubscriptionInterval is used when a subscriber omits its poll interval.
	//
	// Example: a default subscriber receives at most ten poll cycles per second.
	DefaultSubscriptionInterval = 100 * time.Millisecond
	// MinimumSubscriptionInterval limits requested poll frequency; the shared scheduler controls admission.
	//
	// Example: requests below twenty milliseconds are rejected.
	MinimumSubscriptionInterval = 20 * time.Millisecond
	// MaximumSubscriptionWaveformChannels bounds device work per poll.
	//
	// Example: the HDS2202S accepts at most two unique waveform channels.
	MaximumSubscriptionWaveformChannels = 2
	// MaximumSubscriptionCapacity bounds the ordinary event capacity.
	//
	// Example: queue_capacity=1025 is rejected before polling.
	MaximumSubscriptionCapacity = 1024
)

// ValidateSubscribeRequest checks selectors, interval and capacity without mutation, admission or I/O.
// Nil lists are valid, but nil selector elements are not. An omitted interval and zero
// capacity are valid default requests; normalization remains the consumer's responsibility.
//
// Example: duplicate CH1 frequency selectors fail before an active slot is acquired.
func ValidateSubscribeRequest(request *pb.SubscribeRequest) error {
	if request == nil {
		return fmt.Errorf("subscribe request is required: %w", &ErrInvalidInput{Reason: "request is nil"})
	}
	if len(request.WaveformChannels) > MaximumSubscriptionWaveformChannels {
		return fmt.Errorf("subscribe has %d waveform channels, maximum is %d: %w", len(request.WaveformChannels), MaximumSubscriptionWaveformChannels, &ErrInvalidInput{Reason: "too many waveform channels"})
	}
	channels := make(map[pb.Channel]struct{}, len(request.WaveformChannels))
	for _, channel := range request.WaveformChannels {
		if err := owonmodel.ValidateChannel(owonmodel.Channel(channel)); err != nil {
			return &ErrInvalidInput{Reason: "invalid subscription waveform channel", Cause: err}
		}
		if _, duplicate := channels[channel]; duplicate {
			return fmt.Errorf("duplicate waveform channel %s: %w", channel, &ErrInvalidInput{Reason: "waveform channel is duplicated"})
		}
		channels[channel] = struct{}{}
	}
	if err := owonmodel.ValidateMeasurementSelectors(StateRequestFromProto(&pb.GetStateRequest{Measurements: request.Measurements}).Measurements); err != nil {
		return &ErrInvalidInput{Reason: "invalid subscription measurements", Cause: err}
	}
	if request.Interval != nil {
		if err := request.Interval.CheckValid(); err != nil {
			return &ErrInvalidInput{Reason: "interval is not a valid protobuf duration", Cause: err}
		}
		if interval := request.Interval.AsDuration(); interval < MinimumSubscriptionInterval {
			return &ErrInvalidInput{Reason: fmt.Sprintf("interval %s is below minimum %s", interval, MinimumSubscriptionInterval)}
		}
	}

	return ValidateSubscriptionCapacity(request.QueueCapacity)
}

// ValidateSubscriptionCapacity checks the shared request and queue-construction event-count policy.
//
// Example: zero requests the consumer default, while 1025 is rejected without allocating a queue.
func ValidateSubscriptionCapacity(capacity uint32) error {
	if capacity > MaximumSubscriptionCapacity {
		return fmt.Errorf("subscription capacity %d exceeds maximum %d: %w", capacity, MaximumSubscriptionCapacity, &ErrInvalidInput{Reason: "queue capacity exceeds the configured maximum"})
	}

	return nil
}
