package owonrpc

import (
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TriggerPatchFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: an explicit zero LevelVolts value remains present while an omitted slope stays nil.
func TriggerPatchFromProto(value *pb.SetTriggerRequest) *owonmodel.TriggerPatch {
	if value == nil {
		return nil
	}
	result := &owonmodel.TriggerPatch{
		Source:     convertPointer[pb.TriggerSource, owonmodel.TriggerSource](value.Source),
		Coupling:   convertPointer[pb.Coupling, owonmodel.Coupling](value.Coupling),
		Slope:      convertPointer[pb.TriggerSlope, owonmodel.TriggerSlope](value.Slope),
		LevelVolts: clonePointer(value.LevelVolts),
		Sweep:      convertPointer[pb.TriggerSweep, owonmodel.TriggerSweep](value.Sweep),
	}
	return result
}

// TriggerStateToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a falling CH2 edge retains its source, slope, voltage level, and status text.
func TriggerStateToProto(value *owonmodel.TriggerState) *pb.TriggerState {
	if value == nil {
		return nil
	}
	result := &pb.TriggerState{
		Source:   pb.TriggerSource(value.Source),
		Coupling: pb.Coupling(value.Coupling),
		Slope:    pb.TriggerSlope(value.Slope),
		Level:    value.Level,
		Sweep:    pb.TriggerSweep(value.Sweep),
		Status:   value.Status,
	}
	return result
}
