package owonrpc

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// TestWaveformScreenTraceReachesWire requires the display contract to survive RPC serialization.
//
// Example: off-screen points remain signed and the host capture window remains distinct.
func TestWaveformScreenTraceReachesWire(t *testing.T) {
	start := time.Date(2026, 9, 19, 14, 44, 40, 0, time.UTC)
	native := &owonmodel.Waveform{
		Channel: owonmodel.Channel1, Data: []byte{177, 12}, ScreenHeaderJSON: []byte("{}"),
		CaptureStartedAt: start, CapturedAt: start.Add(time.Second),
		ScreenTrace: &owonmodel.ScreenTrace{Profile: "owon-hds2202s-screen", Width: 600, Height: 200, HorizontalDivisions: 12, VerticalDivisions: 8, Y: []int{228, -27}, GroundY: -2147483648},
	}
	wire := WaveformToProto(native)
	encoded, err := (protojson.MarshalOptions{UseProtoNames: true}).Marshal(wire)
	require.NoError(t, err)
	require.Contains(t, string(encoded), `"screen_trace":`)
	require.Contains(t, string(encoded), `"capture_started_at":`)
	require.True(t, proto.Equal(&pb.ScreenTrace{Profile: "owon-hds2202s-screen", Width: 600, Height: 200, HorizontalDivisions: 12, VerticalDivisions: 8, Y: []int32{228, -27}, GroundY: -2147483648}, wire.ScreenTrace))
	require.Equal(t, start, wire.CaptureStartedAt.AsTime())
	require.Equal(t, start.Add(time.Second), wire.CapturedAt.AsTime())
	require.Empty(t, wire.ScreenTraceUnavailableReason)
	native.ScreenTrace.Y[0] = 100
	native.Data[0] = 1
	native.ScreenHeaderJSON[0] = '!'
	require.Equal(t, int32(228), wire.ScreenTrace.Y[0])
	require.Equal(t, []byte{177, 12}, wire.Data)
	require.Equal(t, []byte("{}"), wire.ScreenHeaderJson)
	wire.ScreenTrace.Y[1] = 100
	require.Equal(t, -27, native.ScreenTrace.Y[1])
}

// TestWaveformUnavailableTraceReachesWire preserves raw-only capture explanations.
//
// Example: PEAK remains downloadable without inventing display coordinates.
func TestWaveformUnavailableTraceReachesWire(t *testing.T) {
	wire := WaveformToProto(&owonmodel.Waveform{ScreenTraceUnavailableReason: "PEAK is unproved"})
	require.Nil(t, wire.ScreenTrace)
	require.Equal(t, "PEAK is unproved", wire.ScreenTraceUnavailableReason)
	require.Nil(t, ScreenTraceToProto(nil))
	require.Nil(t, ScreenTraceToProto(&owonmodel.ScreenTrace{}).Y)
	require.NotNil(t, ScreenTraceToProto(&owonmodel.ScreenTrace{Y: []int{}}).Y)
	for _, ground := range []int{-2147483648, 2147483647} {
		require.Equal(t, int32(ground), ScreenTraceToProto(&owonmodel.ScreenTrace{GroundY: ground}).GroundY)
	}
}
