package owonrpc

import (
	"slices"

	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// WaveformRequestFromProto converts wire fields to native values with independent mutable ownership.
//
// Example: a CH2 screen capture becomes Channel2 with Screen set to true.
func WaveformRequestFromProto(value *pb.GetWaveformRequest) *owonmodel.WaveformRequest {
	if value == nil {
		return nil
	}
	result := &owonmodel.WaveformRequest{
		Channel: owonmodel.Channel(value.Channel),
		Screen:  value.Screen,
	}
	return result
}

// WaveformMetadataToProto converts native values to wire fields with independent mutable ownership.
//
// Example: a known zero sample count stays present while an unknown sample count stays nil.
func WaveformMetadataToProto(value *owonmodel.WaveformMetadata) *pb.WaveformMetadata {
	if value == nil {
		return nil
	}
	result := &pb.WaveformMetadata{
		SampleCount:       clonePointer(value.SampleCount),
		SampleRateHz:      value.SampleRateHz,
		SampleEncoding:    value.SampleEncoding,
		XOriginSeconds:    clonePointer(value.XOriginSeconds),
		XIncrementSeconds: clonePointer(value.XIncrementSeconds),
		YOriginVolts:      clonePointer(value.YOriginVolts),
		YIncrementVolts:   clonePointer(value.YIncrementVolts),
		DataLengthBytes:   value.DataLengthBytes,
	}
	return result
}

// WaveformToProto converts native values to wire fields with independent mutable ownership.
//
// Example: raw capture bytes and header bytes are copied independently without adding RPC sequence counters.
func WaveformToProto(value *owonmodel.Waveform) *pb.Waveform {
	if value == nil {
		return nil
	}
	result := &pb.Waveform{
		Channel:          pb.Channel(value.Channel),
		Data:             slices.Clone(value.Data),
		Encoding:         value.Encoding,
		ScreenHeaderJson: slices.Clone(value.ScreenHeaderJSON),
		CapturedAt:       timestamppb.New(value.CapturedAt),
		Metadata:         WaveformMetadataToProto(value.Metadata),
	}
	return result
}
