// Package waveform implements the owonctl waveform command.
//
// Example: `owonctl waveform --channel 1` reads channel one's screen waveform as JSON.
package waveform

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/go-belt"
	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/spf13/cobra"
	"github.com/xaionaro-go/owon/pkg/owonctl"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
)

// commandHandler holds command inputs and shared connection policy.
//
// Example: Cobra populates command values before execution.
type commandHandler struct {
	Config  *owonctl.ClientConfig
	Channel int
}

// NewCommand constructs this independently registered Cobra command.
//
// Example: the executable adds the command to its root.
func NewCommand(config *owonctl.ClientConfig) *cobra.Command {
	handler := &commandHandler{Config: config}
	command := &cobra.Command{Use: "waveform", Short: "Read a waveform as JSON", Args: cobra.NoArgs, RunE: handler.run}
	command.Flags().IntVar(&handler.Channel, "channel", 1, "channel number: 1 or 2")

	return command
}

// run validates inputs, owns the command connection, and writes the result.
//
// Example: invalid requests fail before a connection is constructed.
func (handler *commandHandler) run(
	command *cobra.Command,
	arguments []string,
) (_err error) {
	if handler.Channel != 1 && handler.Channel != 2 {
		return &owonctl.ErrCommandArguments{Command: "waveform", Reason: fmt.Sprintf("channel must be 1 or 2, got %d", handler.Channel)}
	}

	config, err := handler.Config.ConnectionConfig()
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(command.Context(), handler.Config.Timeout)
	defer cancel()
	ctx = belt.WithField(ctx, "command", "waveform")
	logger.Tracef(ctx, "waveform")
	// traceResult reports completion after command-owned cleanup.
	//
	// Example: operation and cleanup errors remain visible at trace level.
	defer func() { logger.Tracef(ctx, "/waveform: %v", _err) }()

	connection, err := owonclient.NewConnection(ctx, config)
	if err != nil {
		return err
	}

	// closeConnection retains independent cleanup failures.
	//
	// Example: an RPC failure cannot hide a connection close failure.
	defer func() { _err = errors.Join(_err, connection.Close()) }()

	logger.Debugf(ctx, "executing waveform")
	response, err := connection.Client().Waveform(ctx, &pb.GetWaveformRequest{Channel: pb.Channel(handler.Channel), Screen: true})
	if err != nil {
		return err
	}

	return owonctl.PrintMessage(command.OutOrStdout(), response)
}
