package owonusb

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"sync/atomic"
	"testing"
	"time"

	"github.com/google/gousb"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owoncontrol"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// TestEndpointZeroProgressRemainsDistinct checks the valid zero-count failure boundary.
//
// Example: zero bytes without an endpoint error remain io.ErrNoProgress, not an invalid-count failure.
func TestEndpointZeroProgressRemainsDistinct(t *testing.T) {
	endpoint := cancellationEndpoint{}
	session, err := newEndpointSession(endpoint, endpoint, 1024)
	require.NoError(t, err)
	session.buffer = []byte("buffered")
	require.ErrorIs(t, session.fill(t.Context()), io.ErrNoProgress)
	require.Equal(t, []byte("buffered"), session.buffer)
	require.Nil(t, session.deferredErr)
	payload := []byte("COMMAND\n")
	require.ErrorIs(t, writeAll(t.Context(), endpoint, payload), io.ErrNoProgress)
	require.Equal(t, []byte("COMMAND\n"), payload)
}

// invalidCountEndpoint returns malformed transfer counts with independent completion errors.
//
// Example: a native cancellation can accompany a count larger than the supplied buffer.
type invalidCountEndpoint struct {
	Count  int
	Cause  error
	Wait   bool
	Calls  atomic.Int32
	Source []byte
}

// ReadContext supplies temporary bytes and returns the configured invalid count and cause.
//
// Example: fill must not append these bytes to an existing buffered response.
func (endpoint *invalidCountEndpoint) ReadContext(
	ctx context.Context,
	destination []byte,
) (int, error) {
	endpoint.Calls.Add(1)
	copy(destination, "unusable")
	if endpoint.Wait {
		<-ctx.Done()
	}
	return endpoint.Count, endpoint.Cause
}

// WriteContext records the attempted payload without accepting any valid prefix.
//
// Example: writeAll must stop after this completion rather than resubmit an advanced slice.
func (endpoint *invalidCountEndpoint) WriteContext(
	ctx context.Context,
	source []byte,
) (int, error) {
	endpoint.Calls.Add(1)
	endpoint.Source = append([]byte(nil), source...)
	if endpoint.Wait {
		<-ctx.Done()
	}
	return endpoint.Count, endpoint.Cause
}

// TestInvalidCountsPreserveAllCauses covers both count guards and the exact normalization domain.
//
// Example: an ended context is added only when native cancellation is among the endpoint causes.
func TestInvalidCountsPreserveAllCauses(t *testing.T) {
	for _, write := range []bool{false, true} {
		for _, count := range []int{-1, endpointReadBytes + 1} {
			t.Run(fmt.Sprintf("write=%t/count=%d", write, count),
				// checkCountCauses covers nil, independent, native and joined completions independently.
				//
				// Example: a nil endpoint error still leaves an invalid-count diagnostic.
				func(t *testing.T) {
					independent := &net.OpError{Op: "transfer", Net: "usb", Err: errors.New("independent endpoint failure")}
					for _, cause := range []error{nil, independent, gousb.TransferCancelled, errors.Join(gousb.TransferCancelled, independent)} {
						for _, ended := range []string{"live", "canceled", "expired"} {
							verifyInvalidCount(t, write, count, cause, independent, ended)
						}
					}
				})
		}
	}
}

// verifyInvalidCount checks one rejected completion without allowing buffer or write advancement.
//
// Example: independent failures survive errors.Is and errors.As even with an invalid byte count.
func verifyInvalidCount(
	t *testing.T,
	write bool,
	count int,
	cause error,
	independent *net.OpError,
	ended string,
) {
	t.Helper()
	ctx, cancel := context.WithCancel(t.Context())
	defer cancel()
	switch ended {
	case "canceled":
		cancel()
	case "expired":
		expired, stop := context.WithDeadline(ctx, time.Unix(0, 0))
		defer stop()
		ctx = expired
	}
	endpoint := &invalidCountEndpoint{Count: count, Cause: cause}
	session, err := newEndpointSession(endpoint, endpoint, 1024)
	require.NoError(t, err)
	session.buffer = []byte("buffered")
	payload := []byte("COMMAND\n")
	if write {
		err = writeAll(ctx, endpoint, payload)
		require.Equal(t, payload, endpoint.Source)
	} else {
		err = session.fill(ctx)
	}
	require.ErrorContains(t, err, fmt.Sprintf("invalid count %d", count), ended)
	require.Equal(t, []byte("buffered"), session.buffer)
	require.Equal(t, []byte("COMMAND\n"), payload)
	require.Nil(t, session.deferredErr)
	require.EqualValues(t, 1, endpoint.Calls.Load())
	if cause != nil {
		require.ErrorIs(t, err, cause, ended)
	}
	var matched *net.OpError
	require.Equal(t, errors.Is(cause, independent), errors.As(err, &matched))
	if matched != nil {
		require.Same(t, independent, matched)
	}
	require.Equal(t, errors.Is(cause, gousb.TransferCancelled), errors.Is(err, gousb.TransferCancelled))
	require.Equal(t, ctx.Err() == context.Canceled && errors.Is(cause, gousb.TransferCancelled), errors.Is(err, context.Canceled))
	require.Equal(t, ctx.Err() == context.DeadlineExceeded && errors.Is(cause, gousb.TransferCancelled), errors.Is(err, context.DeadlineExceeded))
}

// newInvalidCountSession places the controlled failure at exactly one production endpoint boundary.
//
// Example: a write failure cannot reach the healthy reader; a read failure follows one command write.
func newInvalidCountSession(
	t *testing.T,
	endpoint *invalidCountEndpoint,
	write bool,
) *endpointSession {
	t.Helper()
	var reader BulkReader = endpoint
	var writer BulkWriter = new(endpointWriter)
	if write {
		reader = new(endpointReader)
		writer = endpoint
	}
	session, err := newEndpointSession(reader, writer, 1024)
	require.NoError(t, err)
	return session
}

// TestInvalidCountsPoisonWithoutReplay checks rejection through the real endpoint and transaction owners.
//
// Example: the next command in the failed transaction returns the original failure without another transfer.
func TestInvalidCountsPoisonWithoutReplay(t *testing.T) {
	for _, write := range []bool{false, true} {
		for _, count := range []int{-1, endpointReadBytes + 1} {
			t.Run(fmt.Sprintf("write=%t/count=%d", write, count),
				// checkPoison retains all completion variants while forbidding command replay.
				//
				// Example: even nil-cause invalid counts poison their session.
				func(t *testing.T) {
					independent := errors.New("independent endpoint failure")
					for _, cause := range []error{nil, independent, gousb.TransferCancelled, errors.Join(gousb.TransferCancelled, independent)} {
						verifyInvalidCountPoison(t, write, count, cause)
					}
				})
		}
	}
}

// verifyInvalidCountPoison exercises a complete exchange with native resources replaced only at the endpoints.
//
// Example: production Backend forwards the endpoint error; Session keeps it for subsequent commands.
func verifyInvalidCountPoison(
	t *testing.T,
	write bool,
	count int,
	cause error,
) {
	t.Helper()
	endpoint := &invalidCountEndpoint{Count: count, Cause: cause}
	backend := &Backend{resources: &usbResources{session: newInvalidCountSession(t, endpoint, write)}}
	deviceSession, err := owonsession.New(backend, owonsession.Config{ExpectedSerial: "serial"})
	require.NoError(t, err)
	t.Cleanup(
		// closeInvalidCountSession releases the resource owner after transaction cleanup.
		//
		// Example: no physical USB resource is acquired by this fixture.
		func() { require.NoError(t, deviceSession.Close()) })
	transaction, err := deviceSession.Begin(t.Context())
	require.NoError(t, err)
	defer transaction.Close()
	_, err = transaction.Execute(t.Context(), owonprotocol.Command{Text: "*IDN?", ResponseMode: owonprotocol.ResponseModeASCII})
	require.ErrorContains(t, err, "invalid count")
	if cause != nil {
		require.ErrorIs(t, err, cause)
	}
	_, nextErr := transaction.Execute(t.Context(), owonprotocol.Command{Text: "*IDN?", ResponseMode: owonprotocol.ResponseModeASCII})
	require.ErrorIs(t, nextErr, err)
	require.EqualValues(t, 1, endpoint.Calls.Load())
	require.Empty(t, backend.resources.session.buffer)
	transaction.Close()
	_, recoveryErr := deviceSession.Begin(t.Context())
	require.ErrorContains(t, recoveryErr, "recover poisoned session")
	require.EqualValues(t, 1, endpoint.Calls.Load(), "poisoned session must not accept another transfer")
}

// TestInvalidCountsThroughTCP checks public stream classification without faking RPC or framing.
//
// Example: a malformed count plus native deadline preserves DEVICE_UNAVAILABLE and DeadlineExceeded.
func TestInvalidCountsThroughTCP(t *testing.T) {
	for _, write := range []bool{false, true} {
		for _, count := range []int{-1, endpointReadBytes + 1} {
			t.Run(fmt.Sprintf("write=%t/count=%d", write, count),
				// checkPublicClassification compares ordinary endpoint failure and operation deadline.
				//
				// Example: live read-count failures are protocol errors, not invented cancellations.
				func(t *testing.T) {
					for _, expired := range []bool{false, true} {
						verifyInvalidCountTCP(t, write, count, expired)
					}
				})
		}
	}
}

// verifyInvalidCountTCP traverses TCP, generated service, controller, session and endpoint guards.
//
// Example: an independent endpoint diagnostic remains visible alongside the invalid-count message.
func verifyInvalidCountTCP(
	t *testing.T,
	write bool,
	count int,
	expired bool,
) {
	t.Helper()
	independent := errors.New("independent endpoint failure")
	endpoint := &invalidCountEndpoint{Count: count, Cause: errors.Join(gousb.TransferCancelled, independent), Wait: expired}
	backend := &Backend{resources: &usbResources{session: newInvalidCountSession(t, endpoint, write)}}
	deviceSession, err := owonsession.New(backend, owonsession.Config{ExpectedSerial: "serial", OperationTimeout: 20 * time.Millisecond})
	require.NoError(t, err)
	t.Cleanup(
		// closeRPCSession runs after client/server cleanup and all handlers have joined.
		//
		// Example: the test cannot leave an admitted exchange behind.
		func() { require.NoError(t, deviceSession.Close()) })
	instrument, err := owoncontrol.New(deviceSession, owonmodel.DeviceIdentity{})
	require.NoError(t, err)
	client := newSubscribeTCPClient(t, requireNewServer(t, instrument))
	ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancel()
	stream, err := client.Subscribe(ctx, &pb.SubscribeRequest{})
	require.NoError(t, err)
	event, err := stream.Recv()
	require.NoError(t, err)
	require.Contains(t, event.GetError().GetMessage(), "invalid count")
	require.Contains(t, event.GetError().GetMessage(), independent.Error())
	wantCode := codes.Unavailable
	wantCategory := pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE
	switch {
	case expired:
		wantCode = codes.DeadlineExceeded
	case !write:
		wantCode = codes.DataLoss
		wantCategory = pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL
	}
	require.Equal(t, wantCategory, event.GetError().GetCategory())
	require.True(t, event.GetError().GetRetryable())
	_, err = stream.Recv()
	require.Equal(t, wantCode, status.Code(err))
	require.Contains(t, err.Error(), independent.Error())
	require.NoError(t, ctx.Err(), "outer watchdog must not end the stream")
	require.EqualValues(t, 1, endpoint.Calls.Load())
	t.Logf("write=%t count=%d expired=%t: service=%s terminal=%s attempts=1", write, count, expired, wantCategory, wantCode)
}
