// Package dmm implements the owonctl dmm command.
//
// Example: `owonctl dmm` reads the current multimeter measurement without changing its configuration.
package dmm

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"github.com/facebookincubator/go-belt"
	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/spf13/cobra"
	"github.com/xaionaro-go/owon/pkg/owonctl"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
)

const (
	// description summarizes the dmm command in the top-level catalog.
	//
	// Example: top-level help renders `dmm  read the digital-multimeter measurement as JSON`.
	description = "read the digital-multimeter measurement as JSON"

	// functionFlagDescription documents the DMM functions accepted by the CLI.
	//
	// Example: `--function capacitance` selects the capacitance measurement.
	functionFlagDescription = "voltage, current, resistance, capacitance, diode, or continuity"

	// currentTypeFlagDescription documents the AC/DC qualifier for voltage and current.
	//
	// Example: `--current-type dc` selects DC voltage or current.
	currentTypeFlagDescription = "AC or DC; required with voltage and current"

	// rangeFlagDescription documents the range tokens verified by the device protocol.
	//
	// Example: `--range V` selects the verified volt range token.
	rangeFlagDescription = "device range token: ON, mV, or V"

	// autoRangeFlagDescription documents the supported automatic-range mutation.
	//
	// Example: `--auto-range` enables automatic DMM range selection.
	autoRangeFlagDescription = "enable automatic range; only true is supported"

	// relativeFlagDescription documents presence-aware relative-mode selection.
	//
	// Example: `--relative=false` explicitly disables relative mode.
	relativeFlagDescription = "set relative mode; use --relative=false to disable"
)

// commandHandler holds command inputs and shared connection policy.
//
// Example: Cobra populates command values before execution.
type commandHandler struct {
	Config  *owonctl.ClientConfig
	Options dmmOptions
}

// NewCommand constructs this independently registered Cobra command.
//
// Example: the executable adds the command to its root.
func NewCommand(config *owonctl.ClientConfig) *cobra.Command {
	handler := &commandHandler{Config: config}
	command := &cobra.Command{Use: "dmm", Short: description, Args: cobra.NoArgs, RunE: handler.run}
	flags := command.Flags()
	flags.StringVar(&handler.Options.Function, "function", "", functionFlagDescription)
	flags.StringVar(&handler.Options.CurrentType, "current-type", "", currentTypeFlagDescription)
	flags.BoolVar(&handler.Options.Relative, "relative", false, relativeFlagDescription)
	flags.StringVar(&handler.Options.RangeValue, "range", "", rangeFlagDescription)
	flags.BoolVar(&handler.Options.AutoRange, "auto-range", false, autoRangeFlagDescription)

	return command
}

// run validates inputs, owns the command connection, and writes the result.
//
// Example: invalid requests fail before a connection is constructed.
func (handler *commandHandler) run(
	command *cobra.Command,
	arguments []string,
) (_err error) {
	flags := command.Flags()
	request, err := buildDMMRequest(handler.Options, dmmFlagPresence{Function: flags.Changed("function"), CurrentType: flags.Changed("current-type"), Relative: flags.Changed("relative"), RangeValue: flags.Changed("range"), AutoRange: flags.Changed("auto-range")})
	if err != nil {
		return err
	}
	if request != nil {
		if _, err := owonscpi.CompileDMM(owonrpc.DMMPatchFromProto(request)); err != nil {
			return fmt.Errorf("prepare dmm: %w", err)
		}
	}

	config, err := handler.Config.ConnectionConfig()
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(command.Context(), handler.Config.Timeout)
	defer cancel()
	ctx = belt.WithField(ctx, "command", "dmm")
	logger.Tracef(ctx, "dmm")
	// traceResult reports completion after command-owned cleanup.
	//
	// Example: operation and cleanup errors remain visible at trace level.
	defer func() { logger.Tracef(ctx, "/dmm: %v", _err) }()

	connection, err := owonclient.NewConnection(ctx, config)
	if err != nil {
		return err
	}

	// closeConnection retains independent cleanup failures.
	//
	// Example: an RPC failure cannot hide a connection close failure.
	defer func() { _err = errors.Join(_err, connection.Close()) }()

	logger.Debugf(ctx, "executing dmm")
	if request != nil {
		if _, err := connection.Client().SetDMM(ctx, request); err != nil {
			return err
		}
	}
	response, err := connection.Client().DMMMeasurement(ctx)
	if err != nil {
		return err
	}

	return owonctl.PrintMessage(command.OutOrStdout(), response)
}

// dmmOptions contains raw values parsed from one dmm command invocation.
//
// Example: buildDMMRequest converts these values into a typed SetDmmRequest.
type dmmOptions struct {
	Function    string
	CurrentType string
	Relative    bool
	RangeValue  string
	AutoRange   bool
}

// dmmFlagPresence records which optional DMM flags the caller supplied.
//
// Example: an omitted relative flag remains nil in the outgoing patch.
type dmmFlagPresence struct {
	Function    bool
	CurrentType bool
	Relative    bool
	RangeValue  bool
	AutoRange   bool
}

// any reports whether the command contains a DMM mutation.
//
// Example: a plain `dmm` read returns false and skips SetDMM.
func (presence dmmFlagPresence) any() bool {
	return presence.Function || presence.CurrentType || presence.Relative || presence.RangeValue || presence.AutoRange
}

// buildDMMRequest converts parsed CLI values into a presence-aware DMM patch.
//
// Example: selecting capacitance returns a patch with only Function populated.
func buildDMMRequest(
	options dmmOptions,
	presence dmmFlagPresence,
) (*pb.SetDmmRequest, error) {
	if !presence.any() {
		return nil, nil
	}
	request := new(pb.SetDmmRequest)
	if presence.Function {
		function, err := parseDMMFunction(options.Function)
		if err != nil {
			return nil, err
		}
		request.Function = &function
	}
	if presence.CurrentType {
		currentType, err := parseDMMCurrentType(options.CurrentType)
		if err != nil {
			return nil, err
		}
		request.CurrentType = &currentType
	}
	if presence.Relative {
		request.Relative = &options.Relative
	}
	if presence.RangeValue {
		var rangeValue pb.DmmRange
		switch strings.ToUpper(strings.TrimSpace(options.RangeValue)) {
		case "ON":
			rangeValue = pb.DmmRange_DMM_RANGE_ON
		case "MV":
			rangeValue = pb.DmmRange_DMM_RANGE_MV
		case "V":
			rangeValue = pb.DmmRange_DMM_RANGE_V
		default:
			return nil, &owonctl.ErrCommandArguments{Command: "dmm", Reason: fmt.Sprintf("unsupported range %q; want ON, mV, or V", options.RangeValue)}
		}
		request.Range = &rangeValue
	}
	if presence.AutoRange {
		request.AutoRange = &options.AutoRange
	}

	return request, nil
}

// parseDMMFunction converts one CLI function spelling to the protobuf enum.
//
// Example: `capacitance` maps to DMM_FUNCTION_CAPACITANCE.
func parseDMMFunction(value string) (pb.DmmFunction, error) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "voltage":
		return pb.DmmFunction_DMM_FUNCTION_VOLTAGE, nil
	case "current":
		return pb.DmmFunction_DMM_FUNCTION_CURRENT, nil
	case "resistance":
		return pb.DmmFunction_DMM_FUNCTION_RESISTANCE, nil
	case "capacitance":
		return pb.DmmFunction_DMM_FUNCTION_CAPACITANCE, nil
	case "diode":
		return pb.DmmFunction_DMM_FUNCTION_DIODE, nil
	case "continuity":
		return pb.DmmFunction_DMM_FUNCTION_CONTINUITY, nil
	default:
		return pb.DmmFunction_DMM_FUNCTION_UNSPECIFIED, &owonctl.ErrCommandArguments{
			Command: "dmm",
			Reason:  fmt.Sprintf("unsupported function %q; want voltage, current, resistance, capacitance, diode, or continuity", value),
		}
	}
}

// parseDMMCurrentType converts one CLI current-type spelling to the protobuf enum.
//
// Example: `dc` maps to DMM_CURRENT_TYPE_DC.
func parseDMMCurrentType(value string) (pb.DmmCurrentType, error) {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "ac":
		return pb.DmmCurrentType_DMM_CURRENT_TYPE_AC, nil
	case "dc":
		return pb.DmmCurrentType_DMM_CURRENT_TYPE_DC, nil
	default:
		return pb.DmmCurrentType_DMM_CURRENT_TYPE_UNSPECIFIED, &owonctl.ErrCommandArguments{
			Command: "dmm",
			Reason:  fmt.Sprintf("unsupported current type %q; want ac or dc", value),
		}
	}
}
