package dmm

import (
	"bytes"
	"io"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonctl"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestParseDMMFunctionAcceptsSupportedFunctions verifies every documented DMM mode.
//
// Example: capacitance is accepted as a typed function selection.
func TestParseDMMFunctionAcceptsSupportedFunctions(t *testing.T) {
	t.Parallel()

	tests := []struct {
		Name  string
		Value string
		Want  pb.DmmFunction
	}{
		{Name: "voltage", Value: "voltage", Want: pb.DmmFunction_DMM_FUNCTION_VOLTAGE},
		{Name: "current", Value: "current", Want: pb.DmmFunction_DMM_FUNCTION_CURRENT},
		{Name: "resistance", Value: "resistance", Want: pb.DmmFunction_DMM_FUNCTION_RESISTANCE},
		{Name: "capacitance", Value: "capacitance", Want: pb.DmmFunction_DMM_FUNCTION_CAPACITANCE},
		{Name: "diode", Value: "diode", Want: pb.DmmFunction_DMM_FUNCTION_DIODE},
		{Name: "continuity", Value: "continuity", Want: pb.DmmFunction_DMM_FUNCTION_CONTINUITY},
	}
	for _, test := range tests {
		t.Run(test.Name,
			// verifyDMMFunctionCase checks one documented DMM function spelling.
			//
			// Example: the capacitance spelling maps to the protobuf enum.
			func(t *testing.T) {
				got, err := parseDMMFunction(test.Value)
				require.NoError(t, err)
				require.Equal(t, test.Want, got)
			})
	}
}

// TestParseDMMFunctionRejectsUnknownFunctions verifies invalid mode names fail locally.
//
// Example: a misspelled capacitance mode returns a typed command argument error.
func TestParseDMMFunctionRejectsUnknownFunctions(t *testing.T) {
	t.Parallel()

	_, err := parseDMMFunction("capacitence")
	var arguments *owonctl.ErrCommandArguments
	require.ErrorAs(t, err, &arguments)
}

// TestParseDMMCurrentTypeAcceptsAcAndDc verifies both current qualifiers.
//
// Example: `dc` is accepted for a voltage or current selection.
func TestParseDMMCurrentTypeAcceptsAcAndDc(t *testing.T) {
	t.Parallel()

	ac, err := parseDMMCurrentType("AC")
	require.NoError(t, err)
	require.Equal(t, pb.DmmCurrentType_DMM_CURRENT_TYPE_AC, ac)
	dc, err := parseDMMCurrentType("dc")
	require.NoError(t, err)
	require.Equal(t, pb.DmmCurrentType_DMM_CURRENT_TYPE_DC, dc)
}

// TestParseDMMCurrentTypeRejectsUnknownTypes verifies invalid qualifiers fail locally.
//
// Example: a typo in `current-type` returns a typed command argument error.
func TestParseDMMCurrentTypeRejectsUnknownTypes(t *testing.T) {
	t.Parallel()

	_, err := parseDMMCurrentType("alternating")
	var arguments *owonctl.ErrCommandArguments
	require.ErrorAs(t, err, &arguments)
}

// TestBuildDMMRequestPreservesExplicitCapacitanceSelection verifies presence-aware patching.
//
// Example: selecting capacitance does not accidentally overwrite relative or range settings.
func TestBuildDMMRequestPreservesExplicitCapacitanceSelection(t *testing.T) {
	t.Parallel()

	request, err := buildDMMRequest(dmmOptions{Function: "capacitance"}, dmmFlagPresence{Function: true})
	require.NoError(t, err)
	require.NotNil(t, request)
	require.Equal(t, pb.DmmFunction_DMM_FUNCTION_CAPACITANCE, *request.Function)
	require.Nil(t, request.CurrentType)
	require.Nil(t, request.Relative)
	require.Nil(t, request.Range)
	require.Nil(t, request.AutoRange)
}

// TestBuildDMMRequestReturnsNilWithoutConfigurationFlags verifies a plain read is non-mutating.
//
// Example: `owonctl dmm` reads the current device mode without a SetDmm RPC.
func TestBuildDMMRequestReturnsNilWithoutConfigurationFlags(t *testing.T) {
	t.Parallel()

	request, err := buildDMMRequest(dmmOptions{}, dmmFlagPresence{})
	require.NoError(t, err)
	require.Nil(t, request)
}

// TestBuildDMMRequestPreservesExplicitBooleanValues verifies false is not confused with omission.
//
// Example: `-relative=false` produces a present false pointer in the typed patch.
func TestBuildDMMRequestPreservesExplicitBooleanValues(t *testing.T) {
	t.Parallel()

	request, err := buildDMMRequest(
		dmmOptions{Relative: false, AutoRange: true},
		dmmFlagPresence{Relative: true, AutoRange: true},
	)
	require.NoError(t, err)
	require.NotNil(t, request.Relative)
	require.False(t, *request.Relative)
	require.NotNil(t, request.AutoRange)
	require.True(t, *request.AutoRange)
}

// TestCommandHelpDocumentsDMMModes verifies help is complete without a daemon connection.
//
// Example: `owonctl dmm --help` names capacitance and the other supported modes.
func TestCommandHelpDocumentsDMMModes(t *testing.T) {
	t.Parallel()

	var output bytes.Buffer
	command := NewCommand(nil)
	command.SetOut(&output)
	command.SetArgs([]string{"--help"})
	err := command.ExecuteContext(t.Context())
	require.NoError(t, err)
	require.Contains(t, output.String(), "capacitance")
	require.Contains(t, output.String(), "current-type")
}

// TestCommandRejectsInvalidDMMFunctionBeforeClientUse verifies lexical validation precedes RPC setup.
//
// Example: an invalid function is rejected even when no client is available.
func TestCommandRejectsInvalidDMMFunctionBeforeClientUse(t *testing.T) {
	t.Parallel()

	command := NewCommand(nil)
	command.SetOut(io.Discard)
	command.SetArgs([]string{"--function", "capacitence"})
	err := command.ExecuteContext(t.Context())
	var arguments *owonctl.ErrCommandArguments
	require.ErrorAs(t, err, &arguments)
}

// TestCommandAcceptsSupportedDMMPatches checks friendly spellings retain typed range presence.
//
// Example: mV becomes DMM_RANGE_MV without inventing an automatic-range setting.
func TestCommandAcceptsSupportedDMMPatches(t *testing.T) {
	for _, test := range []struct {
		Token string
		Range pb.DmmRange
	}{
		{Token: "ON", Range: pb.DmmRange_DMM_RANGE_ON},
		{Token: " mV ", Range: pb.DmmRange_DMM_RANGE_MV},
		{Token: "v", Range: pb.DmmRange_DMM_RANGE_V},
	} {
		request, err := buildDMMRequest(dmmOptions{RangeValue: test.Token}, dmmFlagPresence{RangeValue: true})
		require.NoError(t, err)
		require.NotNil(t, request.Range)
		require.Equal(t, test.Range, *request.Range)
		require.Nil(t, request.AutoRange)
	}
	for _, function := range []string{"voltage", "current"} {
		for _, currentType := range []string{"ac", "dc"} {
			prepared, err := buildDMMRequest(dmmOptions{Function: function, CurrentType: currentType, Relative: false, AutoRange: true}, dmmFlagPresence{Function: true, CurrentType: true, Relative: true, AutoRange: true})
			require.NoError(t, err)
			require.NotNil(t, prepared)
		}
	}
}
