package owonclient

import (
	"context"
	"fmt"
	"reflect"

	"github.com/facebookincubator/go-belt/tool/logger"

	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Client is the reusable typed Go client for an OWON gRPC service.
//
// Example: construct it from a grpc.ClientConn and call DeviceInfo.
type Client struct {
	rpc pb.OwonServiceClient
}

// NewClient constructs a typed client over an existing gRPC connection.
//
// Example: callers retain ownership of the connection and close it during shutdown.
func NewClient(connection grpc.ClientConnInterface) (*Client, error) {
	if connection == nil || isNilClientConnection(connection) {
		return nil, &ErrInvalidConfig{Reason: "create OWON client: gRPC connection is nil"}
	}

	return &Client{rpc: pb.NewOwonServiceClient(connection)}, nil
}

// isNilClientConnection detects a typed nil connection interface before client construction.
//
// Example: a nil *grpc.ClientConn cannot be retained as an unusable generated client.
func isNilClientConnection(connection grpc.ClientConnInterface) bool {
	value := reflect.ValueOf(connection)
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}

// serviceClient returns the configured generated client or a deterministic local error.
//
// Example: every public method uses it so nil clients and nil contexts cannot panic.
func (client *Client) serviceClient(ctx context.Context) (pb.OwonServiceClient, error) {
	if client == nil || client.rpc == nil {
		return nil, &ErrUnavailable{Operation: "use OWON gRPC client", Resource: "client", Reason: "is unavailable"}
	}
	if ctx == nil {
		return nil, &ErrInvalidInput{Reason: "use OWON gRPC client: context is nil"}
	}

	return client.rpc, nil
}

// DeviceInfo returns the daemon's currently connected instrument identity.
//
// Example: a caller can compare DeviceInfo.Serial against its configured instrument.
func (client *Client) DeviceInfo(ctx context.Context) (_result *pb.DeviceInfo, _err error) {
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "DeviceInfo")
	defer
	// traceDeviceInfo reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/DeviceInfo: %v", _err) }()
	info, err := service.GetDeviceInfo(ctx, new(emptypb.Empty))
	if err != nil {
		return nil, fmt.Errorf("get OWON device info: %w", err)
	}

	return info, nil
}

// Execute performs one explicitly framed raw SCPI command.
//
// Example: advanced callers can execute a newly documented query using ASCII framing.
func (client *Client) Execute(
	ctx context.Context,
	request *pb.ExecuteRequest,
) (_result []byte, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "execute request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "Execute")
	defer
	// traceExecute reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/Execute: %v", _err) }()
	response, err := service.Execute(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("execute OWON command: %w", err)
	}

	return response.Data, nil
}

// State returns one requested instrument snapshot.
//
// Example: measurement collectors use one request per sampling interval.
func (client *Client) State(
	ctx context.Context,
	request *pb.GetStateRequest,
) (_result *pb.StateSnapshot, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "state request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "State")
	defer
	// traceState reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/State: %v", _err) }()
	state, err := service.GetState(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("get OWON state: %w", err)
	}

	return state, nil
}

// SetChannel applies a channel patch through the service.
//
// Example: callers use optional fields to preserve explicit false and zero values.
func (client *Client) SetChannel(
	ctx context.Context,
	request *pb.SetChannelRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set channel request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetChannel")
	defer
	// traceSetChannel reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetChannel: %v", _err) }()
	result, err := service.SetChannel(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON channel: %w", err)
	}

	return result, nil
}

// SetAcquisition applies an acquisition patch through the service.
//
// Example: callers can switch sampling mode without changing unrelated controls.
func (client *Client) SetAcquisition(
	ctx context.Context,
	request *pb.SetAcquisitionRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set acquisition request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetAcquisition")
	defer
	// traceSetAcquisition reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetAcquisition: %v", _err) }()
	result, err := service.SetAcquisition(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON acquisition: %w", err)
	}

	return result, nil
}

// SetHorizontal applies a horizontal patch through the service.
//
// Example: scale precedes offset in one serialized patch; a transport failure can leave partial device changes.
func (client *Client) SetHorizontal(
	ctx context.Context,
	request *pb.SetHorizontalRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set horizontal request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetHorizontal")
	defer
	// traceSetHorizontal reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetHorizontal: %v", _err) }()
	result, err := service.SetHorizontal(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON horizontal controls: %w", err)
	}

	return result, nil
}

// SetTrigger applies a trigger patch through the service.
//
// Example: source and level can be updated in one ordered device transaction sequence.
func (client *Client) SetTrigger(
	ctx context.Context,
	request *pb.SetTriggerRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set trigger request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetTrigger")
	defer
	// traceSetTrigger reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetTrigger: %v", _err) }()
	result, err := service.SetTrigger(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON trigger: %w", err)
	}

	return result, nil
}

// SetMeasurement applies measurement display configuration through the service.
//
// Example: replace_visible distinguishes replacement from omission.
func (client *Client) SetMeasurement(
	ctx context.Context,
	request *pb.SetMeasurementRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set measurement request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetMeasurement")
	defer
	// traceSetMeasurement reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetMeasurement: %v", _err) }()
	result, err := service.SetMeasurement(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON measurement display: %w", err)
	}

	return result, nil
}

// SetGenerator applies a waveform-generator patch through the service.
//
// Example: output=false disables generation while preserving other omitted fields.
func (client *Client) SetGenerator(
	ctx context.Context,
	request *pb.SetGeneratorRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set generator request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetGenerator")
	defer
	// traceSetGenerator reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetGenerator: %v", _err) }()
	result, err := service.SetGenerator(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON generator: %w", err)
	}

	return result, nil
}

// SetDMM applies a multimeter patch through the service.
//
// Example: function and auto-range can be selected together.
func (client *Client) SetDMM(
	ctx context.Context,
	request *pb.SetDmmRequest,
) (_result *pb.CommandResult, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "set DMM request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "SetDMM")
	defer
	// traceSetDMM reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/SetDMM: %v", _err) }()
	result, err := service.SetDmm(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("set OWON DMM: %w", err)
	}

	return result, nil
}

// DMMMeasurement returns the current DMM reading.
//
// Example: metrics exporters use Value and retain Raw for diagnostics.
func (client *Client) DMMMeasurement(ctx context.Context) (_result *pb.DmmMeasurement, _err error) {
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "DMMMeasurement")
	defer
	// traceDMMMeasurement reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/DMMMeasurement: %v", _err) }()
	measurement, err := service.GetDmmMeasurement(ctx, new(emptypb.Empty))
	if err != nil {
		return nil, fmt.Errorf("get OWON DMM measurement: %w", err)
	}

	return measurement, nil
}

// Run starts continuous acquisition through the service.
//
// Example: automation resumes the scope before subscribing to measurements.
func (client *Client) Run(ctx context.Context) (_result *pb.CommandResult, _err error) {
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "Run")
	defer
	// traceRun reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/Run: %v", _err) }()
	result, err := service.Run(ctx, new(emptypb.Empty))
	if err != nil {
		return nil, fmt.Errorf("run OWON acquisition: %w", err)
	}

	return result, nil
}

// Stop stops acquisition through the service.
//
// Example: maintenance automation stops capture before changing probes.
func (client *Client) Stop(ctx context.Context) (_result *pb.CommandResult, _err error) {
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "Stop")
	defer
	// traceStop reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/Stop: %v", _err) }()
	result, err := service.Stop(ctx, new(emptypb.Empty))
	if err != nil {
		return nil, fmt.Errorf("stop OWON acquisition: %w", err)
	}

	return result, nil
}

// Single arms one acquisition through the service.
//
// Example: a client waits for a configured single trigger.
func (client *Client) Single(ctx context.Context) (_result *pb.CommandResult, _err error) {
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "Single")
	defer
	// traceSingle reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/Single: %v", _err) }()
	result, err := service.Single(ctx, new(emptypb.Empty))
	if err != nil {
		return nil, fmt.Errorf("single OWON acquisition: %w", err)
	}

	return result, nil
}

// Waveform returns raw waveform bytes and verified metadata.
//
// Example: clients archive Data unchanged until sample encoding is confirmed.
func (client *Client) Waveform(
	ctx context.Context,
	request *pb.GetWaveformRequest,
) (_result *pb.Waveform, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "waveform request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "Waveform")
	defer
	// traceWaveform reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/Waveform: %v", _err) }()
	waveform, err := service.GetWaveform(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("get OWON waveform: %w", err)
	}

	return waveform, nil
}

// Subscribe opens a server stream of state, waveform, gap, and error events.
//
// Example: callers receive until their context is canceled.
func (client *Client) Subscribe(
	ctx context.Context,
	request *pb.SubscribeRequest,
) (_result pb.OwonService_SubscribeClient, _err error) {
	if request == nil {
		return nil, &ErrInvalidInput{Reason: "subscribe request is nil"}
	}
	service, serviceErr := client.serviceClient(ctx)
	if serviceErr != nil {
		return nil, serviceErr
	}
	logger.Tracef(ctx, "Subscribe")
	defer
	// traceSubscribe reports the operation result without retaining its request context.
	//
	// Example: a transport failure remains visible in the exit trace.
	func() { logger.Tracef(ctx, "/Subscribe: %v", _err) }()
	stream, err := service.Subscribe(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("subscribe to OWON events: %w", err)
	}

	return stream, nil
}

// ErrInvalidInput identifies invalid RPC client input.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrInvalidInput struct {
	Reason string
	Cause  error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrInvalidInput) Error() string {
	if err == nil {
		return "invalid RPC client input"
	}
	detail := err.Reason
	if detail == "" {
		detail = "invalid RPC client input"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrInvalidInput) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}

// ErrInvalidConfig identifies invalid RPC client configuration.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrInvalidConfig struct {
	Reason string
	Cause  error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrInvalidConfig) Error() string {
	if err == nil {
		return "invalid RPC client configuration"
	}
	detail := err.Reason
	if detail == "" {
		detail = "invalid RPC client configuration"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrInvalidConfig) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}

// ErrUnavailable identifies RPC client unavailable.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrUnavailable struct {
	Operation string
	Resource  string
	Reason    string
	Cause     error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrUnavailable) Error() string {
	if err == nil {
		return "RPC client unavailable"
	}
	detail := err.Reason
	if err.Operation != "" || err.Resource != "" {
		detail = fmt.Sprintf("%s: %s %s", err.Operation, err.Resource, detail)
	}
	if detail == "" {
		detail = "RPC client unavailable"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrUnavailable) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}
