package owonclient

import (
	"context"
	"errors"
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc"
)

// failedClientConnection models one transport failure shared by unary and streaming calls.
//
// Example: connection loss must remain inspectable beneath each public client's operation context.
type failedClientConnection struct{ Cause error }

// Invoke rejects a unary call before any response can be decoded.
//
// Example: the client must return the original transport failure rather than a success-shaped result.
func (connection failedClientConnection) Invoke(
	_ context.Context,
	_ string,
	_ any,
	_ any,
	_ ...grpc.CallOption,
) error {
	return connection.Cause
}

// NewStream rejects stream creation with the same connection failure as unary calls.
//
// Example: Subscribe preserves errors.Is compatibility with the transport cause.
func (connection failedClientConnection) NewStream(
	_ context.Context,
	_ *grpc.StreamDesc,
	_ string,
	_ ...grpc.CallOption,
) (grpc.ClientStream, error) {
	return nil, connection.Cause
}

// requireRPCFailure checks a typed call's failure has no successful response and preserves its cause.
//
// Example: a failed SetDmm does not return an application timestamp.
func requireRPCFailure[Request any, Response any](
	t *testing.T,
	call func(
		context.Context,
		*Request,
	) (Response, error),
	cause error,
) {
	t.Helper()
	response, err := call(t.Context(), new(Request))
	require.ErrorIs(t, err, cause)
	require.Nil(t, response)
}

// TestClientPreservesTransportFailures verifies error chains for every reusable client operation.
//
// Example: a connection failure remains the cause under both the DMM and waveform operation labels.
func TestClientPreservesTransportFailures(t *testing.T) {
	t.Parallel()
	cause := errors.New("connection lost")
	client, err := NewClient(failedClientConnection{Cause: cause})
	require.NoError(t, err)
	requireRPCFailure(t, client.Execute, cause)
	requireRPCFailure(t, client.State, cause)
	requireRPCFailure(t, client.SetChannel, cause)
	requireRPCFailure(t, client.SetAcquisition, cause)
	requireRPCFailure(t, client.SetHorizontal, cause)
	requireRPCFailure(t, client.SetTrigger, cause)
	requireRPCFailure(t, client.SetMeasurement, cause)
	requireRPCFailure(t, client.SetGenerator, cause)
	requireRPCFailure(t, client.SetDMM, cause)
	requireRPCFailure(t, client.Waveform, cause)
	requireRPCFailure(t, client.Subscribe, cause)
	for _, call := range []func(context.Context) (*pb.CommandResult, error){client.Run, client.Stop, client.Single} {
		result, err := call(t.Context())
		require.Nil(t, result)
		require.ErrorIs(t, err, cause)
	}
	info, err := client.DeviceInfo(t.Context())
	require.Nil(t, info)
	require.ErrorIs(t, err, cause)
	reading, err := client.DMMMeasurement(t.Context())
	require.Nil(t, reading)
	require.ErrorIs(t, err, cause)
}
