package owonclient

import (
	"errors"
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestNilContextIsInvalidInput distinguishes a caller error from client availability.
//
// Example: a constructed client rejects a nil context before invoking its connection.
func TestNilContextIsInvalidInput(t *testing.T) {
	client := &Client{rpc: pb.NewOwonServiceClient(nil)}
	_, err := client.DeviceInfo(nil)
	require.ErrorAs(t, err, new(*ErrInvalidInput))
	require.NotErrorAs(t, err, new(*ErrUnavailable))
}

// TestClientErrorCauses preserves the original failure for every local classification.
//
// Example: wrapping a connection setup failure preserves errors.Is and diagnostic text.
func TestClientErrorCauses(t *testing.T) {
	cause := errors.New("connection cause")
	for _, err := range []error{
		&ErrInvalidConfig{Reason: "configure", Cause: cause},
		&ErrInvalidInput{Reason: "input", Cause: cause},
		&ErrUnavailable{Operation: "call", Resource: "client", Reason: "closed", Cause: cause},
	} {
		require.ErrorIs(t, err, cause)
		require.Contains(t, err.Error(), cause.Error())
	}
}
