// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.27.3
// source: pkg/owonrpc/owon.proto

package autogenerated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OwonService_GetDeviceInfo_FullMethodName     = "/xaionaro.owon.OwonService/GetDeviceInfo"
	OwonService_GetState_FullMethodName          = "/xaionaro.owon.OwonService/GetState"
	OwonService_Execute_FullMethodName           = "/xaionaro.owon.OwonService/Execute"
	OwonService_SetChannel_FullMethodName        = "/xaionaro.owon.OwonService/SetChannel"
	OwonService_SetAcquisition_FullMethodName    = "/xaionaro.owon.OwonService/SetAcquisition"
	OwonService_SetHorizontal_FullMethodName     = "/xaionaro.owon.OwonService/SetHorizontal"
	OwonService_SetTrigger_FullMethodName        = "/xaionaro.owon.OwonService/SetTrigger"
	OwonService_SetMeasurement_FullMethodName    = "/xaionaro.owon.OwonService/SetMeasurement"
	OwonService_SetGenerator_FullMethodName      = "/xaionaro.owon.OwonService/SetGenerator"
	OwonService_SetDmm_FullMethodName            = "/xaionaro.owon.OwonService/SetDmm"
	OwonService_GetDmmMeasurement_FullMethodName = "/xaionaro.owon.OwonService/GetDmmMeasurement"
	OwonService_Run_FullMethodName               = "/xaionaro.owon.OwonService/Run"
	OwonService_Stop_FullMethodName              = "/xaionaro.owon.OwonService/Stop"
	OwonService_Single_FullMethodName            = "/xaionaro.owon.OwonService/Single"
	OwonService_GetWaveform_FullMethodName       = "/xaionaro.owon.OwonService/GetWaveform"
	OwonService_Subscribe_FullMethodName         = "/xaionaro.owon.OwonService/Subscribe"
)

// OwonServiceClient is the client API for OwonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OwonServiceClient interface {
	GetDeviceInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeviceInfo, error)
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*StateSnapshot, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetAcquisition(ctx context.Context, in *SetAcquisitionRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetHorizontal(ctx context.Context, in *SetHorizontalRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetTrigger(ctx context.Context, in *SetTriggerRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetMeasurement(ctx context.Context, in *SetMeasurementRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetGenerator(ctx context.Context, in *SetGeneratorRequest, opts ...grpc.CallOption) (*CommandResult, error)
	SetDmm(ctx context.Context, in *SetDmmRequest, opts ...grpc.CallOption) (*CommandResult, error)
	GetDmmMeasurement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DmmMeasurement, error)
	Run(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommandResult, error)
	Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommandResult, error)
	Single(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommandResult, error)
	GetWaveform(ctx context.Context, in *GetWaveformRequest, opts ...grpc.CallOption) (*Waveform, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
}

type owonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOwonServiceClient(cc grpc.ClientConnInterface) OwonServiceClient {
	return &owonServiceClient{cc}
}

func (c *owonServiceClient) GetDeviceInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DeviceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceInfo)
	err := c.cc.Invoke(ctx, OwonService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*StateSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateSnapshot)
	err := c.cc.Invoke(ctx, OwonService_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, OwonService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetChannel(ctx context.Context, in *SetChannelRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetAcquisition(ctx context.Context, in *SetAcquisitionRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetAcquisition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetHorizontal(ctx context.Context, in *SetHorizontalRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetHorizontal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetTrigger(ctx context.Context, in *SetTriggerRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetMeasurement(ctx context.Context, in *SetMeasurementRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetGenerator(ctx context.Context, in *SetGeneratorRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetGenerator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) SetDmm(ctx context.Context, in *SetDmmRequest, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_SetDmm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) GetDmmMeasurement(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DmmMeasurement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DmmMeasurement)
	err := c.cc.Invoke(ctx, OwonService_GetDmmMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) Run(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) Stop(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) Single(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResult)
	err := c.cc.Invoke(ctx, OwonService_Single_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) GetWaveform(ctx context.Context, in *GetWaveformRequest, opts ...grpc.CallOption) (*Waveform, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Waveform)
	err := c.cc.Invoke(ctx, OwonService_GetWaveform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *owonServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OwonService_ServiceDesc.Streams[0], OwonService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OwonService_SubscribeClient = grpc.ServerStreamingClient[Event]

// OwonServiceServer is the server API for OwonService service.
// All implementations must embed UnimplementedOwonServiceServer
// for forward compatibility.
type OwonServiceServer interface {
	GetDeviceInfo(context.Context, *emptypb.Empty) (*DeviceInfo, error)
	GetState(context.Context, *GetStateRequest) (*StateSnapshot, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	SetChannel(context.Context, *SetChannelRequest) (*CommandResult, error)
	SetAcquisition(context.Context, *SetAcquisitionRequest) (*CommandResult, error)
	SetHorizontal(context.Context, *SetHorizontalRequest) (*CommandResult, error)
	SetTrigger(context.Context, *SetTriggerRequest) (*CommandResult, error)
	SetMeasurement(context.Context, *SetMeasurementRequest) (*CommandResult, error)
	SetGenerator(context.Context, *SetGeneratorRequest) (*CommandResult, error)
	SetDmm(context.Context, *SetDmmRequest) (*CommandResult, error)
	GetDmmMeasurement(context.Context, *emptypb.Empty) (*DmmMeasurement, error)
	Run(context.Context, *emptypb.Empty) (*CommandResult, error)
	Stop(context.Context, *emptypb.Empty) (*CommandResult, error)
	Single(context.Context, *emptypb.Empty) (*CommandResult, error)
	GetWaveform(context.Context, *GetWaveformRequest) (*Waveform, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error
	mustEmbedUnimplementedOwonServiceServer()
}

// UnimplementedOwonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOwonServiceServer struct{}

func (UnimplementedOwonServiceServer) GetDeviceInfo(context.Context, *emptypb.Empty) (*DeviceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedOwonServiceServer) GetState(context.Context, *GetStateRequest) (*StateSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedOwonServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedOwonServiceServer) SetChannel(context.Context, *SetChannelRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetChannel not implemented")
}
func (UnimplementedOwonServiceServer) SetAcquisition(context.Context, *SetAcquisitionRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAcquisition not implemented")
}
func (UnimplementedOwonServiceServer) SetHorizontal(context.Context, *SetHorizontalRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetHorizontal not implemented")
}
func (UnimplementedOwonServiceServer) SetTrigger(context.Context, *SetTriggerRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrigger not implemented")
}
func (UnimplementedOwonServiceServer) SetMeasurement(context.Context, *SetMeasurementRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMeasurement not implemented")
}
func (UnimplementedOwonServiceServer) SetGenerator(context.Context, *SetGeneratorRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGenerator not implemented")
}
func (UnimplementedOwonServiceServer) SetDmm(context.Context, *SetDmmRequest) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDmm not implemented")
}
func (UnimplementedOwonServiceServer) GetDmmMeasurement(context.Context, *emptypb.Empty) (*DmmMeasurement, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDmmMeasurement not implemented")
}
func (UnimplementedOwonServiceServer) Run(context.Context, *emptypb.Empty) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedOwonServiceServer) Stop(context.Context, *emptypb.Empty) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedOwonServiceServer) Single(context.Context, *emptypb.Empty) (*CommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Single not implemented")
}
func (UnimplementedOwonServiceServer) GetWaveform(context.Context, *GetWaveformRequest) (*Waveform, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWaveform not implemented")
}
func (UnimplementedOwonServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedOwonServiceServer) mustEmbedUnimplementedOwonServiceServer() {}
func (UnimplementedOwonServiceServer) testEmbeddedByValue()                     {}

// UnsafeOwonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OwonServiceServer will
// result in compilation errors.
type UnsafeOwonServiceServer interface {
	mustEmbedUnimplementedOwonServiceServer()
}

func RegisterOwonServiceServer(s grpc.ServiceRegistrar, srv OwonServiceServer) {
	// If the following call panics, it indicates UnimplementedOwonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OwonService_ServiceDesc, srv)
}

func _OwonService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).GetDeviceInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetChannel(ctx, req.(*SetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetAcquisition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAcquisitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetAcquisition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetAcquisition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetAcquisition(ctx, req.(*SetAcquisitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetHorizontal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHorizontalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetHorizontal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetHorizontal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetHorizontal(ctx, req.(*SetHorizontalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetTrigger(ctx, req.(*SetTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetMeasurement(ctx, req.(*SetMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetGenerator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGeneratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetGenerator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetGenerator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetGenerator(ctx, req.(*SetGeneratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_SetDmm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDmmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).SetDmm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_SetDmm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).SetDmm(ctx, req.(*SetDmmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_GetDmmMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).GetDmmMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_GetDmmMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).GetDmmMeasurement(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).Run(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).Stop(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_Single_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).Single(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_Single_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).Single(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_GetWaveform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWaveformRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OwonServiceServer).GetWaveform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OwonService_GetWaveform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OwonServiceServer).GetWaveform(ctx, req.(*GetWaveformRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OwonService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OwonServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OwonService_SubscribeServer = grpc.ServerStreamingServer[Event]

// OwonService_ServiceDesc is the grpc.ServiceDesc for OwonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OwonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xaionaro.owon.OwonService",
	HandlerType: (*OwonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _OwonService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _OwonService_GetState_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _OwonService_Execute_Handler,
		},
		{
			MethodName: "SetChannel",
			Handler:    _OwonService_SetChannel_Handler,
		},
		{
			MethodName: "SetAcquisition",
			Handler:    _OwonService_SetAcquisition_Handler,
		},
		{
			MethodName: "SetHorizontal",
			Handler:    _OwonService_SetHorizontal_Handler,
		},
		{
			MethodName: "SetTrigger",
			Handler:    _OwonService_SetTrigger_Handler,
		},
		{
			MethodName: "SetMeasurement",
			Handler:    _OwonService_SetMeasurement_Handler,
		},
		{
			MethodName: "SetGenerator",
			Handler:    _OwonService_SetGenerator_Handler,
		},
		{
			MethodName: "SetDmm",
			Handler:    _OwonService_SetDmm_Handler,
		},
		{
			MethodName: "GetDmmMeasurement",
			Handler:    _OwonService_GetDmmMeasurement_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _OwonService_Run_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _OwonService_Stop_Handler,
		},
		{
			MethodName: "Single",
			Handler:    _OwonService_Single_Handler,
		},
		{
			MethodName: "GetWaveform",
			Handler:    _OwonService_GetWaveform_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _OwonService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/owonrpc/owon.proto",
}
