// Package state implements the owonctl state command.
//
// Example: `owonctl state` prints both channels' measurements and current controls as JSON.
package state

import (
	"context"
	"errors"

	"github.com/facebookincubator/go-belt"
	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/spf13/cobra"
	"github.com/xaionaro-go/owon/pkg/owonctl"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
)

// commandHandler holds command inputs and shared connection policy.
//
// Example: Cobra populates command values before execution.
type commandHandler struct {
	Config *owonctl.ClientConfig
}

// NewCommand constructs this independently registered Cobra command.
//
// Example: the executable adds the command to its root.
func NewCommand(config *owonctl.ClientConfig) *cobra.Command {
	handler := &commandHandler{Config: config}
	command := &cobra.Command{Use: "state", Short: "Print instrument state as JSON", Args: cobra.NoArgs, RunE: handler.run}

	return command
}

// run validates inputs, owns the command connection, and writes the result.
//
// Example: invalid requests fail before a connection is constructed.
func (handler *commandHandler) run(
	command *cobra.Command,
	arguments []string,
) (_err error) {
	config, err := handler.Config.ConnectionConfig()
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(command.Context(), handler.Config.Timeout)
	defer cancel()
	ctx = belt.WithField(ctx, "command", "state")
	logger.Tracef(ctx, "state")
	// traceResult reports completion after command-owned cleanup.
	//
	// Example: operation and cleanup errors remain visible at trace level.
	defer func() { logger.Tracef(ctx, "/state: %v", _err) }()

	connection, err := owonclient.NewConnection(ctx, config)
	if err != nil {
		return err
	}

	// closeConnection retains independent cleanup failures.
	//
	// Example: an RPC failure cannot hide a connection close failure.
	defer func() { _err = errors.Join(_err, connection.Close()) }()

	logger.Debugf(ctx, "executing state")
	response, err := connection.Client().State(ctx, fullStateRequest())
	if err != nil {
		return err
	}

	return owonctl.PrintMessage(command.OutOrStdout(), response)
}

// fullStateRequest selects every verified scope measurement and screen control.
//
// Example: `owonctl state` returns both channels' scalar measurements and controls.
func fullStateRequest() *pb.GetStateRequest {
	channels := []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2}
	kinds := []pb.MeasurementKind{
		pb.MeasurementKind_MEASUREMENT_KIND_MAXIMUM,
		pb.MeasurementKind_MEASUREMENT_KIND_MINIMUM,
		pb.MeasurementKind_MEASUREMENT_KIND_PEAK_TO_PEAK,
		pb.MeasurementKind_MEASUREMENT_KIND_AMPLITUDE,
		pb.MeasurementKind_MEASUREMENT_KIND_AVERAGE,
		pb.MeasurementKind_MEASUREMENT_KIND_PERIOD,
		pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY,
	}
	selectors := make([]*pb.MeasurementSelector, 0, len(channels)*len(kinds))
	for _, channel := range channels {
		for _, kind := range kinds {
			selectors = append(selectors, &pb.MeasurementSelector{Channel: channel, Kind: kind})
		}
	}

	return &pb.GetStateRequest{
		Measurements:        selectors,
		IncludeScreenHeader: true,
		IncludeControls:     true,
	}
}
