package state

import (
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestFullStateRequestSelectsTheVerifiedStateSurface verifies the state command's default snapshot.
//
// Example: the CLI requests both channels, all seven verified measurement kinds, and controls.
func TestFullStateRequestSelectsTheVerifiedStateSurface(t *testing.T) {
	t.Parallel()

	request := fullStateRequest()
	require.Len(t, request.Measurements, 14)
	require.True(t, request.IncludeScreenHeader)
	require.True(t, request.IncludeControls)
	require.Equal(t, pb.Channel_CHANNEL_1, request.Measurements[0].Channel)
	require.Equal(t, pb.MeasurementKind_MEASUREMENT_KIND_MAXIMUM, request.Measurements[0].Kind)
	require.Equal(t, pb.Channel_CHANNEL_2, request.Measurements[len(request.Measurements)-1].Channel)
	require.Equal(t, pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY, request.Measurements[len(request.Measurements)-1].Kind)
}
