package owonweb

import (
	"context"
	"errors"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owoncontrol"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonserver"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// TestHTTPDMMFunctionBarrierStaysPendingAndReturnsAppliedTimestamp verifies the HTTP-to-controller mutation path.
//
// Example: an HTTP caller remains pending while the controller waits for the final matching function observation.
func TestHTTPDMMFunctionBarrierStaysPendingAndReturnsAppliedTimestamp(t *testing.T) {
	backend := newDMMHTTPBackend([][]byte{
		[]byte("CONTinuity"),
		[]byte("DIODe"),
		[]byte("DIODe"),
		[]byte("DIODe"),
		[]byte("DIODe"),
	})
	backend.BlockFinalQuery = true
	httpServer := newDMMHTTPFixture(
		t,
		backend,
	)

	responseCh := make(chan *http.Response, 1)
	errorCh := make(chan error, 1)
	observability.Go(t.Context(),
		// postPendingDMM submits the browser-shaped mutation while the final function query is gated.
		//
		// Example: the HTTP response channel remains empty until the controller proves its final observation.
		func(ctx context.Context) {
			request, err := http.NewRequestWithContext(
				ctx,
				http.MethodPost,
				httpServer.URL+"/api/dmm",
				strings.NewReader(`{"function":"DMM_FUNCTION_DIODE","relative":true}`),
			)
			if err != nil {
				errorCh <- err
				return
			}
			response, err := http.DefaultClient.Do(request)
			if err != nil {
				errorCh <- err
				return
			}
			responseCh <- response
		})

	select {
	case err := <-errorCh:
		t.Fatal(err)
	case <-backend.FinalQueryEntered:
	}
	select {
	case response := <-responseCh:
		require.NoError(t, response.Body.Close())
		t.Fatal("DMM HTTP mutation completed before final observation was released")
	default:
	}
	close(backend.ReleaseFinalQuery)

	select {
	case err := <-errorCh:
		t.Fatal(err)
	case response := <-responseCh:
		body, err := io.ReadAll(response.Body)
		require.NoError(t, err)
		require.NoError(t, response.Body.Close())
		require.Equal(t, http.StatusOK, response.StatusCode, string(body))
		require.Contains(t, string(body), "appliedAt")
	}
	require.Equal(t, []string{
		":DMM:CONFIGURE DIODE",
		":DMM:CONFIGURE?",
		":DMM:CONFIGURE?",
		":DMM:CONFIGURE?",
		":DMM:REL ON",
		":DMM:CONFIGURE?",
		":DMM:CONFIGURE?",
	}, backend.CommandsSnapshot())
}

// TestHTTPDMMFunctionBarrierReturnsHonestFailure verifies the browser receives a failure without an application timestamp.
//
// Example: a malformed function observation stops before REL and maps to an HTTP error describing possible partial application.
func TestHTTPDMMFunctionBarrierReturnsHonestFailure(t *testing.T) {
	backend := newDMMHTTPBackend([][]byte{[]byte("DIODe"), []byte("bogus")})
	httpServer := newDMMHTTPFixture(
		t,
		backend,
	)
	response, err := http.Post(
		httpServer.URL+"/api/dmm",
		"application/json",
		strings.NewReader(`{"function":"DMM_FUNCTION_DIODE","relative":true}`),
	)
	require.NoError(t, err)
	body, err := io.ReadAll(response.Body)
	require.NoError(t, err)
	require.NoError(t, response.Body.Close())
	require.Equal(t, http.StatusInternalServerError, response.StatusCode, string(body))
	require.Contains(t, string(body), `"code":"DataLoss"`)
	require.Contains(t, string(body), "possible partial or unknown application")
	require.NotContains(t, string(body), "appliedAt")
	require.Equal(t, []string{
		":DMM:CONFIGURE DIODE",
		":DMM:CONFIGURE?",
		":DMM:CONFIGURE?",
	}, backend.CommandsSnapshot())
}

// dmmHTTPBackend supplies deterministic function-query observations to the real controller.
//
// Example: a continuity reply followed by two diode replies models an asynchronous transition without hardware.
type dmmHTTPBackend struct {
	mu                sync.Mutex
	Commands          []string
	Responses         [][]byte
	QueryCount        int
	BlockFinalQuery   bool
	FinalQueryEntered chan struct{}
	ReleaseFinalQuery chan struct{}
}

// newDMMHTTPBackend creates a backend with one queued response per function query.
//
// Example: five queued diode observations cover both the initial and final barriers.
func newDMMHTTPBackend(responses [][]byte) *dmmHTTPBackend {
	return &dmmHTTPBackend{
		Responses:         responses,
		FinalQueryEntered: make(chan struct{}),
		ReleaseFinalQuery: make(chan struct{}),
	}
}

// Exchange records one real controller exchange and optionally gates the final query.
//
// Example: the gated final response proves the HTTP layer does not report success after writes alone.
func (backend *dmmHTTPBackend) Exchange(
	ctx context.Context,
	command owonprotocol.Command,
) ([]byte, error) {
	response, block := backend.recordCommand(command.Text)
	if block {
		close(backend.FinalQueryEntered)
		select {
		case <-backend.ReleaseFinalQuery:
		case <-ctx.Done():
			return nil, ctx.Err()
		}
	}
	return response, nil
}

// recordCommand appends one command and returns the next queued response plus its optional gate decision.
//
// Example: the fifth function query is held until the test releases final convergence.
func (backend *dmmHTTPBackend) recordCommand(command string) (response []byte, block bool) {
	backend.mu.Lock()
	defer backend.mu.Unlock()
	backend.Commands = append(backend.Commands, command)
	if command != ":DMM:CONFIGURE?" {
		return nil, false
	}
	backend.QueryCount++
	if len(backend.Responses) > 0 {
		response = append([]byte(nil), backend.Responses[0]...)
		backend.Responses = backend.Responses[1:]
	}
	return response, backend.BlockFinalQuery && backend.QueryCount == 5
}

// ReopenAndValidate keeps the deterministic backend compatible with session recovery.
//
// Example: the fixture never needs recovery, but it remains a complete session backend.
func (*dmmHTTPBackend) ReopenAndValidate(context.Context, owonmodel.SerialNumber) error {
	return nil
}

// Close releases no external resource in the in-memory fixture.
//
// Example: test cleanup can close the controller session without hardware.
func (*dmmHTTPBackend) Close(context.Context) error {
	return nil
}

// CommandsSnapshot returns a copy of the observed native command order.
//
// Example: the fixture asserts no REL write precedes initial function convergence.
func (backend *dmmHTTPBackend) CommandsSnapshot() []string {
	backend.mu.Lock()
	defer backend.mu.Unlock()
	return append([]string(nil), backend.Commands...)
}

// newDMMHTTPFixture builds the real HTTP, gRPC, RPC-server, controller, and session chain.
//
// Example: the returned URL accepts the same JSON body as a browser DMM form submission.
func newDMMHTTPFixture(
	t *testing.T,
	backend *dmmHTTPBackend,
) *httptest.Server {
	t.Helper()
	session, err := owonsession.New(
		backend,
		owonsession.Config{ExpectedSerial: "25061855"},
	)
	require.NoError(t, err)
	controller, err := owoncontrol.New(
		session,
		owonmodel.DeviceIdentity{},
	)
	require.NoError(t, err)
	deviceServer, err := owonserver.NewServer(controller)
	require.NoError(t, err)

	grpcListener := newBufconnListener()
	grpcServer := grpc.NewServer(owonserver.GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(grpcServer, deviceServer)
	serverErrors := make(chan error, 1)
	observability.Go(
		t.Context(),
		grpcServeRunner{Server: grpcServer, Listener: grpcListener, Errors: serverErrors}.Run,
	)
	t.Cleanup(
		// stopDMMFixture joins the serving goroutine before the fixture is released.
		//
		// Example: a stopped gRPC server cannot outlive the HTTP test.
		func() {
			grpcServer.Stop()
			serveErr := <-serverErrors
			if serveErr != nil && !errors.Is(serveErr, grpc.ErrServerStopped) {
				require.NoError(t, serveErr)
			}
		},
	)

	dialOptions := owonclient.GRPCClientDialOptions()
	dialOptions = append(dialOptions,
		grpc.WithContextDialer(
			// dialDMMFixture connects the generated client to the in-memory gRPC listener.
			//
			// Example: the HTTP handler traverses protobuf transport before reaching Controller.SetDMM.
			func(ctx context.Context, _ string) (net.Conn, error) {
				return grpcListener.DialContext(ctx)
			},
		),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	connection, err := grpc.NewClient("passthrough:///owon-dmm-fixture", dialOptions...)
	require.NoError(t, err)
	t.Cleanup(
		// closeDMMFixtureClient releases the generated client after HTTP shutdown.
		//
		// Example: cleanup reports a transport close failure instead of hiding it.
		func() { require.NoError(t, connection.Close()) },
	)
	httpServer := httptest.NewServer(mustHandler(t, pb.NewOwonServiceClient(connection)))
	t.Cleanup(httpServer.Close)
	return httpServer
}
