package owonweb

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"

	"github.com/facebookincubator/go-belt"
	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonlog"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonserver"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/test/bufconn"
	"google.golang.org/protobuf/types/known/emptypb"
)

// TestHTTPBridgeRoundTripsNativeGRPC verifies the built transport boundary through a real gRPC server.
//
// Example: browser-shaped HTTP requests reach typed daemon methods and a native stream returns as SSE.
func TestHTTPBridgeRoundTripsNativeGRPC(t *testing.T) {
	t.Parallel()

	grpcListener := newBufconnListener()
	grpcServer := grpc.NewServer(owonserver.GRPCServerOptions()...)
	deviceServer := &integrationService{}
	pb.RegisterOwonServiceServer(grpcServer, deviceServer)
	serverErrors := make(chan error, 1)
	observability.Go(context.Background(), grpcServeRunner{Server: grpcServer, Listener: grpcListener, Errors: serverErrors}.Run)
	t.Cleanup(
		// stopGRPC joins the server after closing its listener.
		//
		// Example: integration completion leaves no background serving goroutine.
		func() {
			grpcServer.Stop()
			serveErr := <-serverErrors
			switch {
			case serveErr == nil, errors.Is(serveErr, grpc.ErrServerStopped):
			default:
				require.NoError(t, serveErr)
			}
		})

	dialOptions := owonclient.GRPCClientDialOptions()
	dialOptions = append(dialOptions,
		grpc.WithContextDialer(
			// dialTestTransport connects generated clients to the real in-process gRPC server.
			//
			// Example: a channel patch traverses protobuf encoding before recording.
			func(
				ctx context.Context,
				_ string,
			) (net.Conn, error) {
				return grpcListener.DialContext(ctx)
			}),
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	connection, err := grpc.NewClient("passthrough:///owonweb-test", dialOptions...)
	require.NoError(t, err)
	t.Cleanup(
		// closeClient verifies connection cleanup after all HTTP requests finish.
		//
		// Example: test shutdown reports a close failure instead of swallowing it.
		func() { require.NoError(t, connection.Close()) })
	var output bytes.Buffer
	ctx, err := owonlog.WithContext(belt.WithField(t.Context(), "endpoint", "fixture"), owonlog.Config{Level: logger.LevelTrace, Service: "owonweb"}, &output)
	require.NoError(t, err)
	httpServer := httptest.NewUnstartedServer(mustHandler(t, pb.NewOwonServiceClient(connection)))
	httpServer.Config.BaseContext =
		// httpContext adapts net/http's required callback without retaining context in a struct.
		//
		// Example: real HTTP requests inherit process fields and their own cancellation lifetime.
		func(net.Listener) context.Context { return ctx }
	httpServer.Start()
	t.Cleanup(httpServer.Close)

	deviceResponse, err := http.Get(httpServer.URL + "/api/device")
	require.NoError(t, err)
	deviceBody, err := io.ReadAll(deviceResponse.Body)
	require.NoError(t, err)
	require.NoError(t, deviceResponse.Body.Close())
	require.Equal(t, http.StatusOK, deviceResponse.StatusCode)
	require.Contains(t, string(deviceBody), "HDS2202S")

	channelResponse, err := http.Post(httpServer.URL+"/api/channel", "application/json", strings.NewReader(`{"channel":"CHANNEL_1","display":false}`))
	require.NoError(t, err)
	require.NoError(t, channelResponse.Body.Close())
	require.Equal(t, http.StatusOK, channelResponse.StatusCode)
	require.NotNil(t, deviceServer.recordedChannel())
	require.False(t, deviceServer.recordedChannel().GetDisplay())

	eventsResponse, err := http.Get(httpServer.URL + "/api/events?interval=1s")
	require.NoError(t, err)
	eventsBody, err := io.ReadAll(eventsResponse.Body)
	require.NoError(t, err)
	require.NoError(t, eventsResponse.Body.Close())
	require.Equal(t, http.StatusOK, eventsResponse.StatusCode)
	require.Equal(t, "text/event-stream", eventsResponse.Header.Get("Content-Type"))
	require.Contains(t, string(eventsBody), "id: 12")
	httpServer.Close()
	for _, field := range []string{"service=owonweb", "endpoint=fixture", "http_path=/api/device", "http_path=/api/channel", "http_path=/api/events", "http_method=GET", "http_method=POST", "browser subscription started"} {
		require.Contains(t, output.String(), field)
	}
	require.NotContains(t, output.String(), "payload=")
}

// integrationService implements the small native gRPC surface exercised by the HTTP bridge test.
//
// Example: the fake records SetChannel while Subscribe emits one deterministic state event.
type integrationService struct {
	pb.UnimplementedOwonServiceServer
	channel atomic.Pointer[pb.SetChannelRequest]
}

// recordedChannel reads the completed RPC's atomically published request.
//
// Example: a synchronous HTTP response guarantees its channel patch is available.
func (service *integrationService) recordedChannel() *pb.SetChannelRequest {
	return service.channel.Load()
}

// GetDeviceInfo returns stable identity data for the integration test.
//
// Example: the browser device endpoint receives model `HDS2202S`.
func (service *integrationService) GetDeviceInfo(
	context.Context,
	*emptypb.Empty,
) (*pb.DeviceInfo, error) {
	return &pb.DeviceInfo{Manufacturer: "OWON", Model: "HDS2202S", Serial: "integration"}, nil
}

// SetChannel records the latest channel patch for integration assertions.
//
// Example: an HTTP channel update can be observed after the gRPC round trip.
func (service *integrationService) SetChannel(
	_ context.Context,
	request *pb.SetChannelRequest,
) (*pb.CommandResult, error) {
	service.channel.Store(request)
	return new(pb.CommandResult), nil
}

// Subscribe emits one deterministic state event for the SSE integration check.
//
// Example: the HTTP stream contains `id: 12` after the browser subscribes.
func (service *integrationService) Subscribe(
	_ *pb.SubscribeRequest,
	stream pb.OwonService_SubscribeServer,
) error {
	return stream.Send(&pb.Event{Sequence: 12, Payload: &pb.Event_State{State: &pb.StateSnapshot{Device: &pb.DeviceInfo{Model: "HDS2202S"}}}})
}

// grpcServeRunner adapts grpc.Server.Serve to the observability goroutine runner shape.
//
// Example: observability.Go(ctx, runner.Run) records the terminal test-server error.
type grpcServeRunner struct {
	Server   *grpc.Server
	Listener net.Listener
	Errors   chan<- error
}

// Run serves the integration gRPC listener and reports its terminal error.
//
// Example: stopping the test server produces grpc.ErrServerStopped on the result channel.
func (runner grpcServeRunner) Run(context.Context) {
	runner.Errors <- runner.Server.Serve(runner.Listener)
}

// newBufconnListener creates the in-memory listener used by the integration test.
//
// Example: grpc.NewClient can dial this listener without opening a TCP port.
func newBufconnListener() *bufconn.Listener { return bufconn.Listen(1 << 20) }
