// Package owonweb bridges typed OWON RPCs to a same-origin browser interface.
//
// Example: attach NewHandler's result to an HTTP server with a process BaseContext.
package owonweb

import (
	"bytes"
	"context"
	"embed"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"reflect"
	"strings"
	"time"

	"github.com/facebookincubator/go-belt"
	"github.com/facebookincubator/go-belt/tool/logger"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Web UI defaults and request limits keep the local browser bridge bounded.
//
// Example: maxRequestBodyBytes rejects an oversized JSON request before it reaches gRPC.
const (
	// maxRequestBodyBytes bounds browser JSON request bodies.
	//
	// Example: a body larger than one mebibyte is rejected before protobuf decoding.
	maxRequestBodyBytes = 1 << 20
	// maxSSEEventBytes bounds one serialized event sent to a browser.
	//
	// Example: an unexpectedly large waveform event becomes a structured stream error.
	maxSSEEventBytes = 8 << 20
	// maxSubscribeQuery bounds the optional JSON subscription query.
	//
	// Example: a query larger than 64 KiB is rejected before opening a stream.
	maxSubscribeQuery = 64 << 10
	// apiTimeout bounds one browser-to-daemon request.
	//
	// Example: a stalled control RPC returns a timeout instead of holding a handler forever.
	apiTimeout = 15 * time.Second
)

// embeddedUI contains the browser assets served by the binary.
//
// Example: NewHandler serves `index.html` from this embedded filesystem.
//
//go:embed ui/*
var embeddedUI embed.FS

// httpHandler keeps dependencies private so requests cannot replace the client.
//
// Example: all browser requests share a client while retaining separate contexts.
type httpHandler struct {
	client pb.OwonServiceClient
	static http.Handler
}

// NewHandler constructs the browser bridge, rejecting unavailable dependencies.
//
// Example: handler, err := owonweb.NewHandler(pb.NewOwonServiceClient(connection)).
func NewHandler(client pb.OwonServiceClient) (http.Handler, error) {
	if client == nil || (reflect.ValueOf(client).Kind() == reflect.Pointer && reflect.ValueOf(client).IsNil()) {
		return nil, &ErrInvalidWebRequest{Reason: "gRPC client is required"}
	}
	ui, err := fs.Sub(embeddedUI, "ui")
	if err != nil {
		return nil, fmt.Errorf("open embedded UI: %w", err)
	}
	return &httpHandler{client: client, static: http.FileServer(http.FS(ui))}, nil
}

// ServeHTTP reports response failures through the request's contextual logger.
//
// Example: a disconnected reader produces a diagnostic without a second HTTP response.
func (handler *httpHandler) ServeHTTP(
	writer http.ResponseWriter,
	request *http.Request,
) {
	ctx := belt.WithField(request.Context(), "http_method", request.Method)
	ctx = belt.WithField(ctx, "http_path", request.URL.Path)
	request = request.WithContext(ctx)
	logger.Tracef(ctx, "ServeHTTP")
	logger.Debugf(ctx, "HTTP request started")
	err := handler.serve(writer, request)
	logger.Tracef(ctx, "/ServeHTTP: %v", err)
	if err != nil {
		logger.Errorf(ctx, "serve HTTP request: %v", err)
	}
}

// serve owns routing and returns every API response write failure.
//
// Example: invalid JSON is written once as a 400 response.
func (handler *httpHandler) serve(
	writer http.ResponseWriter,
	request *http.Request,
) error {
	setSecurityHeaders(writer)
	if strings.HasPrefix(request.URL.Path, "/api/") {
		if err := sameOrigin(request); err != nil {
			return writeRPCError(writer, status.Error(codes.PermissionDenied, err.Error()))
		}
	}
	switch request.URL.Path {
	case "/healthz":
		if request.Method != http.MethodGet {
			return methodError(writer, http.MethodGet)
		}
		writer.WriteHeader(http.StatusNoContent)
		return nil
	case "/api/events":
		return handler.handleEvents(writer, request)
	}
	message, method := routeRequest(request.URL.Path)
	if message == nil {
		handler.static.ServeHTTP(writer, request)
		return nil
	}
	message, err := prepareRPCRequestOrWriteRejection(writer, request, message, method)
	if err != nil || message == nil {
		return err
	}
	ctx, cancel := context.WithTimeout(request.Context(), apiTimeout)
	defer cancel()
	response, err := handler.call(ctx, request.URL.Path, message)
	if err != nil {
		logger.Debugf(ctx, "HTTP RPC failed: %v", err)
		return writeRPCError(writer, err)
	}
	return writeProto(writer, response)
}

// prepareRPCRequestOrWriteRejection checks method and body before a request can reach the daemon.
// A nil message means that an HTTP rejection has already been attempted.
//
// Example: GET state requests include controls while empty POST actions need no JSON body.
func prepareRPCRequestOrWriteRejection(
	writer http.ResponseWriter,
	request *http.Request,
	message proto.Message,
	method string,
) (proto.Message, error) {
	if request.URL.Path == "/api/state" && request.Method == http.MethodGet {
		return &pb.GetStateRequest{IncludeScreenHeader: true, IncludeControls: true}, nil
	}
	if request.Method != method {
		if request.URL.Path == "/api/state" {
			method = "GET, POST"
		}
		return nil, methodError(writer, method)
	}
	if method != http.MethodPost {
		return message, nil
	}
	switch request.URL.Path {
	case "/api/run", "/api/stop", "/api/single":
		return message, nil
	}
	if err := decodeProtoBody(writer, request, message); err != nil {
		return nil, writeRPCError(writer, status.Error(codes.InvalidArgument, err.Error()))
	}
	return message, nil
}

// routeRequest associates URL contracts with concrete protobuf request shapes.
//
// Example: channel patches decode into SetChannelRequest, preserving optional false.
func routeRequest(path string) (proto.Message, string) {
	switch path {
	case "/api/device", "/api/dmm/measurement":
		return new(emptypb.Empty), http.MethodGet
	case "/api/run", "/api/stop", "/api/single":
		return new(emptypb.Empty), http.MethodPost
	case "/api/state":
		return new(pb.GetStateRequest), http.MethodPost
	case "/api/execute":
		return new(pb.ExecuteRequest), http.MethodPost
	case "/api/channel":
		return new(pb.SetChannelRequest), http.MethodPost
	case "/api/acquisition":
		return new(pb.SetAcquisitionRequest), http.MethodPost
	case "/api/horizontal":
		return new(pb.SetHorizontalRequest), http.MethodPost
	case "/api/trigger":
		return new(pb.SetTriggerRequest), http.MethodPost
	case "/api/measurement":
		return new(pb.SetMeasurementRequest), http.MethodPost
	case "/api/generator":
		return new(pb.SetGeneratorRequest), http.MethodPost
	case "/api/dmm":
		return new(pb.SetDmmRequest), http.MethodPost
	case "/api/waveform":
		return new(pb.GetWaveformRequest), http.MethodPost
	default:
		return nil, ""
	}
}

// call uses checked type dispatch instead of storing cross-layer function values.
//
// Example: unknown request types return a protocol error rather than panicking.
func (handler *httpHandler) call(
	ctx context.Context,
	path string,
	message proto.Message,
) (proto.Message, error) {
	switch request := message.(type) {
	case *pb.GetStateRequest:
		return handler.client.GetState(ctx, request)
	case *pb.ExecuteRequest:
		return handler.client.Execute(ctx, request)
	case *pb.SetChannelRequest:
		return handler.client.SetChannel(ctx, request)
	case *pb.SetAcquisitionRequest:
		return handler.client.SetAcquisition(ctx, request)
	case *pb.SetHorizontalRequest:
		return handler.client.SetHorizontal(ctx, request)
	case *pb.SetTriggerRequest:
		return handler.client.SetTrigger(ctx, request)
	case *pb.SetMeasurementRequest:
		return handler.client.SetMeasurement(ctx, request)
	case *pb.SetGeneratorRequest:
		return handler.client.SetGenerator(ctx, request)
	case *pb.SetDmmRequest:
		return handler.client.SetDmm(ctx, request)
	case *pb.GetWaveformRequest:
		return handler.client.GetWaveform(ctx, request)
	case *emptypb.Empty:
		switch path {
		case "/api/device":
			return handler.client.GetDeviceInfo(ctx, request)
		case "/api/dmm/measurement":
			return handler.client.GetDmmMeasurement(ctx, request)
		case "/api/run":
			return handler.client.Run(ctx, request)
		case "/api/stop":
			return handler.client.Stop(ctx, request)
		case "/api/single":
			return handler.client.Single(ctx, request)
		}
	}
	return nil, &ErrInvalidWebProtocol{Reason: fmt.Sprintf("unsupported RPC request %T for %s", message, path)}
}

// setSecurityHeaders restricts executable content and cross-origin embedding.
//
// Example: scripts and connections must originate from this HTTP service.
func setSecurityHeaders(writer http.ResponseWriter) {
	writer.Header().Set("Content-Security-Policy", "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; base-uri 'none'; frame-ancestors 'none'")
	writer.Header().Set("Referrer-Policy", "no-referrer")
	writer.Header().Set("X-Content-Type-Options", "nosniff")
	writer.Header().Set("Cross-Origin-Opener-Policy", "same-origin")
	writer.Header().Set("Cross-Origin-Resource-Policy", "same-origin")
}

// sameOrigin validates browser origin metadata before any instrument operation.
//
// Example: an external page cannot submit a loopback generator request.
func sameOrigin(request *http.Request) error {
	site := strings.TrimSpace(strings.ToLower(request.Header.Get("Sec-Fetch-Site")))
	if site != "" && site != "same-origin" && site != "none" {
		return &ErrInvalidWebRequest{Reason: "cross-site API request rejected"}
	}
	origin := request.Header.Get("Origin")
	if origin == "" {
		return nil
	}
	parsed, err := url.Parse(origin)
	scheme := "http"
	if request.TLS != nil {
		scheme = "https"
	}
	if err != nil || parsed.Scheme != scheme || parsed.Host == "" || parsed.Host != request.Host {
		return &ErrInvalidWebRequest{Reason: "cross-origin API request rejected", Cause: err}
	}
	return nil
}

// methodError supplies the allowed methods and preserves failed response writes.
//
// Example: GET against a mutation receives 405 and an Allow header.
func methodError(
	writer http.ResponseWriter,
	method string,
) error {
	writer.Header().Set("Allow", method)
	return writeJSON(writer, http.StatusMethodNotAllowed, []byte("{\"message\":\"method not allowed\"}"))
}

// decodeProtoBody validates bounded JSON without committing a response.
//
// Example: callers classify unknown fields as invalid browser input.
func decodeProtoBody(
	writer http.ResponseWriter,
	request *http.Request,
	message proto.Message,
) error {
	body, err := io.ReadAll(http.MaxBytesReader(writer, request.Body, maxRequestBodyBytes))
	if err != nil {
		return &ErrInvalidWebRequest{Reason: "request body is too large or unreadable", Cause: err}
	}
	trimmed := bytes.TrimSpace(body)
	if len(trimmed) == 0 || bytes.Equal(trimmed, []byte("null")) {
		return &ErrInvalidWebRequest{Reason: "request body is required"}
	}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: false}).Unmarshal(body, message); err != nil {
		return &ErrInvalidWebRequest{Reason: "invalid protobuf JSON", Cause: err}
	}
	return nil
}

// writeProto retains protobuf presence and propagates serialization or write failure.
//
// Example: an omitted measurement value stays omitted on the wire and means zero.
func writeProto(
	writer http.ResponseWriter,
	message proto.Message,
) error {
	payload, err := (protojson.MarshalOptions{UseProtoNames: false}).Marshal(message)
	if err != nil {
		return writeRPCError(writer, err)
	}
	return writeJSON(writer, http.StatusOK, payload)
}

// writeRPCError maps gRPC categories into browser-readable response status.
//
// Example: daemon unavailability becomes a 503 response.
func writeRPCError(
	writer http.ResponseWriter,
	err error,
) error {
	rpcStatus := status.Convert(err)
	payload, marshalErr := json.Marshal(map[string]string{"code": rpcStatus.Code().String(), "message": rpcStatus.Message()})
	if marshalErr != nil {
		return errors.Join(err, fmt.Errorf("serialize RPC error: %w", marshalErr))
	}
	if deliveryErr := writeJSON(writer, httpStatus(rpcStatus.Code()), payload); deliveryErr != nil {
		return errors.Join(err, fmt.Errorf("deliver RPC error: %w", deliveryErr))
	}
	return nil
}

// writeJSON bounds an actual response write independently from the request lifetime.
//
// Example: a stalled reader cannot hold an API handler indefinitely.
func writeJSON(
	writer http.ResponseWriter,
	statusCode int,
	payload []byte,
) error {
	if err := setWriteDeadline(writer, time.Now().Add(apiTimeout)); err != nil {
		return err
	}
	writer.Header().Set("Content-Type", "application/json; charset=utf-8")
	writer.WriteHeader(statusCode)
	_, err := writer.Write(payload)
	return err
}

// setWriteDeadline permits documented in-memory writers lacking network deadlines.
//
// Example: httptest.ResponseRecorder returns ErrNotSupported, while real socket errors propagate.
func setWriteDeadline(
	writer http.ResponseWriter,
	deadline time.Time,
) error {
	err := http.NewResponseController(writer).SetWriteDeadline(deadline)
	if errors.Is(err, http.ErrNotSupported) {
		return nil
	}
	return err
}

// httpStatus maps gRPC status categories to browser recovery semantics.
//
// Example: codes.Unavailable becomes HTTP 503 so the browser can show a degraded state.
func httpStatus(code codes.Code) int {
	switch code {
	case codes.InvalidArgument:
		return http.StatusBadRequest
	case codes.Unauthenticated:
		return http.StatusUnauthorized
	case codes.PermissionDenied:
		return http.StatusForbidden
	case codes.NotFound:
		return http.StatusNotFound
	case codes.AlreadyExists, codes.Aborted:
		return http.StatusConflict
	case codes.ResourceExhausted:
		return http.StatusTooManyRequests
	case codes.FailedPrecondition:
		return http.StatusPreconditionFailed
	case codes.Unimplemented:
		return http.StatusNotImplemented
	case codes.DeadlineExceeded:
		return http.StatusGatewayTimeout
	case codes.Unavailable:
		return http.StatusServiceUnavailable
	default:
		return http.StatusInternalServerError
	}
}
