package owonweb

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// TestHandlerServesEmbeddedUI verifies the browser entry point is available without a filesystem asset.
//
// Example: an operator opening the web client receives the branded shell from the Go binary.
func TestHandlerServesEmbeddedUI(t *testing.T) {
	t.Parallel()

	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodGet, "/", nil)
	mustHandler(t, &fakeService{}).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusOK, recorder.Code)
	require.Contains(t, recorder.Body.String(), "OWON Control")
	require.Equal(t, "text/html; charset=utf-8", recorder.Header().Get("Content-Type"))
}

// TestEmbeddedUIUsesApprovedDisclosureAndFriendlyLabels verifies low-frequency
// controls stay available behind native disclosure while enum values remain exact.
//
// Example: an operator sees “Channel 1” in a select while the request still sends CHANNEL_1.
func TestEmbeddedUIUsesApprovedDisclosureAndFriendlyLabels(t *testing.T) {
	t.Parallel()

	recorder := httptest.NewRecorder()
	mustHandler(t, &fakeService{}).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/", nil))
	body := recorder.Body.String()

	require.Equal(t, 7, strings.Count(body, "<details"))
	require.NotContains(t, body, "<details open")
	for _, label := range []string{
		`value="CHANNEL_1">Channel 1`,
		`value="CHANNEL_2">Channel 2`,
		`value="COUPLING_DC">DC`,
		`value="ACQUISITION_MODE_SAMPLE">Sample`,
		`value="TRIGGER_SOURCE_CHANNEL_1">Channel 1`,
		`value="GENERATOR_WAVEFORM_SINE">Sine`,
		`value="GENERATOR_LOAD_ON">ON`,
		`value="GENERATOR_LOAD_OFF">OFF`,
		`value="DMM_FUNCTION_VOLTAGE">Voltage`,
		`value="DMM_RANGE_MV">mV`,
		`value="DMM_RANGE_V">V`,
		`value="DMM_RANGE_ON">ON`,
		`value="ACQUISITION_MEMORY_DEPTH_4K">4K`,
		`value="ACQUISITION_MEMORY_DEPTH_8K">8K`,
		`value="RESPONSE_MODE_ASCII_LINE">ASCII line`,
	} {
		require.Contains(t, body, label)
	}
	require.Contains(t, body, `class="brand-mark"`)
	require.Contains(t, body, "<summary>")
	require.Contains(t, body, `placeholder="1.0ms"`)
	require.Contains(t, body, `class="badge">LOGICAL READBACK</span>`)
	require.NotContains(t, body, `class="badge">WRITE ONLY</span>`)
	require.Contains(t, body, "bounded logical operation readback")
	require.Contains(t, body, "does not validate electrical output")
}

// TestHandlerAcceptsProtoJSONForChannelPatch verifies browser field names reach the typed RPC boundary.
//
// Example: an unchecked display control is preserved as an explicit false value.
func TestHandlerAcceptsProtoJSONForChannelPatch(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(`{"channel":"CHANNEL_1","display":false,"scale":"500mV"}`))
	request.Header.Set("Content-Type", "application/json")
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusOK, recorder.Code)
	require.NotNil(t, service.ChannelRequest)
	require.Equal(t, pb.Channel_CHANNEL_1, service.ChannelRequest.GetChannel())
	require.NotNil(t, service.ChannelRequest.Display)
	require.False(t, service.ChannelRequest.GetDisplay())
	require.Equal(t, "500mV", service.ChannelRequest.GetScale())
}

// TestHandlerPreservesExplicitZeroForChannelPatch verifies optional numeric
// presence survives JSON decoding instead of being treated as omitted.
//
// Example: an operator can intentionally set offset divisions to zero.
func TestHandlerPreservesExplicitZeroForChannelPatch(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(`{"channel":"CHANNEL_1","offsetDivisions":0}`))
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusOK, recorder.Code)
	require.NotNil(t, service.ChannelRequest)
	require.NotNil(t, service.ChannelRequest.OffsetDivisions)
	require.Zero(t, service.ChannelRequest.GetOffsetDivisions())
}

// TestHandlerRejectsInvalidOffsetJSON verifies malformed int64 values never reach the RPC boundary.
//
// Example: a fractional offset with a valid display field returns 400 without applying either field.
func TestHandlerRejectsInvalidOffsetJSON(t *testing.T) {
	t.Parallel()
	for _, value := range []string{`0.25`, `"-0.25"`, `"NaN"`, `"Infinity"`, `"9223372036854775808"`, `"-9223372036854775809"`} {
		service := &fakeService{}
		recorder := httptest.NewRecorder()
		request := httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(`{"channel":"CHANNEL_1","display":true,"offsetDivisions":`+value+`}`))
		mustHandler(t, service).ServeHTTP(recorder, request)
		require.Equal(t, http.StatusBadRequest, recorder.Code, value)
		require.Contains(t, recorder.Body.String(), "InvalidArgument")
		require.Nil(t, service.ChannelRequest)
	}
}

// TestHandlerKeepsOmittedStateFieldsOmitted verifies a POST state request does
// not inherit the browser GET defaults.
//
// Example: `{}` remains an empty GetStateRequest instead of silently enabling
// screen headers and controls.
func TestHandlerKeepsOmittedStateFieldsOmitted(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodPost, "/api/state", strings.NewReader(`{}`))
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusOK, recorder.Code)
	require.NotNil(t, service.StateRequest)
	require.False(t, service.StateRequest.IncludeScreenHeader)
	require.False(t, service.StateRequest.IncludeControls)
}

// TestHandlerRejectsUnknownProtoJSONFields verifies malformed browser payloads fail before hardware access.
//
// Example: a typo in a control name returns a client error instead of being silently ignored.
func TestHandlerRejectsUnknownProtoJSONFields(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(`{"channel":"CHANNEL_1","displayy":true}`))
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusBadRequest, recorder.Code)
	require.Nil(t, service.ChannelRequest)
	require.Contains(t, recorder.Body.String(), "displayy")
}

// TestHandlerRejectsCrossOriginAPIRequests verifies browser-origin checks protect mutating routes.
//
// Example: an unrelated page cannot send a channel patch even when the web client is on loopback.
func TestHandlerRejectsCrossOriginAPIRequests(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(`{"channel":"CHANNEL_1"}`))
	request.Header.Set("Origin", "https://attacker.example")
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusForbidden, recorder.Code)
	require.Nil(t, service.ChannelRequest)
}

// TestHandlerRejectsCrossSiteFetches verifies Fetch Metadata protects API routes
// even when a browser omits the Origin header.
//
// Example: an attacker page cannot use a cross-site fetch to stop acquisition.
func TestHandlerRejectsCrossSiteFetches(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodPost, "/api/stop", nil)
	request.Header.Set("Sec-Fetch-Site", "cross-site")
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusForbidden, recorder.Code)
}

// TestHandlerStreamsEventsAsSSE verifies one server event reaches the browser stream with its sequence id.
//
// Example: EventSource can consume the state payload without a polling loop.
func TestHandlerStreamsEventsAsSSE(t *testing.T) {
	t.Parallel()

	service := &fakeService{EventStream: &fakeEventStream{Events: []*pb.Event{
		{Sequence: 7, Payload: &pb.Event_State{State: &pb.StateSnapshot{Device: &pb.DeviceInfo{Model: "HDS2202S"}}}},
	}}}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodGet, "/api/events?interval=1s&queue_capacity=64&include_screen_header=true&include_controls=false&waveform_channel=CHANNEL_2&measurement=CHANNEL_1:FREQUENCY", nil)
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusOK, recorder.Code)
	require.Equal(t, "text/event-stream", recorder.Header().Get("Content-Type"))
	require.Contains(t, recorder.Body.String(), "id: 7")
	require.Contains(t, recorder.Body.String(), `"state":{"device":{"model":"HDS2202S"}`)
	require.NotNil(t, service.SubscribeRequest)
	require.Equal(t, "1s", service.SubscribeRequest.Interval.AsDuration().String())
	require.Equal(t, uint32(64), service.SubscribeRequest.QueueCapacity)
	require.True(t, service.SubscribeRequest.IncludeScreenHeader)
	require.False(t, service.SubscribeRequest.IncludeControls)
	require.Equal(t, []pb.Channel{pb.Channel_CHANNEL_2}, service.SubscribeRequest.WaveformChannels)
	require.Len(t, service.SubscribeRequest.Measurements, 1)
	require.Equal(t, pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY, service.SubscribeRequest.Measurements[0].Kind)
}

// TestHandlerCommitsValidStartupFailuresAsSSE verifies valid EventSource requests
// keep the browser-native retry supervisor alive even when Subscribe cannot start.
//
// Example: a temporarily unavailable daemon returns HTTP 200 with a retryable stream-error event.
func TestHandlerCommitsValidStartupFailuresAsSSE(t *testing.T) {
	t.Parallel()

	tests := []struct {
		Name       string
		Service    *fakeService
		WantCode   string
		WantRetry  bool
		WantStatus int
	}{
		{
			Name: "subscribe unavailable",
			Service: &fakeService{
				SubscribeError: status.Error(codes.Unavailable, "daemon unavailable"),
			},
			WantCode:   codes.Unavailable.String(),
			WantRetry:  true,
			WantStatus: http.StatusOK,
		},
		{
			Name: "subscribe internal",
			Service: &fakeService{
				SubscribeError: status.Error(codes.Internal, "stream setup failed"),
			},
			WantCode:   codes.Internal.String(),
			WantRetry:  false,
			WantStatus: http.StatusOK,
		},
		{
			Name: "nil stream",
			Service: &fakeService{
				ReturnNilStream: true,
			},
			WantCode:   codes.Internal.String(),
			WantRetry:  false,
			WantStatus: http.StatusOK,
		},
	}
	for _, test := range tests {
		t.Run(test.Name,
			// checkStartupFailure preserves SSE framing when subscription setup fails.
			//
			// Example: Unavailable remains a retryable stream-error under HTTP 200.
			func(t *testing.T) {
				service := test.Service
				recorder := httptest.NewRecorder()
				service.InitialWriter = recorder
				mustHandler(t, service).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/api/events", nil))

				require.Equal(t, "retry: 1000\n\n", service.InitialStreamPrefix)
				require.Equal(t, test.WantStatus, recorder.Code)
				require.Equal(t, "text/event-stream", recorder.Header().Get("Content-Type"))
				require.True(t, strings.HasPrefix(recorder.Body.String(), "retry: 1000\n\n"))
				require.Contains(t, recorder.Body.String(), "event: stream-error\n")
				require.Contains(t, recorder.Body.String(), `"code":"`+test.WantCode+`"`)
				require.Contains(t, recorder.Body.String(), `"retryable":`+strconv.FormatBool(test.WantRetry))
			})
	}
}

// TestHandlerNamesSSEOneofs verifies oneof payloads use browser custom event
// names and never collide with EventSource's reserved error handler.
//
// Example: a waveform gap is surfaced as `waveform-gap` while a service error
// is surfaced as `service-error`.
func TestHandlerNamesSSEOneofs(t *testing.T) {
	t.Parallel()

	service := &fakeService{EventStream: &fakeEventStream{Events: []*pb.Event{
		{Sequence: 1, Payload: &pb.Event_State{State: &pb.StateSnapshot{}}},
		{Sequence: 2, Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: pb.Channel_CHANNEL_1, Data: []byte{0, 1}}}},
		{Sequence: 3, Payload: &pb.Event_WaveformGap{WaveformGap: &pb.WaveformGap{Channel: pb.Channel_CHANNEL_1, MissingCount: 2}}},
		{Sequence: 4, Payload: &pb.Event_Error{Error: &pb.ServiceError{Message: "degraded"}}},
	}}}
	recorder := httptest.NewRecorder()
	mustHandler(t, service).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/api/events", nil))

	body := recorder.Body.String()
	require.Contains(t, body, "event: state\n")
	require.Contains(t, body, "event: waveform\n")
	require.Contains(t, body, "event: waveform-gap\n")
	require.Contains(t, body, "event: service-error\n")
	require.NotContains(t, body, "event: error\n")
}

// TestHandlerRejectsInvalidEventPayloads verifies malformed daemon oneofs fail
// closed before protojson can turn them into an ambiguous browser event.
//
// Example: nil, typed-nil, empty, and nested-nil payloads each produce one
// terminal stream-error with an explicit non-retryable decision.
func TestHandlerRejectsInvalidEventPayloads(t *testing.T) {
	t.Parallel()

	tests := []struct {
		Name  string
		Event *pb.Event
	}{
		{Name: "nil event", Event: nil},
		{Name: "empty oneof", Event: &pb.Event{}},
		{Name: "unknown oneof", Event: &pb.Event{Payload: nil}},
		{Name: "typed nil state", Event: &pb.Event{Payload: (*pb.Event_State)(nil)}},
		{Name: "typed nil waveform", Event: &pb.Event{Payload: (*pb.Event_Waveform)(nil)}},
		{Name: "typed nil gap", Event: &pb.Event{Payload: (*pb.Event_WaveformGap)(nil)}},
		{Name: "typed nil error", Event: &pb.Event{Payload: (*pb.Event_Error)(nil)}},
		{Name: "nested nil state", Event: &pb.Event{Payload: &pb.Event_State{}}},
		{Name: "nested nil waveform", Event: &pb.Event{Payload: &pb.Event_Waveform{}}},
		{Name: "nested nil gap", Event: &pb.Event{Payload: &pb.Event_WaveformGap{}}},
		{Name: "nested nil error", Event: &pb.Event{Payload: &pb.Event_Error{}}},
	}
	for _, test := range tests {
		t.Run(test.Name,
			// rejectMalformedEvent keeps missing oneof payloads out of browser state.
			//
			// Example: a typed-nil state becomes one terminal stream-error.
			func(t *testing.T) {
				validationErr := validateEventPayload(test.Event)
				var protocolErr *ErrInvalidWebProtocol
				require.ErrorAs(t, validationErr, &protocolErr)

				recorder := httptest.NewRecorder()
				service := &fakeService{EventStream: &fakeEventStream{Events: []*pb.Event{test.Event}}}
				mustHandler(t, service).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/api/events", nil))

				body := recorder.Body.String()
				require.Equal(t, http.StatusOK, recorder.Code)
				require.Equal(t, 1, strings.Count(body, "event: stream-error\n"))
				require.Contains(t, body, `"retryable":false`)
				require.Contains(t, body, "invalid event payload")
			})
	}
}

// TestHandlerLeavesServiceErrorFalseOmitted verifies proto3 default false is
// kept omitted on valid service-error events without changing global JSON shape.
//
// Example: the browser receives a service error without a retryable field when
// the daemon's false default was not explicitly populated.
func TestHandlerLeavesServiceErrorFalseOmitted(t *testing.T) {
	t.Parallel()

	service := &fakeService{EventStream: &fakeEventStream{Events: []*pb.Event{
		{Sequence: 9, Payload: &pb.Event_Error{Error: &pb.ServiceError{Message: "terminal"}}},
	}}}
	recorder := httptest.NewRecorder()
	mustHandler(t, service).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/api/events", nil))

	body := recorder.Body.String()
	require.Contains(t, body, "event: service-error\n")
	require.Contains(t, body, `"message":"terminal"`)
	require.NotContains(t, body, `"retryable":false`)
}

// TestHandlerRejectsInvalidEventQuery verifies EventSource options do not silently fall back on typos.
//
// Example: an invalid boolean returns 400 before opening a device stream.
func TestHandlerRejectsInvalidEventQuery(t *testing.T) {
	t.Parallel()

	service := &fakeService{EventStream: &fakeEventStream{}}
	recorder := httptest.NewRecorder()
	request := httptest.NewRequest(http.MethodGet, "/api/events?include_controls=maybe", nil)
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusBadRequest, recorder.Code)
	require.Nil(t, service.SubscribeRequest)
	require.Zero(t, service.SubscribeCalls)
}

// TestHandlerRejectsInvalidEventMethodAndOrigin verifies browser guards run
// before an EventSource subscription can consume daemon resources.
//
// Example: a POST receives 405 and a cross-origin GET receives 403 without Subscribe.
func TestHandlerRejectsInvalidEventMethodAndOrigin(t *testing.T) {
	t.Parallel()

	tests := []struct {
		Name   string
		Method string
		Origin string
		Want   int
	}{
		{Name: "method", Method: http.MethodPost, Want: http.StatusMethodNotAllowed},
		{Name: "origin", Method: http.MethodGet, Origin: "https://attacker.example", Want: http.StatusForbidden},
	}
	for _, test := range tests {
		t.Run(test.Name,
			// rejectInvalidStreamRequest verifies method and origin checks precede subscription.
			//
			// Example: a cross-origin GET cannot allocate a daemon stream.
			func(t *testing.T) {
				service := &fakeService{EventStream: &fakeEventStream{}}
				recorder := httptest.NewRecorder()
				request := httptest.NewRequest(test.Method, "/api/events", nil)
				if test.Origin != "" {
					request.Header.Set("Origin", test.Origin)
				}
				mustHandler(t, service).ServeHTTP(recorder, request)

				require.Equal(t, test.Want, recorder.Code)
				require.Zero(t, service.SubscribeCalls)
			})
	}
}

// TestHandlerRejectsOversizedJSON verifies the bridge bounds browser request
// bodies before invoking a device RPC.
//
// Example: a body one byte above the one-megabyte limit receives 400 and the
// fake service observes no channel patch.
func TestHandlerRejectsOversizedJSON(t *testing.T) {
	t.Parallel()

	service := &fakeService{}
	recorder := httptest.NewRecorder()
	body := `{"channel":"CHANNEL_1","scale":"` + strings.Repeat("x", maxRequestBodyBytes) + `"}`
	request := httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(body))
	mustHandler(t, service).ServeHTTP(recorder, request)

	require.Equal(t, http.StatusBadRequest, recorder.Code)
	require.Nil(t, service.ChannelRequest)
}

// TestSubscribeRequestBounds verifies stream query limits fail before a gRPC
// Subscribe call can consume a server slot.
//
// Example: an interval below the daemon's minimum and a queue above its hard
// cap are both rejected deterministically.
func TestSubscribeRequestBounds(t *testing.T) {
	t.Parallel()

	for _, rawQuery := range []string{"interval=1ms", "interval=2h", "queue_capacity=1025", "measurement=CHANNEL_1:FREQUENCY&measurement=CHANNEL_1:FREQUENCY"} {
		request := httptest.NewRequest(http.MethodGet, "/api/events?"+rawQuery, nil)
		_, err := subscribeRequestFromURL(request)
		require.Error(t, err, "query=%s", rawQuery)
	}
}

// TestHandlerNamesTerminalStreamErrors verifies transport failures use a
// custom SSE event instead of EventSource's built-in `error` event.
//
// Example: a network failure remains visible to the custom stream-error
// listener while the browser reconnect callback remains available.
func TestHandlerNamesTerminalStreamErrors(t *testing.T) {
	t.Parallel()

	service := &fakeService{EventStream: &fakeEventStream{RecvErr: errors.New("transport closed")}}
	recorder := httptest.NewRecorder()
	mustHandler(t, service).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/api/events", nil))

	require.Equal(t, http.StatusOK, recorder.Code)
	require.Contains(t, recorder.Body.String(), "event: stream-error\n")
	require.NotContains(t, recorder.Body.String(), "event: error\n")
}

// TestTerminalSSEErrorsPreserveRetryability verifies browser terminal errors
// carry an explicit retry decision instead of relying on EventSource heuristics.
//
// Example: an unavailable daemon remains retryable while an invalid request is terminal.
func TestTerminalSSEErrorsPreserveRetryability(t *testing.T) {
	t.Parallel()

	tests := map[codes.Code]bool{
		codes.Unavailable:       true,
		codes.Aborted:           true,
		codes.DeadlineExceeded:  true,
		codes.DataLoss:          true,
		codes.ResourceExhausted: false,
		codes.Internal:          false,
		codes.InvalidArgument:   false,
	}
	for code, wantRetryable := range tests {
		var output bytes.Buffer
		require.NoError(t, writeSSEError(&output, status.Error(code, "stream failure")))
		require.Contains(t, output.String(), `"code":"`+code.String()+`"`)
		require.Contains(t, output.String(), `"retryable":`+strconv.FormatBool(wantRetryable), "code=%s", code)
	}
}

// TestPublicWebErrorsRetainTypedUnwrap verifies request and protocol errors
// remain discoverable through errors.As and errors.Is-compatible causes.
//
// Example: callers can classify a bad duration without losing the web boundary type.
func TestPublicWebErrorsRetainTypedUnwrap(t *testing.T) {
	t.Parallel()

	_, err := subscribeRequestFromURL(httptest.NewRequest(http.MethodGet, "/api/events?interval=not-a-duration", nil))
	var requestErr *ErrInvalidWebRequest
	require.ErrorAs(t, err, &requestErr)
	require.NotNil(t, requestErr.Unwrap())

	_, err = subscribeRequestFromURL(httptest.NewRequest(http.MethodGet, "/api/events?queue_capacity=invalid", nil))
	var numberErr *strconv.NumError
	require.ErrorAs(t, err, &numberErr)

	err = writeSSEEvent(io.Discard, "bad\nname", 1, nil)
	var protocolErr *ErrInvalidWebProtocol
	require.ErrorAs(t, err, &protocolErr)
}

// TestHandlerLifecycleCancellationStopsActiveSSE verifies process cancellation
// reaches an active stream and lets the HTTP handler return promptly.
//
// Example: shutdown does not wait for a browser EventSource that is blocked in Recv.
func TestHandlerLifecycleCancellationStopsActiveSSE(t *testing.T) {
	t.Parallel()

	lifecycleContext, cancelLifecycle := context.WithCancel(context.Background())
	defer cancelLifecycle()
	service := &fakeService{
		EventStream:      &fakeEventStream{WaitForContext: true},
		SubscribeStarted: make(chan struct{}),
	}
	recorder := httptest.NewRecorder()
	done := make(chan struct{})
	observability.Go(context.Background(),
		// serveCancelableRequest exposes stream completion after request cancellation.
		//
		// Example: the process BaseContext can release a handler waiting on Recv.
		func(context.Context) {
			mustHandler(t, service).ServeHTTP(recorder, httptest.NewRequest(http.MethodGet, "/api/events", nil).WithContext(lifecycleContext))
			close(done)
		})

	select {
	case <-service.SubscribeStarted:
	case <-time.After(time.Second):
		require.FailNow(t, "timed out waiting for the active SSE subscription")
	}
	cancelLifecycle()
	select {
	case <-done:
	case <-time.After(time.Second):
		require.FailNow(t, "handler failed to stop after request cancellation")
	}
	require.Equal(t, http.StatusOK, recorder.Code)
}

// TestHandlerServesHealthAndRejectsMissingRoutes verifies operational feedback is simple and deterministic.
//
// Example: a load balancer can probe /healthz while an unknown API path remains a 404.
func TestHandlerServesHealthAndRejectsMissingRoutes(t *testing.T) {
	t.Parallel()

	health := httptest.NewRecorder()
	mustHandler(t, &fakeService{}).ServeHTTP(health, httptest.NewRequest(http.MethodGet, "/healthz", nil))
	require.Equal(t, http.StatusNoContent, health.Code)

	missing := httptest.NewRecorder()
	mustHandler(t, &fakeService{}).ServeHTTP(missing, httptest.NewRequest(http.MethodGet, "/api/missing", nil))
	require.Equal(t, http.StatusNotFound, missing.Code)
}

// TestHandlerRoutesEveryServiceMethod verifies each browser API route is wired to its typed method.
//
// Example: adding a new control route cannot silently leave one existing service capability unreachable.
func TestHandlerRoutesEveryServiceMethod(t *testing.T) {
	t.Parallel()

	tests := []struct {
		Name   string
		Method string
		Path   string
		Body   string
	}{
		{Name: "device", Method: http.MethodGet, Path: "/api/device"},
		{Name: "state get", Method: http.MethodGet, Path: "/api/state"},
		{Name: "state post", Method: http.MethodPost, Path: "/api/state", Body: `{}`},
		{Name: "execute", Method: http.MethodPost, Path: "/api/execute", Body: `{"command":"*IDN?","responseMode":"RESPONSE_MODE_ASCII_LINE"}`},
		{Name: "acquisition", Method: http.MethodPost, Path: "/api/acquisition", Body: `{}`},
		{Name: "horizontal", Method: http.MethodPost, Path: "/api/horizontal", Body: `{}`},
		{Name: "trigger", Method: http.MethodPost, Path: "/api/trigger", Body: `{}`},
		{Name: "measurement", Method: http.MethodPost, Path: "/api/measurement", Body: `{}`},
		{Name: "generator", Method: http.MethodPost, Path: "/api/generator", Body: `{}`},
		{Name: "dmm", Method: http.MethodPost, Path: "/api/dmm", Body: `{}`},
		{Name: "dmm measurement", Method: http.MethodGet, Path: "/api/dmm/measurement"},
		{Name: "run", Method: http.MethodPost, Path: "/api/run"},
		{Name: "stop", Method: http.MethodPost, Path: "/api/stop"},
		{Name: "single", Method: http.MethodPost, Path: "/api/single"},
		{Name: "waveform", Method: http.MethodPost, Path: "/api/waveform", Body: `{"channel":"CHANNEL_1","screen":true}`},
	}
	for _, test := range tests {
		t.Run(test.Name,
			// exerciseRoute checks each public HTTP path reaches its typed RPC.
			//
			// Example: a generator JSON patch returns a command result.
			func(t *testing.T) {
				service := &fakeService{}
				recorder := httptest.NewRecorder()
				request := httptest.NewRequest(test.Method, test.Path, strings.NewReader(test.Body))
				mustHandler(t, service).ServeHTTP(recorder, request)
				require.Equal(t, http.StatusOK, recorder.Code)
			})
	}
}

// TestParseHelpersAcceptSupportedNamesAndRejectUnknowns verifies query parsing remains explicit.
//
// Example: both compact and protobuf enum spellings work, while unspecified values fail closed.
func TestParseHelpersAcceptSupportedNamesAndRejectUnknowns(t *testing.T) {
	t.Parallel()

	for _, raw := range []string{"1", "CHANNEL_1", "channel1"} {
		channel, err := parseChannel(raw)
		require.NoError(t, err)
		require.Equal(t, pb.Channel_CHANNEL_1, channel)
	}
	for _, raw := range []string{"2", "CHANNEL_2", "channel2"} {
		channel, err := parseChannel(raw)
		require.NoError(t, err)
		require.Equal(t, pb.Channel_CHANNEL_2, channel)
	}
	_, err := parseChannel("CHANNEL_3")
	require.Error(t, err)

	for _, raw := range []string{
		"UNKNOWN", "MAXIMUM", "MINIMUM", "PEAK_TO_PEAK", "AMPLITUDE", "AVERAGE", "PERIOD", "FREQUENCY",
	} {
		_, err := parseMeasurementKind(raw)
		require.NoError(t, err)
	}
	_, err = parseMeasurementKind("MEASUREMENT_KIND_UNSPECIFIED")
	require.Error(t, err)
}

// TestHTTPStatusCoversGRPCCategories verifies transport errors become useful browser statuses.
//
// Example: ResourceExhausted becomes 429 while an unknown service failure remains 500.
func TestHTTPStatusCoversGRPCCategories(t *testing.T) {
	t.Parallel()

	wants := map[codes.Code]int{
		codes.InvalidArgument:    http.StatusBadRequest,
		codes.Unauthenticated:    http.StatusUnauthorized,
		codes.PermissionDenied:   http.StatusForbidden,
		codes.NotFound:           http.StatusNotFound,
		codes.AlreadyExists:      http.StatusConflict,
		codes.Aborted:            http.StatusConflict,
		codes.ResourceExhausted:  http.StatusTooManyRequests,
		codes.FailedPrecondition: http.StatusPreconditionFailed,
		codes.Unimplemented:      http.StatusNotImplemented,
		codes.DeadlineExceeded:   http.StatusGatewayTimeout,
		codes.Unavailable:        http.StatusServiceUnavailable,
		codes.Internal:           http.StatusInternalServerError,
	}
	for code, want := range wants {
		require.Equal(t, want, httpStatus(code))
	}
}

// fakeService implements the browser-facing gRPC client with deterministic responses.
//
// Example: a handler test records a typed request before returning a small protobuf response.
type fakeService struct {
	GeneratorRequest    *pb.SetGeneratorRequest
	DmmRequest          *pb.SetDmmRequest
	AcquisitionRequest  *pb.SetAcquisitionRequest
	ChannelRequest      *pb.SetChannelRequest
	StateRequest        *pb.GetStateRequest
	SubscribeRequest    *pb.SubscribeRequest
	SubscribeCalls      int
	SubscribeError      error
	InitialWriter       *httptest.ResponseRecorder
	InitialStreamPrefix string
	ReturnNilStream     bool
	SubscribeStarted    chan struct{}
	EventStream         grpc.ServerStreamingClient[pb.Event]
}

// GetDeviceInfo returns stable identity data for handler tests.
//
// Example: the embedded UI test sees model `HDS2202S` without hardware.
func (service *fakeService) GetDeviceInfo(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.DeviceInfo, error) {
	return &pb.DeviceInfo{Model: "HDS2202S"}, nil
}

// GetState records the request and returns an empty state snapshot.
//
// Example: a test can verify GET and POST field-presence defaults through StateRequest.
func (service *fakeService) GetState(
	_ context.Context,
	request *pb.GetStateRequest,
	_ ...grpc.CallOption,
) (*pb.StateSnapshot, error) {
	service.StateRequest = request
	return &pb.StateSnapshot{}, nil
}

// Execute returns a small opaque response for command-route tests.
//
// Example: the browser receives base64-safe command bytes without a device.
func (service *fakeService) Execute(
	context.Context,
	*pb.ExecuteRequest,
	...grpc.CallOption,
) (*pb.ExecuteResponse, error) {
	return &pb.ExecuteResponse{Data: []byte("OK")}, nil
}

// SetChannel records a typed channel patch and reports an applied timestamp.
//
// Example: a false display value remains present in ChannelRequest.
func (service *fakeService) SetChannel(
	_ context.Context,
	request *pb.SetChannelRequest,
	_ ...grpc.CallOption,
) (*pb.CommandResult, error) {
	service.ChannelRequest = request
	return &pb.CommandResult{AppliedAt: timestamppb.Now()}, nil
}

// SetAcquisition records the decoded request and returns a successful empty result.
//
// Example: the acquisition route can be tested without modeling instrument state.
func (service *fakeService) SetAcquisition(
	_ context.Context,
	request *pb.SetAcquisitionRequest,
	_ ...grpc.CallOption,
) (*pb.CommandResult, error) {
	service.AcquisitionRequest = request
	return &pb.CommandResult{}, nil
}

// SetHorizontal returns a successful empty command result.
//
// Example: route coverage can exercise horizontal controls without hardware.
func (service *fakeService) SetHorizontal(
	context.Context,
	*pb.SetHorizontalRequest,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// SetTrigger returns a successful empty command result.
//
// Example: route coverage can exercise trigger controls without hardware.
func (service *fakeService) SetTrigger(
	context.Context,
	*pb.SetTriggerRequest,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// SetMeasurement returns a successful empty command result.
//
// Example: visibility route coverage remains independent of an instrument.
func (service *fakeService) SetMeasurement(
	context.Context,
	*pb.SetMeasurementRequest,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// SetGenerator records the decoded request and returns a successful empty result.
//
// Example: generator route coverage verifies request decoding only.
func (service *fakeService) SetGenerator(
	_ context.Context,
	request *pb.SetGeneratorRequest,
	_ ...grpc.CallOption,
) (*pb.CommandResult, error) {
	service.GeneratorRequest = request
	return &pb.CommandResult{}, nil
}

// SetDmm records the decoded request and returns a successful empty result.
//
// Example: DMM configuration route coverage does not require a live meter.
func (service *fakeService) SetDmm(
	_ context.Context,
	request *pb.SetDmmRequest,
	_ ...grpc.CallOption,
) (*pb.CommandResult, error) {
	service.DmmRequest = request
	return &pb.CommandResult{}, nil
}

// GetDmmMeasurement returns an empty reading for the refresh route.
//
// Example: the DMM endpoint can be exercised without measuring hardware.
func (service *fakeService) GetDmmMeasurement(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.DmmMeasurement, error) {
	return &pb.DmmMeasurement{}, nil
}

// Run returns a successful empty command result for acquisition lifecycle tests.
//
// Example: POST `/api/run` can be covered with the fake client.
func (service *fakeService) Run(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// Stop returns a successful empty command result for acquisition lifecycle tests.
//
// Example: POST `/api/stop` can be covered with the fake client.
func (service *fakeService) Stop(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// Single returns a successful empty command result for acquisition lifecycle tests.
//
// Example: POST `/api/single` can be covered with the fake client.
func (service *fakeService) Single(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// Auto returns a successful empty command result for the source-backed action.
//
// Example: the browser can verify POST `/api/auto` without a device connection.
func (service *fakeService) Auto(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.CommandResult, error) {
	return &pb.CommandResult{}, nil
}

// GetWaveform returns an empty waveform for capture-route tests.
//
// Example: the waveform endpoint can be tested without raw instrument bytes.
func (service *fakeService) GetWaveform(
	context.Context,
	*pb.GetWaveformRequest,
	...grpc.CallOption,
) (*pb.Waveform, error) {
	return &pb.Waveform{}, nil
}

// Subscribe records the request and returns the configured fake event stream.
//
// Example: SSE tests inject state, waveform, and service-error events through EventStream.
func (service *fakeService) Subscribe(
	ctx context.Context,
	request *pb.SubscribeRequest,
	_ ...grpc.CallOption,
) (grpc.ServerStreamingClient[pb.Event], error) {
	service.SubscribeCalls++
	service.SubscribeRequest = request
	if service.SubscribeStarted != nil {
		close(service.SubscribeStarted)
	}
	if service.InitialWriter != nil {
		service.InitialStreamPrefix = service.InitialWriter.Body.String()
	}
	if service.SubscribeError != nil {
		return nil, service.SubscribeError
	}
	if service.ReturnNilStream {
		return nil, nil
	}
	if service.EventStream == nil {
		return nil, errors.New("stream not configured")
	}
	if eventStream, ok := service.EventStream.(*fakeEventStream); ok {
		eventStream.done = ctx.Done()
	}
	return service.EventStream, nil
}

// fakeEventStream implements a finite server stream for deterministic SSE tests.
// Its private cursor and cancellation signal belong to the active receive lifetime.
//
// Example: events are returned in order and then terminate with io.EOF.
type fakeEventStream struct {
	Events         []*pb.Event
	index          int
	RecvErr        error
	done           <-chan struct{}
	WaitForContext bool
}

// Header returns no initial metadata for the fake stream.
//
// Example: SSE tests focus on event framing rather than gRPC headers.
func (stream *fakeEventStream) Header() (metadata.MD, error) { return nil, nil }

// Trailer returns no terminal metadata for the fake stream.
//
// Example: fake event assertions do not require gRPC trailers.
func (stream *fakeEventStream) Trailer() metadata.MD { return nil }

// CloseSend reports that the fake client has no send side to close.
//
// Example: handler cleanup can call the standard stream method without side effects.
func (stream *fakeEventStream) CloseSend() error { return nil }

// Context returns a background context for the fake stream.
//
// Example: stream consumers can inspect a valid context during tests.
func (stream *fakeEventStream) Context() context.Context { return context.Background() }

// SendMsg accepts no-op client messages for the fake stream interface.
//
// Example: generated gRPC plumbing can call SendMsg without a network transport.
func (stream *fakeEventStream) SendMsg(any) error { return nil }

// RecvMsg accepts no-op server messages for the fake stream interface.
//
// Example: generated gRPC plumbing can call RecvMsg without a network transport.
func (stream *fakeEventStream) RecvMsg(any) error { return nil }

// Recv returns the next configured event or the configured terminal error.
//
// Example: after the final event, Recv returns io.EOF to close an SSE test stream.
func (stream *fakeEventStream) Recv() (*pb.Event, error) {
	if stream.WaitForContext {
		<-stream.done
		return nil, context.Canceled
	}
	if stream.index >= len(stream.Events) {
		if stream.RecvErr != nil {
			return nil, stream.RecvErr
		}
		return nil, io.EOF
	}
	event := stream.Events[stream.index]
	stream.index++
	return event, nil
}

// mustHandler constructs a valid bridge for HTTP behavior tests.
//
// Example: handler setup failures abort a test before requests are made.
func mustHandler(
	t *testing.T,
	client pb.OwonServiceClient,
) http.Handler {
	t.Helper()
	handler, err := NewHandler(client)
	require.NoError(t, err)
	return handler
}
