package owonweb

import (
	"context"
	"crypto/tls"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/emptypb"
)

// observedWriter exposes explicit network failure injection and deadline history.
//
// Example: a flush failure must terminate streaming and return its cause.
type observedWriter struct {
	*httptest.ResponseRecorder
	WriteError     error
	DeadlineError  error
	DeadlineErrors map[int]error
	FlushCause     error
	Deadlines      []time.Time
	Writes         int
	Statuses       []int
}

// Write injects a peer disconnect before bytes reach the response recorder.
//
// Example: API writes propagate io.ErrClosedPipe.
func (writer *observedWriter) Write(payload []byte) (int, error) {
	writer.Writes++
	if writer.WriteError != nil {
		return 0, writer.WriteError
	}
	return writer.ResponseRecorder.Write(payload)
}

// WriteHeader records each response attempt without changing recorder semantics.
//
// Example: failed error delivery must not attempt a second HTTP response.
func (writer *observedWriter) WriteHeader(code int) {
	writer.Statuses = append(writer.Statuses, code)
	writer.ResponseRecorder.WriteHeader(code)
}

// WriteString routes string writes through the same observed network boundary.
//
// Example: the initial SSE retry frame exercises WriteError too.
func (writer *observedWriter) WriteString(payload string) (int, error) {
	return writer.Write([]byte(payload))
}

// FlushError records the transport's flush result through ResponseController.
//
// Example: a kernel write failure remains visible after buffering succeeds.
func (writer *observedWriter) FlushError() error { return writer.FlushCause }

// SetWriteDeadline records bounded write windows and explicit clearing.
//
// Example: a zero deadline follows every successful SSE flush.
func (writer *observedWriter) SetWriteDeadline(deadline time.Time) error {
	writer.Deadlines = append(writer.Deadlines, deadline)
	if err := writer.DeadlineErrors[len(writer.Deadlines)]; err != nil {
		return err
	}
	return writer.DeadlineError
}

// TestResponseErrorsAndDeadlines verifies errors survive each output boundary.
//
// Example: successful event writes alternate finite deadlines and clears.
func TestResponseErrorsAndDeadlines(t *testing.T) {
	cause := errors.New("network write failed")
	writer := &observedWriter{ResponseRecorder: httptest.NewRecorder(), WriteError: cause}
	require.ErrorIs(t, writeProto(writer, &pb.DmmMeasurement{}), cause)
	require.ErrorIs(t, writeRPCError(writer, status.Error(codes.Unavailable, "offline")), cause)
	require.ErrorIs(t, finishStream(writer, io.EOF), cause)
	handler := mustHandler(t, &fakeService{EventStream: &fakeEventStream{Events: []*pb.Event{{Payload: &pb.Event_State{State: &pb.StateSnapshot{}}}}}}).(*httpHandler)
	require.ErrorIs(t, handler.serve(writer, httptest.NewRequest(http.MethodGet, "/api/events", nil)), cause)
	writer = &observedWriter{ResponseRecorder: httptest.NewRecorder(), FlushCause: cause}
	require.ErrorIs(t, handler.serve(writer, httptest.NewRequest(http.MethodGet, "/api/events", nil)), cause)
	handler.ServeHTTP(writer, httptest.NewRequest(http.MethodGet, "/api/device", nil))
	writer = &observedWriter{ResponseRecorder: httptest.NewRecorder(), DeadlineError: cause}
	require.ErrorIs(t, writeProto(writer, &pb.DmmMeasurement{}), cause)
	require.ErrorIs(t, finishStream(writer, io.EOF), cause)
	require.ErrorIs(t, handler.serve(writer, httptest.NewRequest(http.MethodGet, "/api/events", nil)), cause)
	writer = &observedWriter{ResponseRecorder: httptest.NewRecorder()}
	require.NoError(t, handler.serve(writer, httptest.NewRequest(http.MethodGet, "/api/events", nil)))
	require.Len(t, writer.Deadlines, 4)
	require.False(t, writer.Deadlines[0].IsZero())
	require.True(t, writer.Deadlines[1].IsZero())
	require.False(t, writer.Deadlines[2].IsZero())
	require.True(t, writer.Deadlines[3].IsZero())
}

// TestConstructorAndDispatchRejectInvalidDependencies rejects invalid construction and routing.
//
// Example: a typed nil client fails before an HTTP request can panic.
func TestConstructorAndDispatchRejectInvalidDependencies(t *testing.T) {
	_, err := NewHandler(nil)
	require.Error(t, err)
	var client *fakeService
	_, err = NewHandler(client)
	require.Error(t, err)
	handler := mustHandler(t, &fakeService{}).(*httpHandler)
	_, err = handler.call(context.Background(), "/invalid", new(emptypb.Empty))
	require.Error(t, err)
	_, err = handler.call(context.Background(), "/invalid", new(pb.StateSnapshot))
	require.Error(t, err)
	for _, path := range []string{"/api/device", "/api/state", "/api/events", "/healthz"} {
		response := httptest.NewRecorder()
		handler.ServeHTTP(response, httptest.NewRequest(http.MethodDelete, path, nil))
		require.Equal(t, http.StatusMethodNotAllowed, response.Code)
		require.NotEmpty(t, response.Header().Get("Allow"))
	}
	for _, body := range []string{"", "null"} {
		response := httptest.NewRecorder()
		handler.ServeHTTP(response, httptest.NewRequest(http.MethodPost, "/api/channel", strings.NewReader(body)))
		require.Equal(t, http.StatusBadRequest, response.Code)
	}
	request := httptest.NewRequest(http.MethodGet, "https://localhost/api/device", nil)
	request.TLS = &tls.ConnectionState{}
	request.Header.Set("Origin", "https://localhost")
	require.NoError(t, sameOrigin(request))
}

// TestSubscriptionValidationMatrix covers malformed browser-controlled work budgets.
//
// Example: unknown enum values and duplicate selectors never open a stream.
func TestSubscriptionValidationMatrix(t *testing.T) {
	for _, query := range []string{"request=%7B", "request=" + strings.Repeat("x", maxSubscribeQuery+1), "interval=-1s", "queue_capacity=1025", "waveform_channel=3", "measurement=x", "measurement=3:FREQUENCY", "measurement=1:invalid"} {
		_, err := subscribeRequestFromURL(httptest.NewRequest(http.MethodGet, "/api/events?"+query, nil))
		require.Error(t, err, query)
	}
	_, err := subscribeRequestFromURL(nil)
	require.Error(t, err)
	require.Error(t, validateWebSubscribeRequest(nil))
	for _, request := range []*pb.SubscribeRequest{
		{Interval: &durationpb.Duration{Seconds: 1, Nanos: -1}},
		{Measurements: make([]*pb.MeasurementSelector, 15)},
		{Measurements: []*pb.MeasurementSelector{nil}},
		{Measurements: []*pb.MeasurementSelector{{Channel: pb.Channel_CHANNEL_UNSPECIFIED}}},
		{Measurements: []*pb.MeasurementSelector{{Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_UNSPECIFIED}}},
		{Measurements: []*pb.MeasurementSelector{{Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY}, {Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY}}},
		{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2, pb.Channel_CHANNEL_1}},
		{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_UNSPECIFIED}},
		{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_1}},
	} {
		require.Error(t, validateWebSubscribeRequest(request))
	}
	request := new(pb.SubscribeRequest)
	require.NoError(t, validateWebSubscribeRequest(request))
	require.Zero(t, request.QueueCapacity)
	require.Nil(t, request.Interval)
}

// TestWebErrorsPreserveContext verifies typed errors retain both readable detail and causes.
//
// Example: wrapping a lower-level parser error keeps errors.Is useful.
func TestWebErrorsPreserveContext(t *testing.T) {
	cause := errors.New("cause")
	var requestNil *ErrInvalidWebRequest
	var protocolNil *ErrInvalidWebProtocol
	for _, err := range []error{requestNil, protocolNil, &ErrInvalidWebRequest{}, &ErrInvalidWebProtocol{}} {
		require.Contains(t, err.Error(), "OWON web")
		require.Nil(t, errors.Unwrap(err))
	}
	for _, err := range []error{&ErrInvalidWebRequest{Cause: cause}, &ErrInvalidWebProtocol{Cause: cause}, &ErrInvalidWebRequest{Reason: "detail", Cause: cause}, &ErrInvalidWebProtocol{Reason: "detail", Cause: cause}} {
		require.ErrorIs(t, err, cause)
		require.Contains(t, err.Error(), "cause")
	}
	require.Equal(t, "stream-error", eventName(nil))
	require.Equal(t, "stream-error", eventName(new(pb.Event)))
}
