package owonweb

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonlog"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// TestStreamTerminationOwnership distinguishes expected completion from independent failures.
//
// Example: a canceled browser cannot erase an unrelated daemon error in a joined tree.
func TestStreamTerminationOwnership(t *testing.T) {
	t.Parallel()
	independent := errors.New("independent daemon failure")
	for _, test := range []struct {
		Name     string
		Cause    error
		Match    error
		CleanEOF bool
	}{
		{Name: "EOF", Cause: io.EOF, CleanEOF: true},
		{Name: "wrapped EOF", Cause: fmt.Errorf("receive: %w", io.EOF), CleanEOF: true},
		{Name: "canceled", Cause: context.Canceled, Match: context.Canceled},
		{Name: "wrapped canceled", Cause: fmt.Errorf("receive: %w", context.Canceled), Match: context.Canceled},
		{Name: "deadline", Cause: context.DeadlineExceeded, Match: context.DeadlineExceeded},
		{Name: "grpc canceled", Cause: status.Error(codes.Canceled, "RPC canceled"), Match: context.Canceled},
		{Name: "wrapped grpc deadline", Cause: fmt.Errorf("receive: %w", status.Error(codes.DeadlineExceeded, "RPC deadline")), Match: context.DeadlineExceeded},
		{Name: "independent", Cause: independent},
		{Name: "joined EOF", Cause: errors.Join(io.EOF, independent)},
		{Name: "wrapped joined cancellation", Cause: fmt.Errorf("receive: %w", errors.Join(context.Canceled, independent))},
		{Name: "joined expected only", Cause: errors.Join(context.Canceled, context.Canceled)},
		{Name: "single element join", Cause: errors.Join(context.Canceled)},
	} {
		t.Run(test.Name,
			// checkOutcomes keeps each independent cause's complete outcome matrix together.
			//
			// Example: every cancellation and output stage remains independently exercised.
			func(t *testing.T) {
				for _, ended := range []error{nil, context.Canceled, context.DeadlineExceeded} {
					for _, creation := range []bool{false, true} {
						t.Run(fmt.Sprintf("%s/%v/creation=%v", test.Name, ended, creation),
							// checkTermination exercises both generated-client entry and receive ownership.
							//
							// Example: matching cancellation is quiet, mismatched deadline remains observable.
							func(t *testing.T) {
								ctx, cancel := streamTestContext(t.Context(), ended)
								defer cancel()
								service := &fakeService{EventStream: &fakeEventStream{RecvErr: test.Cause}}
								if creation {
									service.SubscribeError = test.Cause
								}
								writer := httptest.NewRecorder()
								err := mustHandler(t, service).(*httpHandler).handleEvents(writer, httptest.NewRequest("GET", "/api/events", nil).WithContext(ctx))
								quiet := (!creation && test.CleanEOF) || (ended != nil && test.Match == ended)
								switch {
								case quiet:
									require.NoError(t, err)
									require.Equal(t, "retry: 1000\n\n", writer.Body.String())
								case ended != nil:
									require.Equal(t, test.Cause, err, "original tree belongs to handler owner")
									require.Equal(t, "retry: 1000\n\n", writer.Body.String())
								default:
									require.NoError(t, err, "successful terminal delivery handles the error")
									require.Contains(t, writer.Body.String(), "event: stream-error")
								}
							})
					}
				}
			})

	}
}

// streamTestContext creates an already-settled request lifetime without clock sleeps.
//
// Example: a past deadline deterministically models a request whose budget has expired.
func streamTestContext(
	parent context.Context,
	ended error,
) (context.Context, context.CancelFunc) {
	if ended == context.DeadlineExceeded {
		return context.WithDeadline(parent, time.Time{})
	}
	ctx, cancel := context.WithCancel(parent)
	if ended == context.Canceled {
		cancel()
	}
	return ctx, cancel
}

// canceledPayloadStream returns one payload concurrently with ending its request lifetime.
//
// Example: a malformed event must still be validated when cancellation becomes visible.
type canceledPayloadStream struct {
	fakeEventStream
	Cancel context.CancelFunc
	Event  *pb.Event
}

// Recv ends the caller before returning its configured successful receive.
//
// Example: nil payload with nil receive error represents a protocol defect, not EOF.
func (stream *canceledPayloadStream) Recv() (*pb.Event, error) {
	stream.Cancel()
	return stream.Event, nil
}

// TestCanceledReceiveStillValidatesPayload retains defects detected at the receive boundary.
//
// Example: valid data may be abandoned after cancellation, but invalid data reaches the owner.
func TestCanceledReceiveStillValidatesPayload(t *testing.T) {
	t.Parallel()
	for _, event := range []*pb.Event{nil, {}, {Payload: &pb.Event_State{State: &pb.StateSnapshot{}}}} {
		ctx, cancel := context.WithCancel(t.Context())
		service := &fakeService{EventStream: &canceledPayloadStream{Cancel: cancel, Event: event}}
		writer := httptest.NewRecorder()
		err := mustHandler(t, service).(*httpHandler).handleEvents(writer, httptest.NewRequest("GET", "/api/events", nil).WithContext(ctx))
		cancel()
		if event != nil && event.GetState() != nil {
			require.NoError(t, err)
		} else {
			var protocolErr *ErrInvalidWebProtocol
			require.ErrorAs(t, err, &protocolErr)
		}
		require.Equal(t, "retry: 1000\n\n", writer.Body.String())
	}
}

// TestTerminalDeliveryRetainsBothCauses checks every terminal output boundary.
//
// Example: clearing a flushed frame's deadline cannot erase its original device failure.
func TestTerminalDeliveryRetainsBothCauses(t *testing.T) {
	t.Parallel()
	cause := &ErrInvalidWebProtocol{Reason: "device event"}
	secondary := &ErrInvalidWebRequest{Reason: "output failed"}
	for _, stage := range []string{"deadline", "write", "flush", "clear", "success"} {
		t.Run(stage,
			// checkDelivery verifies one output boundary independently of the others.
			//
			// Example: a deadline failure does not prevent exercising flush failure.
			func(t *testing.T) {
				writer := &observedWriter{ResponseRecorder: httptest.NewRecorder()}
				switch stage {
				case "deadline":
					writer.DeadlineError = secondary
				case "write":
					writer.WriteError = secondary
				case "flush":
					writer.FlushCause = secondary
				case "clear":
					writer.DeadlineErrors = map[int]error{2: secondary}
				}
				err := finishStream(writer, cause)
				if stage == "success" {
					require.NoError(t, err)
					require.Contains(t, writer.Body.String(), "device event")
					return
				}
				require.ErrorIs(t, err, cause, stage)
				require.ErrorIs(t, err, secondary, stage)
				var protocolErr *ErrInvalidWebProtocol
				var outputErr *ErrInvalidWebRequest
				require.ErrorAs(t, err, &protocolErr)
				require.ErrorAs(t, err, &outputErr)
				require.Contains(t, err.Error(), "terminal SSE")
			})
	}
}

// TestStreamOwnerLogsIndependentFailure uses the request logger rather than global output.
//
// Example: an unrelated receive failure survives browser cancellation in one owner diagnostic.
func TestStreamOwnerLogsIndependentFailure(t *testing.T) {
	t.Parallel()
	var output bytes.Buffer
	ctx, err := owonlog.WithContext(t.Context(), owonlog.Config{Level: logger.LevelInfo, Service: "owonweb"}, &output)
	require.NoError(t, err)
	ctx, cancel := context.WithCancel(ctx)
	cancel()
	service := &fakeService{EventStream: &fakeEventStream{RecvErr: errors.Join(context.Canceled, errors.New("independent diagnostic"))}}
	mustHandler(t, service).ServeHTTP(httptest.NewRecorder(), httptest.NewRequest("GET", "/api/events", nil).WithContext(ctx))
	require.Contains(t, output.String(), "serve HTTP request")
	require.Contains(t, output.String(), "http_method=GET")
	require.Contains(t, output.String(), "http_path=/api/events")
	require.Contains(t, output.String(), "independent diagnostic")
}
