package owonweb

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owoncontrol"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonserver"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// streamTransportBackend models one silent identity read followed by a healthy device.
//
// Example: the actual transport must time out, recover, and permit a later subscription.
type streamTransportBackend struct {
	Silent     atomic.Bool
	Recoveries atomic.Int32
}

// Exchange provides controlled bytes only; production code owns all protocol layers.
//
// Example: a silent exchange ends only when its operation context expires.
func (backend *streamTransportBackend) Exchange(
	ctx context.Context,
	command owonprotocol.Command,
) ([]byte, error) {
	if backend.Silent.Swap(false) {
		<-ctx.Done()
		return nil, ctx.Err()
	}
	if command.Text == "*IDN?" {
		return []byte("OWON,HDS2202S,controlled,V2.6.0"), nil
	}
	return nil, fmt.Errorf("unexpected integration command %q", command.Text)
}

// ReopenAndValidate records the recovery boundary without touching native hardware.
//
// Example: the next operation after the silent read revalidates the expected serial.
func (backend *streamTransportBackend) ReopenAndValidate(
	_ context.Context,
	serial owonmodel.SerialNumber,
) error {
	if serial != "controlled" {
		return fmt.Errorf("unexpected serial %q", serial)
	}
	backend.Recoveries.Add(1)
	return nil
}

// Close releases this resource-free controlled backend.
//
// Example: the fixture does not open a USB device.
func (*streamTransportBackend) Close(context.Context) error { return nil }

// TestProductionStreamOperationTimeout traverses TCP gRPC and HTTP without faking RPC handlers.
//
// Example: device silence emits both retryable service metadata and terminal DeadlineExceeded SSE.
func TestProductionStreamOperationTimeout(t *testing.T) {
	t.Parallel()
	backend := new(streamTransportBackend)
	backend.Silent.Store(true)
	transport, err := owonsession.New(backend, owonsession.Config{ExpectedSerial: "controlled", OperationTimeout: 40 * time.Millisecond})
	require.NoError(t, err)
	t.Cleanup(
		// closeTransport checks native-resource ownership after server shutdown.
		//
		// Example: no outstanding fixture operation survives test completion.
		func() { require.NoError(t, transport.Close()) })
	instrument, err := owoncontrol.New(transport, owonmodel.DeviceIdentity{})
	require.NoError(t, err)
	service, err := owonserver.NewServer(instrument)
	require.NoError(t, err)
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	server := grpc.NewServer(owonserver.GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(server, service)
	served := make(chan error, 1)
	observability.Go(t.Context(), grpcServeRunner{Server: server, Listener: listener, Errors: served}.Run)
	t.Cleanup(
		// joinServer waits for the TCP serving loop to terminate.
		//
		// Example: stopped-server completion is expected, independent failures are not.
		func() {
			server.Stop()
			err := <-served
			if !errors.Is(err, grpc.ErrServerStopped) {
				require.NoError(t, err)
			}
		})
	options := append(owonclient.GRPCClientDialOptions(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	connection, err := grpc.NewClient(listener.Addr().String(), options...)
	require.NoError(t, err)
	t.Cleanup(
		// closeClient releases the generated client's TCP connection.
		//
		// Example: the client outlives all HTTP requests but not the test.
		func() { require.NoError(t, connection.Close()) })
	web := httptest.NewServer(mustHandler(t, pb.NewOwonServiceClient(connection)))
	t.Cleanup(web.Close)
	client := &http.Client{Timeout: 5 * time.Second}
	response, err := client.Get(web.URL + "/api/events?include_controls=false&interval=200ms")
	require.NoError(t, err)
	body, err := io.ReadAll(response.Body)
	require.NoError(t, response.Body.Close())
	require.NoError(t, err, "stream must end itself; test timeout is not a cancellation rescue")
	require.Equal(t, http.StatusOK, response.StatusCode)
	require.Contains(t, string(body), "event: service-error")
	require.Contains(t, string(body), "SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE")
	require.Contains(t, string(body), `"retryable":true`)
	require.Contains(t, string(body), "event: stream-error")
	require.Contains(t, string(body), `"code":"DeadlineExceeded"`)
	t.Logf("silent production stream terminated: %s", body)
	response, err = client.Get(web.URL + "/api/device")
	require.NoError(t, err)
	body, err = io.ReadAll(response.Body)
	require.NoError(t, response.Body.Close())
	require.NoError(t, err)
	require.Equal(t, http.StatusOK, response.StatusCode)
	require.Contains(t, string(body), "HDS2202S")
	require.EqualValues(t, 1, backend.Recoveries.Load())
	response, err = client.Get(web.URL + "/api/events?include_controls=false&interval=200ms")
	require.NoError(t, err)
	t.Cleanup(
		// closeStream releases the active response even when a later assertion fails.
		//
		// Example: early test failure still cancels the production subscription.
		func() { require.NoError(t, response.Body.Close()) })
	scanner := bufio.NewScanner(response.Body)
	states := 0
	for states < 3 && scanner.Scan() {
		line := scanner.Text()
		require.False(t, strings.Contains(line, "stream-error"), line)
		if line == "event: state" {
			states++
		}
	}
	require.NoError(t, scanner.Err())
	require.Equal(t, 3, states, "healthy stream survives idle intervals longer than each operation budget")
	t.Log("recovered once; three healthy state events span idle intervals beyond the operation deadline")
}
