package owonweb

import (
	"net/http/httptest"
	"net/url"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
)

// TestWebSubscriptionValidationIsPure checks domain delegation without applying defaults.
//
// Example: an omitted interval stays nil when only validation is requested.
func TestWebSubscriptionValidationIsPure(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		Name    string
		Request *pb.SubscribeRequest
		Invalid bool
		WebOnly bool
		Domain  bool
	}{
		{Name: "nil", Invalid: true},
		{Name: "empty", Request: &pb.SubscribeRequest{}},
		{Name: "zero interval", Request: &pb.SubscribeRequest{Interval: durationpb.New(0)}, Invalid: true},
		{Name: "negative", Request: &pb.SubscribeRequest{Interval: durationpb.New(-time.Second)}, Invalid: true},
		{Name: "malformed", Request: &pb.SubscribeRequest{Interval: &durationpb.Duration{Seconds: 1, Nanos: -1}}, Invalid: true},
		{Name: "duration overflow", Request: &pb.SubscribeRequest{Interval: &durationpb.Duration{Seconds: 315576000001}}, Invalid: true},
		{Name: "too fast", Request: &pb.SubscribeRequest{Interval: durationpb.New(19 * time.Millisecond)}, Invalid: true},
		{Name: "minimum", Request: &pb.SubscribeRequest{Interval: durationpb.New(20 * time.Millisecond)}},
		{Name: "one hour", Request: &pb.SubscribeRequest{Interval: durationpb.New(time.Hour)}},
		{Name: "above one hour", Request: &pb.SubscribeRequest{Interval: durationpb.New(time.Hour + time.Second)}, Invalid: true, WebOnly: true},
		{Name: "capacity one", Request: &pb.SubscribeRequest{QueueCapacity: 1}},
		{Name: "capacity maximum", Request: &pb.SubscribeRequest{QueueCapacity: 1024}},
		{Name: "capacity overflow", Request: &pb.SubscribeRequest{QueueCapacity: 1025}, Invalid: true},
		{Name: "nil selector", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{nil}}, Invalid: true, Domain: true},
		{Name: "unknown measurement", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{{Channel: pb.Channel_CHANNEL_1, Kind: 99}}}, Invalid: true, Domain: true},
		{Name: "unknown measurement channel", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{{Channel: 99, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY}}}, Invalid: true, Domain: true},
		{Name: "all measurements", Request: &pb.SubscribeRequest{Measurements: allWebMeasurementSelectors()}},
		{Name: "fifteenth measurement", Request: &pb.SubscribeRequest{Measurements: append(allWebMeasurementSelectors(), &pb.MeasurementSelector{Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY})}, Invalid: true, Domain: true},
		{Name: "one waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1}}},
		{Name: "two waveforms", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2}}},
		{Name: "unknown waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{99}}, Invalid: true, Domain: true},
		{Name: "duplicate waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_1}}, Invalid: true},
		{Name: "third waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2, pb.Channel_CHANNEL_1}}, Invalid: true},
	} {
		t.Run(test.Name,
			// checkPureValidation compares both classification and unchanged protobuf content.
			//
			// Example: rejected malformed durations retain the core typed cause.
			func(t *testing.T) {
				before := proto.Clone(test.Request)
				err := validateWebSubscribeRequest(test.Request)
				require.True(t, proto.Equal(before, test.Request), "validation must not normalize")
				if !test.Invalid {
					require.NoError(t, err)
					return
				}
				var webErr *ErrInvalidWebRequest
				require.ErrorAs(t, err, &webErr)
				if !test.WebOnly {
					if test.Domain {
						var domainErr *owonmodel.ErrInvalidRequest
						require.ErrorAs(t, err, &domainErr)
					} else {
						var wireErr *owonrpc.ErrInvalidInput
						require.ErrorAs(t, err, &wireErr)
					}
				}
			})
	}
}

// allWebMeasurementSelectors enumerates the complete supported two-channel selection.
//
// Example: all fourteen selectors pass the shared native service rule.
func allWebMeasurementSelectors() []*pb.MeasurementSelector {
	var selectors []*pb.MeasurementSelector
	for _, channel := range []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2} {
		for kind := pb.MeasurementKind_MEASUREMENT_KIND_MAXIMUM; kind <= pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY; kind++ {
			selectors = append(selectors, &pb.MeasurementSelector{Channel: channel, Kind: kind})
		}
	}
	return selectors
}

// TestWebSubscribePrecedenceAndEarlyRejection preserves JSON reset and explicit scalar overrides.
//
// Example: JSON's omitted booleans stay false rather than being normalized back to URL defaults.
func TestWebSubscribePrecedenceAndEarlyRejection(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		JSON     string
		Query    string
		Invalid  bool
		Interval time.Duration
		Capacity uint32
		Controls bool
	}{
		{Interval: time.Second, Capacity: 128, Controls: true},
		{JSON: `{}`, Interval: time.Second, Capacity: 128},
		{JSON: `{"interval":null,"queueCapacity":0}`, Interval: time.Second, Capacity: 128},
		{JSON: `{"interval":"0s"}`, Invalid: true},
		{JSON: `{"interval":"2s","queueCapacity":3,"includeControls":true}`, Query: "interval=20ms&queue_capacity=1&include_controls=false", Interval: 20 * time.Millisecond, Capacity: 1, Controls: true},
		{JSON: `{"measurements":[null]}`, Invalid: true},
		{JSON: `{"unknown":true}`, Invalid: true},
		{JSON: `null`, Invalid: true},
		{JSON: `{"waveformChannels":[99]}`, Invalid: true},
		{Query: "interval=0s", Invalid: true},
		{Query: "interval=2h", Invalid: true},
		{Query: "queue_capacity=1025", Invalid: true},
		{Query: "queue_capacity=4294967296", Invalid: true},
		{Query: "measurement=1:FREQUENCY&measurement=1:FREQUENCY", Invalid: true},
	} {
		t.Run(test.JSON+"/"+test.Query,
			// checkURL exercises the public handler before any generated-client subscription.
			//
			// Example: invalid numeric enums cannot consume an RPC stream slot.
			func(t *testing.T) {
				query := test.Query
				if test.JSON != "" {
					query += "&request=" + url.QueryEscape(test.JSON)
				}
				service := &fakeService{EventStream: &fakeEventStream{}}
				writer := httptest.NewRecorder()
				mustHandler(t, service).ServeHTTP(writer, httptest.NewRequest("GET", "/api/events?"+query, nil))
				if test.Invalid {
					require.Equal(t, 400, writer.Code)
					require.Zero(t, service.SubscribeCalls)
					return
				}
				require.Equal(t, 200, writer.Code)
				require.Equal(t, 1, service.SubscribeCalls)
				require.Equal(t, test.Interval, service.SubscribeRequest.Interval.AsDuration())
				require.Equal(t, test.Capacity, service.SubscribeRequest.QueueCapacity)
				require.Equal(t, test.Controls, service.SubscribeRequest.IncludeControls)
			})
	}
}
