package owonweb

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestTypedPatchPresence preserves optional zeros, false values and finite-choice names.
//
// Example: an explicit zero symmetry is different from an omitted symmetry field.
func TestTypedPatchPresence(t *testing.T) {
	t.Parallel()
	service := new(fakeService)
	handler := mustHandler(t, service)
	for _, test := range []struct {
		Path string
		Body string
	}{
		{Path: "/api/generator", Body: `{"symmetryPercent":0,"load":"GENERATOR_LOAD_OFF","output":false,"offsetVolts":0.25,"dutyPercent":12.5}`},
		{Path: "/api/dmm", Body: `{"function":"DMM_FUNCTION_VOLTAGE","currentType":"DMM_CURRENT_TYPE_AC","range":"DMM_RANGE_MV","relative":false}`},
		{Path: "/api/acquisition", Body: `{"memoryDepth":"ACQUISITION_MEMORY_DEPTH_4K"}`},
	} {
		response := httptest.NewRecorder()
		handler.ServeHTTP(response, httptest.NewRequest(http.MethodPost, test.Path, strings.NewReader(test.Body)))
		require.Equal(t, http.StatusOK, response.Code, response.Body.String())
	}
	require.NotNil(t, service.GeneratorRequest.SymmetryPercent)
	require.Zero(t, service.GeneratorRequest.GetSymmetryPercent())
	require.Equal(t, pb.GeneratorLoad_GENERATOR_LOAD_OFF, service.GeneratorRequest.GetLoad())
	require.NotNil(t, service.GeneratorRequest.Output)
	require.False(t, service.GeneratorRequest.GetOutput())
	require.Nil(t, service.GeneratorRequest.FrequencyHz)
	require.Equal(t, 0.25, service.GeneratorRequest.GetOffsetVolts())
	require.Equal(t, 12.5, service.GeneratorRequest.GetDutyPercent())
	require.Equal(t, pb.DmmRange_DMM_RANGE_MV, service.DmmRequest.GetRange())
	require.NotNil(t, service.DmmRequest.Relative)
	require.False(t, service.DmmRequest.GetRelative())
	require.Nil(t, service.DmmRequest.AutoRange)
	require.Equal(t, pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_4K, service.AcquisitionRequest.GetMemoryDepth())

	response := httptest.NewRecorder()
	handler.ServeHTTP(response, httptest.NewRequest(http.MethodPost, "/api/generator", strings.NewReader(`{"load":"GENERATOR_LOAD_ON"}`)))
	require.Equal(t, http.StatusOK, response.Code)
	require.Nil(t, service.GeneratorRequest.SymmetryPercent)
	require.Nil(t, service.GeneratorRequest.Output)
	require.Equal(t, pb.GeneratorLoad_GENERATOR_LOAD_ON, service.GeneratorRequest.GetLoad())
}

// TestTypedPatchRejectsInvalidJSON rejects invalid wire representations before RPC dispatch.
//
// Example: fractional symmetry and free-form load tokens cannot reach the instrument.
func TestTypedPatchRejectsInvalidJSON(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		Path string
		Body string
	}{
		{Path: "/api/generator", Body: `{"symmetryPercent":50.5,"output":true}`},
		{Path: "/api/generator", Body: `{"symmetryPercent":"2147483648"}`},
		{Path: "/api/generator", Body: `{"load":"ON"}`},
		{Path: "/api/dmm", Body: `{"range":"mV"}`},
		{Path: "/api/acquisition", Body: `{"memoryDepth":"4K"}`},
	} {
		service := new(fakeService)
		response := httptest.NewRecorder()
		mustHandler(t, service).ServeHTTP(response, httptest.NewRequest(http.MethodPost, test.Path, strings.NewReader(test.Body)))
		require.Equal(t, http.StatusBadRequest, response.Code, test.Body)
		require.Nil(t, service.GeneratorRequest)
		require.Nil(t, service.DmmRequest)
		require.Nil(t, service.AcquisitionRequest)
	}
}

// TestObservedDomainsRemainDistinct preserves raw header text and fractional query values.
//
// Example: state depth does not acquire the restricted write selector's domain.
func TestObservedDomainsRemainDistinct(t *testing.T) {
	t.Parallel()
	response := httptest.NewRecorder()
	err := writeProto(response, &pb.StateSnapshot{
		Acquisition: &pb.AcquisitionState{MemoryDepth: "unverified raw depth"},
		Generator:   &pb.GeneratorState{SymmetryPercent: 50.25, Load: pb.GeneratorLoad_GENERATOR_LOAD_ON},
		Dmm:         &pb.DmmState{Range: pb.DmmRange_DMM_RANGE_V},
	})
	require.NoError(t, err)
	require.JSONEq(t, `{"acquisition":{"memoryDepth":"unverified raw depth"},"generator":{"symmetryPercent":50.25,"load":"GENERATOR_LOAD_ON"},"dmm":{"range":"DMM_RANGE_V"}}`, response.Body.String())
}
