package owonweb

import (
	"bytes"
	"context"
	"fmt"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonlog"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// unaryErrorService exposes RPC failure or a genuinely unencodable protobuf response.
//
// Example: invalid UTF-8 exercises production ProtoJSON serialization, not an injected marshaler.
type unaryErrorService struct {
	fakeService
	Cause     error
	Malformed bool
}

// GetDeviceInfo returns the configured outcome at the normal generated-client boundary.
//
// Example: a failed identity RPC and a malformed success both use the sole HTTP error owner.
func (service *unaryErrorService) GetDeviceInfo(
	context.Context,
	*emptypb.Empty,
	...grpc.CallOption,
) (*pb.DeviceInfo, error) {
	if service.Malformed {
		return &pb.DeviceInfo{Model: string([]byte{0xff})}, nil
	}
	return nil, service.Cause
}

// TestUnaryErrorDeliveryOwnership retains causes while making only one response attempt.
//
// Example: a disconnected error response preserves the RPC and write errors for its logger.
func TestUnaryErrorDeliveryOwnership(t *testing.T) {
	t.Parallel()
	for _, stage := range []string{"success", "deadline", "write"} {
		t.Run(stage,
			// checkDelivery verifies both causal identities and response cardinality.
			//
			// Example: a deadline failure occurs before any status or body is written.
			func(t *testing.T) {
				cause := &ErrInvalidWebProtocol{Reason: "original RPC failure"}
				secondary := &ErrInvalidWebRequest{Reason: "secondary output failure"}
				writer := unaryFailureWriter(stage, secondary)
				err := writeRPCError(writer, cause)
				if stage == "success" {
					require.NoError(t, err)
					require.Contains(t, writer.Body.String(), cause.Error())
				} else {
					require.ErrorIs(t, err, cause)
					require.ErrorIs(t, err, secondary)
					var original *ErrInvalidWebProtocol
					var output *ErrInvalidWebRequest
					require.ErrorAs(t, err, &original)
					require.ErrorAs(t, err, &output)
					require.Contains(t, err.Error(), "deliver RPC error")
				}
				expectedWrites := 1
				if stage == "deadline" {
					expectedWrites = 0
				}
				require.Equal(t, expectedWrites, writer.Writes)
				require.Len(t, writer.Statuses, expectedWrites)
			})
	}
}

// unaryFailureWriter configures one selected network output boundary.
//
// Example: success leaves both deadline and write operations usable.
func unaryFailureWriter(
	stage string,
	cause error,
) *observedWriter {
	writer := &observedWriter{ResponseRecorder: httptest.NewRecorder()}
	switch stage {
	case "deadline":
		writer.DeadlineError = cause
	case "write":
		writer.WriteError = cause
	}
	return writer
}

// TestUnaryOwnerLogsOnce covers real serialization failures and contextual handler logging.
//
// Example: successful error reporting is quiet; failed reporting logs original and secondary once.
func TestUnaryOwnerLogsOnce(t *testing.T) {
	t.Parallel()
	for _, malformed := range []bool{false, true} {
		t.Run(fmt.Sprintf("malformed=%v", malformed),
			// checkOutcomes keeps each independent cause's complete outcome matrix together.
			//
			// Example: every cancellation and output stage remains independently exercised.
			func(t *testing.T) {
				for _, stage := range []string{"success", "deadline", "write"} {
					var output bytes.Buffer
					ctx, err := owonlog.WithContext(t.Context(), owonlog.Config{Level: logger.LevelInfo, Service: "owonweb"}, &output)
					require.NoError(t, err)
					service := &unaryErrorService{Cause: &ErrInvalidWebProtocol{Reason: "original RPC failure"}, Malformed: malformed}
					writer := unaryFailureWriter(stage, &ErrInvalidWebRequest{Reason: "secondary output failure"})
					mustHandler(t, service).ServeHTTP(writer, httptest.NewRequest("GET", "/api/device", nil).WithContext(ctx))
					original := "original RPC failure"
					if malformed {
						original = "invalid UTF-8"
					}
					if stage == "success" {
						require.Empty(t, output.String())
						require.Equal(t, 500, writer.Code)
						require.Contains(t, writer.Body.String(), original)
						continue
					}
					require.Contains(t, output.String(), original)
					require.Contains(t, output.String(), "secondary output failure")
					require.Equal(t, 1, strings.Count(output.String(), "serve HTTP request"))
					require.Contains(t, output.String(), "http_method=GET")
					require.Contains(t, output.String(), "http_path=/api/device")
					require.LessOrEqual(t, writer.Writes, 1)
					require.LessOrEqual(t, len(writer.Statuses), 1)
				}
			})

	}
}
