package owonserver

import (
	"testing"

	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// TestValidateWaveformWireSizeRejectsAggregateOversize verifies device frames fit public RPC limits.
//
// Example: a header and payload at their independent sixteen-MiB limits cannot form one event.
func TestValidateWaveformWireSizeRejectsAggregateOversize(t *testing.T) {
	t.Parallel()

	waveform := &pb.Waveform{
		Data:             make([]byte, owonprotocol.DefaultMaximumResponseBytes),
		ScreenHeaderJson: make([]byte, owonprotocol.DefaultMaximumResponseBytes),
		CapturedAt:       timestamppb.Now(),
	}
	requireErrorType[*ErrWaveformTooLarge](t, validateWaveformWireSize(&pb.Event{Timestamp: waveform.CapturedAt, Payload: &pb.Event_Waveform{Waveform: waveform}}))
}
