package owonserver

import (
	"context"
	"net"
	"path/filepath"
	"reflect"
	"sync/atomic"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// TestServerCountsRejectNegativeConfiguration verifies local counts use signed domain validation.
//
// Example: a negative active-subscription limit fails before a channel allocation.
func TestServerCountsRejectNegativeConfiguration(t *testing.T) {
	t.Parallel()
	for _, name := range []string{"MaxActiveRPCs", "MaxActiveSubscriptions", "MaxSubscriptionPollWork"} {
		config := ServerConfig{}
		field := reflect.ValueOf(&config).Elem().FieldByName(name)
		require.Equal(t, reflect.Int, field.Kind(), name)
		field.SetInt(-1)
		server, err := NewServerWithConfig(newTestInstrument(t, &scriptedBackend{}), config)
		require.Nil(t, server)
		requireErrorType[*ErrInvalidConfig](t, err)
	}
}

// TestDmmPreflightMatchesExecution verifies pure preparation and the setter share one complete validator.
//
// Example: a late unsupported auto-range field prevents an earlier valid relative write.
func TestDmmPreflightMatchesExecution(t *testing.T) {
	t.Parallel()
	for _, testCase := range []struct {
		JSON     string
		Commands []string
	}{
		{`{}`, nil},
		{`{"function":"DMM_FUNCTION_VOLTAGE"}`, nil},
		{`{"currentType":"DMM_CURRENT_TYPE_DC"}`, nil},
		{`{"function":"DMM_FUNCTION_RESISTANCE","currentType":"DMM_CURRENT_TYPE_DC"}`, nil},
		{`{"relative":true,"autoRange":false}`, nil},
		{`{"relative":true,"range":999}`, nil},
		{`{"relative":true,"range":"DMM_RANGE_UNSPECIFIED"}`, nil},
		{`{"function":999}`, nil},
		{`{"function":"DMM_FUNCTION_CURRENT","currentType":999}`, nil},
		{`{"function":"DMM_FUNCTION_VOLTAGE","currentType":"DMM_CURRENT_TYPE_DC","relative":false,"range":"DMM_RANGE_MV","autoRange":true}`, []string{":DMM:CONFIGURE:VOLTAGE DC", ":DMM:REL OFF", ":DMM:RANGE mV", ":DMM:AUTO ON"}},
		{`{"range":"DMM_RANGE_ON"}`, []string{":DMM:RANGE ON"}},
		{`{"range":"DMM_RANGE_V"}`, []string{":DMM:RANGE V"}},
		{`{"function":"DMM_FUNCTION_RESISTANCE"}`, []string{":DMM:CONFIGURE RESISTANCE"}},
	} {
		var request pb.SetDmmRequest
		require.NoError(t, protojson.Unmarshal([]byte(testCase.JSON), &request))
		before := proto.Clone(&request)
		_, validationErr := owonscpi.CompileDMM(owonrpc.DMMPatchFromProto(&request))
		require.True(t, proto.Equal(before, &request), "pure validation mutated %s", testCase.JSON)
		backend := &scriptedBackend{}
		executionErr := newTestInstrument(t, backend).SetDMM(t.Context(), owonrpc.DMMPatchFromProto(&request))
		if testCase.Commands == nil {
			require.Error(t, validationErr, testCase.JSON)
			require.EqualError(t, executionErr, validationErr.Error())
			require.Empty(t, backend.Commands)
			continue
		}
		require.NoError(t, validationErr, testCase.JSON)
		require.NoError(t, executionErr)
		require.Equal(t, testCase.Commands, backend.Commands)
	}
	_, err := owonscpi.CompileDMM(nil)
	requireErrorType[*owonmodel.ErrInvalidRequest](t, err)
}

// TestControlDomainsThroughRPC verifies optional write domains across production serialization and handlers.
//
// Example: zero symmetry emits an integer while an invalid trailing load prevents every command in its patch.
func TestControlDomainsThroughRPC(t *testing.T) {
	for _, testCase := range []struct {
		JSON     string
		Commands []string
	}{
		{`{"symmetryPercent":0}`, []string{":FUNCTION:SYMMETRY 0"}},
		{`{"symmetryPercent":100}`, []string{":FUNCTION:SYMMETRY 100"}},
		{`{"symmetryPercent":-1}`, nil},
		{`{"symmetryPercent":101}`, nil},
		{`{"symmetryPercent":50,"load":999}`, nil},
		{`{"symmetryPercent":50,"load":"GENERATOR_LOAD_UNSPECIFIED"}`, nil},
		{`{"load":"GENERATOR_LOAD_ON"}`, []string{":FUNCTION:LOAD ON"}},
		{`{"load":"GENERATOR_LOAD_OFF"}`, []string{":FUNCTION:LOAD OFF"}},
		{`{"dutyPercent":12.5,"offsetVolts":-0.25,"output":false}`, []string{":FUNCTION:OFFSET -0.25", ":FUNCTION:DTYCYCLE 12.5", ":CHANNEL OFF"}},
	} {
		backend := &scriptedBackend{}
		client := newUnixControlClient(t, backend)
		var request pb.SetGeneratorRequest
		require.NoError(t, protojson.Unmarshal([]byte(testCase.JSON), &request))
		result, err := client.SetGenerator(t.Context(), &request)
		if testCase.Commands == nil {
			require.Nil(t, result)
			require.Equal(t, codes.InvalidArgument, status.Code(err), testCase.JSON)
			require.Empty(t, backend.Commands)
			continue
		}
		require.NoError(t, err)
		require.NotNil(t, result.AppliedAt)
		require.Equal(t, testCase.Commands, backend.Commands)
	}
	for _, value := range []pb.AcquisitionMemoryDepth{pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_UNSPECIFIED, pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_4K, pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_8K, 999} {
		backend := &scriptedBackend{}
		result, err := newUnixControlClient(t, backend).SetAcquisition(t.Context(), &pb.SetAcquisitionRequest{MemoryDepth: &value})
		switch value {
		case pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_4K:
			require.NoError(t, err)
			require.NotNil(t, result.AppliedAt)
			require.Equal(t, []string{":ACQUIRE:DEPMEM 4K"}, backend.Commands)
		case pb.AcquisitionMemoryDepth_ACQUISITION_MEMORY_DEPTH_8K:
			require.NoError(t, err)
			require.NotNil(t, result.AppliedAt)
			require.Equal(t, []string{":ACQUIRE:DEPMEM 8K"}, backend.Commands)
		default:
			require.Nil(t, result)
			require.Equal(t, codes.InvalidArgument, status.Code(err))
			require.Empty(t, backend.Commands)
		}
	}
	for _, value := range []pb.DmmRange{pb.DmmRange_DMM_RANGE_UNSPECIFIED, pb.DmmRange_DMM_RANGE_ON, pb.DmmRange_DMM_RANGE_MV, pb.DmmRange_DMM_RANGE_V, 999} {
		backend := &scriptedBackend{}
		result, err := newUnixControlClient(t, backend).SetDMM(t.Context(), &pb.SetDmmRequest{Range: &value})
		commands := map[pb.DmmRange]string{pb.DmmRange_DMM_RANGE_ON: "ON", pb.DmmRange_DMM_RANGE_MV: "mV", pb.DmmRange_DMM_RANGE_V: "V"}
		command, valid := commands[value]
		if !valid {
			require.Nil(t, result)
			require.Equal(t, codes.InvalidArgument, status.Code(err))
			require.Empty(t, backend.Commands)
			continue
		}
		require.NoError(t, err)
		require.NotNil(t, result.AppliedAt)
		require.Equal(t, []string{":DMM:RANGE " + command}, backend.Commands)
	}
}

// newUnixControlClient connects production service and client implementations through a kernel socket.
//
// Example: domain tests exercise actual protobuf RPCs with a controlled command-recording backend.
func newUnixControlClient(
	t *testing.T,
	backend owonsession.Backend,
) *owonclient.Client {
	t.Helper()
	path := filepath.Join(t.TempDir(), "instrument")
	serveUnixControlFixture(t, path, backend)
	endpoint := owonrpc.Endpoint{Network: owonrpc.NetworkUnix, Address: path}
	target, err := endpoint.Target()
	require.NoError(t, err)
	connection, err := grpc.NewClient(target, grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	t.Cleanup(
		// closeConnection releases the client before stopping its server.
		//
		// Example: a completed domain case leaves no RPC connection behind.
		func() { require.NoError(t, connection.Close()) })
	client, err := owonclient.NewClient(connection)
	require.NoError(t, err)
	return client
}

// serveUnixControlFixture registers production service logic on a real Unix socket.
//
// Example: endpoint tests exercise the native gRPC resolver rather than a recording-only dialer.
func serveUnixControlFixture(
	t *testing.T,
	path string,
	backend owonsession.Backend,
) *countedUnixListener {
	t.Helper()
	listener, err := net.Listen("unix", path)
	require.NoError(t, err)
	counted := &countedUnixListener{Listener: listener}
	server := grpc.NewServer(GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(server, requireNewServer(t, newTestInstrument(t, backend)))
	done := make(chan error, 1)
	observability.Go(t.Context(),
		// serveFixture owns the accept loop until the test's cleanup joins it.
		//
		// Example: no socket worker survives its temporary directory.
		func(context.Context) { done <- server.Serve(counted) })
	t.Cleanup(
		// stopFixture joins gRPC after it closes the owned listener.
		//
		// Example: temporary socket removal happens after all serving work ends.
		func() {
			server.Stop()
			require.NoError(t, <-done)
		})
	return counted
}

// countedUnixListener observes accepted connections without changing normal socket behavior.
//
// Example: a truncated-filename decoy must accept zero connections during a successful intended RPC.
type countedUnixListener struct {
	net.Listener
	Accepted atomic.Int32
}

// Accept records successful kernel socket connections before returning them to gRPC.
//
// Example: the intended listener counts the public client's sole connection.
func (listener *countedUnixListener) Accept() (net.Conn, error) {
	connection, err := listener.Listener.Accept()
	if err == nil {
		listener.Accepted.Add(1)
	}
	return connection, err
}
