package owonserver

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"testing/synctest"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonweb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// TestGeneratorBuiltinsHTTPToController exercises browser-shaped requests through native command compilation.
// No physical device is involved; command delivery to this fixture is not electrical verification.
//
// Example: a named builtin crosses HTTP JSON and TCP protobuf before producing its exact SCPI token.
func TestGeneratorBuiltinsHTTPToController(t *testing.T) {
	backend := &scriptedBackend{Responses: map[string][]byte{
		":CHANNEL?": []byte("OFF"),
	}}
	service := requireNewServer(t, newTestInstrument(t, backend))
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	server := grpc.NewServer(GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(server, service)
	done := make(chan error, 1)
	observability.Go(t.Context(),
		// serveGeneratorFixture transports requests to the native controller without hardware.
		//
		// Example: the cleanup joins this goroutine before releasing the backend.
		func(context.Context) { done <- server.Serve(listener) })
	t.Cleanup(
		// stopGeneratorFixture joins handlers before instrument cleanup.
		//
		// Example: no network server survives an assertion failure.
		func() { server.Stop(); require.NoError(t, <-done) })
	connection, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	t.Cleanup(
		// closeGeneratorClient releases the protobuf transport.
		//
		// Example: the client cannot reconnect after this test exits.
		func() { require.NoError(t, connection.Close()) })
	handler, err := owonweb.NewHandler(pb.NewOwonServiceClient(connection))
	require.NoError(t, err)
	httpServer := httptest.NewServer(handler)
	t.Cleanup(httpServer.Close)
	for _, builtin := range []struct{ Enum, Token string }{
		{"AMP_ALT", "AmpALT"}, {"ATT_ALT", "AttALT"}, {"STAIR_DOWN", "StairDn"}, {"STAIR_UP_DOWN", "StairUD"},
		{"STAIR_UP", "StairUp"}, {"BESSEL_J", "Besselj"}, {"BESSEL_Y", "Bessely"}, {"SINC", "Sinc"},
	} {
		backend.Commands = nil
		backend.Responses[":FUNCTION?"] = []byte(builtin.Token)
		body := fmt.Sprintf(`{"waveform":"GENERATOR_WAVEFORM_%s","frequencyHz":5000000}`, builtin.Enum)
		requireGeneratorHTTP(t, httpServer, body, http.StatusOK)
		require.Equal(t, []string{
			":CHANNEL?", ":CHANNEL?", ":FUNCTION " + builtin.Token, ":FUNCTION?", ":FUNCTION?",
			":FUNCTION:FREQUENCY 5e+06", ":CHANNEL OFF", ":CHANNEL?", ":CHANNEL?",
		}, backend.Commands)
		backend.Commands = nil
		body = fmt.Sprintf(`{"waveform":"GENERATOR_WAVEFORM_%s","periodSeconds":0.0000002,"output":false}`, builtin.Enum)
		requireGeneratorHTTP(t, httpServer, body, http.StatusOK)
		require.Equal(t, []string{
			":FUNCTION " + builtin.Token, ":FUNCTION?", ":FUNCTION?",
			":FUNCTION:PERIOD 2e-07", ":CHANNEL OFF", ":CHANNEL?", ":CHANNEL?",
		}, backend.Commands)
	}
	for _, test := range []struct {
		Body   string
		Status int
	}{
		{`{"periodSeconds":1}`, http.StatusBadRequest},
		{`{"waveform":"GENERATOR_WAVEFORM_SINC","frequencyHz":2,"periodSeconds":0.5}`, http.StatusBadRequest},
		{`{"waveform":"GENERATOR_WAVEFORM_SINC","periodSeconds":0.0000001}`, http.StatusBadRequest},
		{`{"waveform":"GENERATOR_WAVEFORM_SINC","dutyPercent":50}`, http.StatusNotImplemented},
		{`{"waveform":"GENERATOR_WAVEFORM_SINC","frequencyHz":1000,"load":999,"output":true}`, http.StatusBadRequest},
		{`{"waveform":999,"output":true}`, http.StatusBadRequest},
	} {
		backend.Commands = nil
		requireGeneratorHTTP(t, httpServer, test.Body, test.Status)
		require.Empty(t, backend.Commands, test.Body)
	}

	backend.Commands = nil
	backend.ExchangeErrors = []error{nil, nil, nil, nil, nil, errors.New("restoration exchange lost")}
	backend.Responses[":FUNCTION?"] = []byte("SINe")
	partialResponse, err := httpServer.Client().Post(
		httpServer.URL+"/api/generator",
		"application/json",
		strings.NewReader(`{"waveform":"GENERATOR_WAVEFORM_SINE"}`),
	)
	require.NoError(t, err)
	partialBody, err := io.ReadAll(partialResponse.Body)
	require.NoError(t, err)
	require.NoError(t, partialResponse.Body.Close())
	require.Equal(t, http.StatusServiceUnavailable, partialResponse.StatusCode, string(partialBody))
	normalizedPartialBody := strings.ReplaceAll(string(partialBody), " ", "")
	require.Contains(t, normalizedPartialBody, `"code":"Unavailable"`)
	require.Contains(t, normalizedPartialBody, `"delivery":"GENERATOR_DELIVERY_PARTIAL_OR_UNKNOWN"`)
	require.Contains(t, normalizedPartialBody, `"compensation":{"requested":false,"status":"GENERATOR_OUTPUT_COMPENSATION_FAILED"}`)
	require.Contains(t, normalizedPartialBody, `"completedWrites":[":FUNCTIONSINE"]`)
	require.NotContains(t, normalizedPartialBody, `"appliedAt"`)
}

// TestObservedGeneratorRPCResultPreservesLogicalPresence verifies the additive observed RPC result contract.
// No physical device is involved; the fixture returns only logical FUNCTION?/CHANNEL? tokens.
//
// Example: explicit output=false is retained while a patch without waveform context leaves requested absent.
func TestObservedGeneratorRPCResultPreservesLogicalPresence(t *testing.T) {
	backend := &scriptedBackend{Responses: map[string][]byte{
		":FUNCTION?": []byte("SINe"),
		":CHANNEL?":  []byte("OFF"),
	}}
	client := newControlClient(t, backend)
	observe, output := true, false
	waveform := pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINE
	result, err := client.SetGenerator(t.Context(), &pb.SetGeneratorRequest{
		Waveform: &waveform,
		Output:   &output,
		Observe:  &observe,
	})
	require.NoError(t, err)
	require.NotNil(t, result.Generator)
	require.Equal(t, pb.GeneratorDeliveryStatus_GENERATOR_DELIVERY_TRANSPORT_COMPLETE_READBACK_VERIFIED, result.Generator.Delivery)
	require.Equal(t, pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINE, result.Generator.Observation.Context.GetRequested())
	require.Equal(t, pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINE, result.Generator.Observation.Context.GetObserved())
	require.NotNil(t, result.Generator.Observation.Output.Value)
	require.False(t, result.Generator.Observation.Output.GetValue())
	require.Equal(t, pb.GeneratorOutputCompensationStatus_GENERATOR_OUTPUT_COMPENSATION_VERIFIED, result.Generator.Compensation.Status)

	backend.Commands = nil
	result, err = client.SetGenerator(t.Context(), &pb.SetGeneratorRequest{Output: &output, Observe: &observe})
	require.NoError(t, err)
	require.NotNil(t, result.Generator)
	require.Nil(t, result.Generator.Observation.Context.Requested)
	require.Nil(t, result.Generator.Observation.Output.Value)
	require.Equal(t, []string{":CHANNEL OFF"}, backend.Commands)

	backend.Commands = nil
	backend.ExchangeErrors = []error{nil, nil, nil, nil, nil, errors.New("restoration exchange lost")}
	result, err = client.SetGenerator(t.Context(), &pb.SetGeneratorRequest{Waveform: &waveform, Observe: &observe})
	require.Error(t, err)
	require.Nil(t, result)
	require.Equal(t, codes.Unavailable, status.Code(err))
	var partial *pb.GeneratorOperationResult
	for _, detail := range status.Convert(err).Details() {
		if candidate, ok := detail.(*pb.GeneratorOperationResult); ok {
			partial = candidate
			break
		}
	}
	require.NotNil(t, partial)
	require.Equal(t, pb.GeneratorDeliveryStatus_GENERATOR_DELIVERY_PARTIAL_OR_UNKNOWN, partial.Delivery)
	require.Equal(t, []string{":CHANNEL?", ":CHANNEL?", ":FUNCTION SINE", ":FUNCTION?", ":FUNCTION?", ":CHANNEL OFF"}, backend.Commands)
	require.Equal(t, []string{":FUNCTION SINE"}, partial.CompletedWrites)
	require.Equal(t, pb.GeneratorOutputCompensationStatus_GENERATOR_OUTPUT_COMPENSATION_FAILED, partial.Compensation.Status)
	require.NotNil(t, partial.Compensation.Requested)
	require.False(t, partial.Compensation.GetRequested())
}

// TestObservedGeneratorRPCClassifiesHealthyNonconvergence verifies semantic status mapping and details.
//
// Example: valid but nonmatching FUNCTION? replies return FailedPrecondition while preserving a partial result.
func TestObservedGeneratorRPCClassifiesHealthyNonconvergence(t *testing.T) {
	synctest.Test(t, func(t *testing.T) {
		backend := &scriptedBackend{Responses: map[string][]byte{
			":CHANNEL?":  []byte("OFF"),
			":FUNCTION?": []byte("SQUARE"),
		}}
		service := requireNewServer(t, newTestInstrument(t, backend))
		observe := true
		waveform := pb.GeneratorWaveform_GENERATOR_WAVEFORM_SINE

		response, err := service.SetGenerator(t.Context(), &pb.SetGeneratorRequest{Waveform: &waveform, Observe: &observe})
		require.Error(t, err)
		require.NotNil(t, response)
		require.Equal(t, codes.FailedPrecondition, status.Code(err))
		require.NotNil(t, response.Generator)
		require.Equal(t, pb.GeneratorDeliveryStatus_GENERATOR_DELIVERY_PARTIAL_OR_UNKNOWN, response.Generator.Delivery)
		var detail *pb.GeneratorOperationResult
		for _, candidate := range status.Convert(err).Details() {
			if value, ok := candidate.(*pb.GeneratorOperationResult); ok {
				detail = value
				break
			}
		}
		require.NotNil(t, detail)
		require.True(t, proto.Equal(response.Generator, detail))
	})
}

// requireGeneratorHTTP sends one real HTTP patch and checks its completion status.
//
// Example: validation failures return their public HTTP status before any backend write.
func requireGeneratorHTTP(
	t *testing.T,
	server *httptest.Server,
	body string,
	wantStatus int,
) {
	t.Helper()
	response, err := server.Client().Post(server.URL+"/api/generator", "application/json", strings.NewReader(body))
	require.NoError(t, err)
	result, err := io.ReadAll(response.Body)
	require.NoError(t, err)
	require.NoError(t, response.Body.Close())
	require.Equal(t, wantStatus, response.StatusCode, string(result))
}
