package owonserver

import (
	"context"
	"errors"
	"testing"

	"github.com/stretchr/testify/require"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
)

// requireServerUnavailable verifies a handler refuses uninitialized service state before device work.
//
// Example: every control returns FailedPrecondition rather than dereferencing a nil instrument.
func requireServerUnavailable[Request any, Response any](
	t *testing.T,
	call func(
		context.Context,
		*Request,
	) (Response, error),
	want codes.Code,
) {
	t.Helper()
	response, err := call(t.Context(), new(Request))
	require.Nil(t, response)
	require.Equal(t, want, status.Code(err))
}

// TestServerRefusesUnavailableAndBusyStates verifies all RPCs honor admission and instrument ownership.
//
// Example: a saturated server returns ResourceExhausted before parsing even an empty request.
func TestServerRefusesUnavailableAndBusyStates(t *testing.T) {
	t.Parallel()
	backend := &scriptedBackend{}
	busy := requireNewServer(t, newTestInstrument(t, backend))
	for range cap(busy.rpcAdmission) {
		require.NoError(t, busy.acquireRPC())
	}
	for _, testCase := range []struct {
		Server *Server
		Want   codes.Code
	}{
		{nil, codes.FailedPrecondition},
		{&Server{}, codes.FailedPrecondition},
		{&Server{rpcAdmission: make(chan struct{}, 1)}, codes.FailedPrecondition},
		{busy, codes.ResourceExhausted},
	} {
		server := testCase.Server
		requireServerUnavailable(t, server.GetDeviceInfo, testCase.Want)
		requireServerUnavailable(t, server.GetState, testCase.Want)
		requireServerUnavailable(t, server.Execute, testCase.Want)
		requireServerUnavailable(t, server.SetChannel, testCase.Want)
		requireServerUnavailable(t, server.SetAcquisition, testCase.Want)
		requireServerUnavailable(t, server.SetHorizontal, testCase.Want)
		requireServerUnavailable(t, server.SetTrigger, testCase.Want)
		requireServerUnavailable(t, server.SetMeasurement, testCase.Want)
		requireServerUnavailable(t, server.SetGenerator, testCase.Want)
		requireServerUnavailable(t, server.SetDmm, testCase.Want)
		requireServerUnavailable(t, server.GetDmmMeasurement, testCase.Want)
		requireServerUnavailable(t, server.GetWaveform, testCase.Want)
		requireServerUnavailable(t, server.Run, testCase.Want)
		requireServerUnavailable(t, server.Stop, testCase.Want)
		requireServerUnavailable(t, server.Single, testCase.Want)
	}
	for range cap(busy.rpcAdmission) {
		busy.releaseRPC()
	}
	result, err := busy.Run(t.Context(), new(emptypb.Empty))
	require.NoError(t, err)
	require.NotNil(t, result.AppliedAt)
	require.Equal(t, []string{":RUN"}, backend.Commands)
}

// TestServerReportsDeviceFailures verifies failed writes never return application timestamps or get replayed.
//
// Example: Run, Stop and Single each return Unavailable after one ambiguous transport write.
func TestServerReportsDeviceFailures(t *testing.T) {
	t.Parallel()
	for _, action := range []string{"run", "stop", "single", "execute"} {
		backend := &scriptedBackend{ExchangeErrors: []error{errors.New("USB disconnected")}}
		server := requireNewServer(t, newTestInstrument(t, backend))
		var err error
		switch action {
		case "run":
			_, err = server.Run(t.Context(), nil)
		case "stop":
			_, err = server.Stop(t.Context(), nil)
		case "single":
			_, err = server.Single(t.Context(), nil)
		case "execute":
			_, err = server.Execute(t.Context(), &pb.ExecuteRequest{Command: ":RUN", ResponseMode: pb.ResponseMode_RESPONSE_MODE_NONE})
		}
		require.Equal(t, codes.Unavailable, status.Code(err))
		require.Len(t, backend.Commands, 1)
		require.Zero(t, backend.ReopenCalls)
	}
	server := requireNewServer(t, newTestInstrument(t, &scriptedBackend{}))
	requireServerUnavailable(t, server.SetHorizontal, codes.InvalidArgument)
	requireServerUnavailable(t, server.SetTrigger, codes.InvalidArgument)
	requireServerUnavailable(t, server.SetMeasurement, codes.InvalidArgument)
	requireServerUnavailable(t, server.SetDmm, codes.InvalidArgument)
	// An unspecified channel is intrinsically invalid before non-screen support is considered.
	requireServerUnavailable(t, server.GetWaveform, codes.InvalidArgument)
	_, err := server.Execute(t.Context(), nil)
	require.Equal(t, codes.InvalidArgument, status.Code(err))
	_, err = server.Execute(t.Context(), &pb.ExecuteRequest{Command: "bad;command", ResponseMode: pb.ResponseMode_RESPONSE_MODE_ASCII_LINE})
	require.Equal(t, codes.InvalidArgument, status.Code(err))
}
