package owonserver

import (
	"context"
	"errors"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
)

// identityInstrument isolates RPC policy from command compilation and native I/O.
//
// Example: embedded uncalled methods panic if a device-info handler unexpectedly invokes them.
type identityInstrument struct {
	Instrument
	Calls int
	Error error
}

// DeviceInfo supplies one typed observation for the RPC conversion boundary.
//
// Example: the serial must reach the client without a native controller.
func (instrument *identityInstrument) DeviceInfo(context.Context) (*owonmodel.DeviceInfo, error) {
	instrument.Calls++
	if instrument.Error != nil {
		return nil, instrument.Error
	}
	return &owonmodel.DeviceInfo{Serial: "interface-serial"}, nil
}

// TestInterfaceErrorsPreserveRPCPolicy exercises unary transport and stream classification.
//
// Example: corrupt dialect payloads wrapping invalid model values remain DataLoss over TCP.
func TestInterfaceErrorsPreserveRPCPolicy(t *testing.T) {
	invalid := &owonmodel.ErrInvalidRequest{Reason: "invalid value"}
	corrupt := &owonscpi.ErrMalformedResponse{Reason: "invalid observation", Cause: invalid}
	for _, test := range []struct {
		Error     error
		Code      codes.Code
		Category  pb.ServiceErrorCategory
		Retryable bool
	}{
		{invalid, codes.InvalidArgument, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_INVALID_REQUEST, false},
		{new(owonscpi.ErrInvalidSetting), codes.InvalidArgument, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_INVALID_REQUEST, false},
		{new(ErrInvalidInput), codes.InvalidArgument, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_INVALID_REQUEST, false},
		{new(owonrpc.ErrInvalidInput), codes.InvalidArgument, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_INVALID_REQUEST, false},
		{new(owonscpi.ErrUnsupportedControl), codes.Unimplemented, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_UNSUPPORTED, false},
		{corrupt, codes.DataLoss, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, true},
		{new(owonprotocol.ErrMalformedResponse), codes.DataLoss, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, true},
		{new(owonprotocol.ErrSurplusResponse), codes.DataLoss, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, true},
		{new(ErrWaveformTooLarge), codes.DataLoss, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, true},
		{new(ErrUnavailable), codes.Unavailable, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE, true},
		{errors.Join(corrupt, context.Canceled), codes.Canceled, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE, true},
		{errors.Join(corrupt, context.DeadlineExceeded), codes.DeadlineExceeded, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE, true},
	} {
		server, err := NewServer(&identityInstrument{Error: test.Error})
		require.NoError(t, err)
		client := newSubscribeTCPClient(t, server)
		result, err := client.DeviceInfo(t.Context())
		require.Nil(t, result)
		require.Equal(t, test.Code, status.Code(err), "%T", test.Error)
		serviceError := subscriptionServiceError(test.Error)
		require.Equal(t, test.Category, serviceError.Category, "%T", test.Error)
		require.Equal(t, test.Retryable, serviceError.Retryable, "%T", test.Error)
	}
}

// TestServerAcceptsConsumerInstrument exercises an independent interface implementation.
//
// Example: typed nil implementations fail construction while an available source serves identity.
func TestServerAcceptsConsumerInstrument(t *testing.T) {
	var absent *identityInstrument
	for _, instrument := range []Instrument{nil, absent} {
		server, err := NewServer(instrument)
		require.Nil(t, server)
		require.ErrorAs(t, err, new(*ErrInvalidConfig))
	}
	instrument := new(identityInstrument)
	server, err := NewServer(instrument)
	require.NoError(t, err)
	result, err := server.GetDeviceInfo(t.Context(), new(emptypb.Empty))
	require.NoError(t, err)
	require.Equal(t, "interface-serial", result.Serial)
	require.Equal(t, 1, instrument.Calls)
}
