package owonserver

import (
	"bytes"
	"context"
	"io"
	"net"
	"sync"
	"testing"

	"github.com/facebookincubator/go-belt"
	"github.com/facebookincubator/go-belt/tool/logger"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonlog"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/stats"
	"google.golang.org/protobuf/types/known/emptypb"
)

// synchronizedLogOutput permits assertions while transport shutdown finishes asynchronously.
//
// Example: a connection-end message cannot race a test reading emitted records.
type synchronizedLogOutput struct {
	mu     sync.Mutex
	buffer bytes.Buffer
}

// Write appends one complete logging write under the buffer lock.
//
// Example: unary and streaming callbacks share one safe output sink.
func (output *synchronizedLogOutput) Write(value []byte) (int, error) {
	output.mu.Lock()
	defer output.mu.Unlock()
	return output.buffer.Write(value)
}

// String snapshots records without racing transport callbacks.
//
// Example: assertions inspect method fields after RPC completion.
func (output *synchronizedLogOutput) String() string {
	output.mu.Lock()
	defer output.mu.Unlock()
	return output.buffer.String()
}

// loggingService observes the actual server contexts supplied by gRPC.
//
// Example: unary and streaming handlers both emit through the configured connection logger.
type loggingService struct {
	pb.UnimplementedOwonServiceServer
}

// GetDeviceInfo emits a marker from a real unary handler.
//
// Example: the marker must contain the configured serial and RPC method.
func (service *loggingService) GetDeviceInfo(
	ctx context.Context,
	_ *emptypb.Empty,
) (*pb.DeviceInfo, error) {
	logger.Debugf(ctx, "unary context marker")
	return &pb.DeviceInfo{Serial: "fixture"}, nil
}

// Subscribe emits a marker from the actual stream context and sends one event.
//
// Example: no handwritten context wrapper is needed for the configured identity to survive.
func (service *loggingService) Subscribe(
	_ *pb.SubscribeRequest,
	stream grpc.ServerStreamingServer[pb.Event],
) error {
	logger.Debugf(stream.Context(), "stream context marker")
	return stream.Send(&pb.Event{Sequence: 1})
}

// TestRPCLoggingRealUnaryAndStream verifies structured context through a real TCP listener.
//
// Example: both RPC shapes emit configured service, serial, and method fields without payload logs.
func TestRPCLoggingRealUnaryAndStream(t *testing.T) {
	output := &synchronizedLogOutput{}
	logging, err := NewRPCLogging(owonlog.Config{Level: logger.LevelTrace, Service: "owond"}, output, "fixture")
	require.NoError(t, err)
	ctx := logging.TagConn(belt.WithField(t.Context(), "existing", "retained"), &stats.ConnTagInfo{})
	ctx = logging.TagRPC(ctx, &stats.RPCTagInfo{FullMethodName: "/test/local"})
	logger.Debugf(ctx, "local field marker")
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	server := grpc.NewServer(grpc.StatsHandler(logging))
	pb.RegisterOwonServiceServer(server, &loggingService{})
	done := make(chan error, 1)
	observability.Go(t.Context(),
		// serveLoggingFixture runs the production gRPC transport until explicit shutdown.
		//
		// Example: no daemon or hardware device participates in this logging proof.
		func(context.Context) { done <- server.Serve(listener) })
	t.Cleanup(server.Stop)
	connection, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	t.Cleanup(
		// closeLoggingFixture releases the client's connection after assertions.
		//
		// Example: failed assertions still release their kernel socket.
		func() { require.NoError(t, connection.Close()) })
	client := pb.NewOwonServiceClient(connection)
	_, err = client.GetDeviceInfo(t.Context(), &emptypb.Empty{})
	require.NoError(t, err)
	stream, err := client.Subscribe(t.Context(), &pb.SubscribeRequest{})
	require.NoError(t, err)
	event, err := stream.Recv()
	require.NoError(t, err)
	require.Equal(t, uint64(1), event.Sequence)
	_, err = stream.Recv()
	require.ErrorIs(t, err, io.EOF)
	server.GracefulStop()
	require.NoError(t, <-done)
	text := output.String()
	for _, expected := range []string{"service=owond", "serial=fixture", "existing=retained", "unary context marker", "stream context marker", "rpc_method=" + pb.OwonService_GetDeviceInfo_FullMethodName, "rpc_method=" + pb.OwonService_Subscribe_FullMethodName, "RPC started", "RPC ended"} {
		require.Contains(t, text, expected)
	}
	require.NotContains(t, text, "payload=")
	_, err = NewRPCLogging(owonlog.Config{}, output, "fixture")
	require.Error(t, err)
}
