package owonserver

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
	"google.golang.org/protobuf/encoding/protojson"
)

// TestOffsetJSONCommands verifies exact integer spelling, presence, bounds and no writes after invalid preflight.
//
// Example: a horizontal value beyond JavaScript's safe integer range reaches SCPI unchanged.
func TestOffsetJSONCommands(t *testing.T) {
	t.Parallel()
	for _, testCase := range []struct {
		Payload string
		Command string
	}{
		{`{"offsetDivisions":"9007199254740993"}`, ":HORIZONTAL:OFFSET 9007199254740993"},
		{`{"offsetDivisions":"-9223372036854775808"}`, ":HORIZONTAL:OFFSET -9223372036854775808"},
		{`{"offsetDivisions":"9223372036854775807"}`, ":HORIZONTAL:OFFSET 9223372036854775807"},
		{`{"offsetDivisions":0}`, ":HORIZONTAL:OFFSET 0"},
		{`{"scale":"20us"}`, ":HORIZONTAL:SCALE 20us"},
	} {
		backend := &scriptedBackend{}
		var request pb.SetHorizontalRequest
		require.NoError(t, protojson.Unmarshal([]byte(testCase.Payload), &request))
		require.NoError(t, newTestInstrument(t, backend).SetHorizontal(t.Context(), owonrpc.HorizontalPatchFromProto(&request)))
		require.Equal(t, []string{testCase.Command}, backend.Commands)
	}
	for _, offset := range []int64{-201, -200, -1, 0, 1, 200, 201} {
		backend := &scriptedBackend{}
		var request pb.SetChannelRequest
		require.NoError(t, protojson.Unmarshal([]byte(fmt.Sprintf(`{"channel":"CHANNEL_1","display":false,"probeAttenuation":10,"scale":"100mV","offsetDivisions":"%d"}`, offset)), &request))
		err := newTestInstrument(t, backend).SetChannel(t.Context(), owonrpc.ChannelPatchFromProto(&request))
		if offset < -200 || offset > 200 {
			requireErrorType[*owonscpi.ErrInvalidSetting](t, err)
			require.Empty(t, backend.Commands)
			continue
		}
		require.NoError(t, err)
		require.Equal(t, []string{":CH1:DISPLAY OFF", ":CH1:PROBE 10X", ":CH1:SCALE 100mV", fmt.Sprintf(":CH1:OFFSET %d", offset)}, backend.Commands)
	}
}

// TestScreenOffsetsRemainRawAndOptional verifies state never invents write units or missing offsets.
//
// Example: -78 remains a raw screen value while an omitted OFFSET stays absent in JSON.
func TestScreenOffsetsRemainRawAndOptional(t *testing.T) {
	t.Parallel()
	for _, offset := range []string{"", `,"OFFSET":null`, `,"OFFSET":0`, `,"OFFSET":-78`, `,"OFFSET":-49`, `,"OFFSET":1.25`} {
		rawHeader := []byte(`{"TIMEBASE":{"SCALE":"20us"` + replaceOffsetName(offset) + `},"SAMPLE":{"TYPE":"SAMPle"},"CHANNEL":[{"NAME":"CH1","DISPLAY":"ON","COUPLING":"DC","PROBE":"10X","SCALE":"1.00V"` + offset + `}],"Trig":{"Mode":"SINGLE","Type":"EDGE","Items":{"Channel":"CH1","Level":"1V","Edge":"RISE","Coupling":"DC","Sweep":"AUTO"}}}`)
		backend := &scriptedBackend{Responses: map[string][]byte{"*IDN?": []byte("OWON,HDS2202S,25061855,V2.6.0"), ":DATA:WAVE:SCREEN:HEAD?": rawHeader, ":DMM:RANGE?": []byte("mV")}}
		snapshot, err := newControlClient(t, backend).State(t.Context(), &pb.GetStateRequest{IncludeControls: true})
		require.NoError(t, err)
		require.Equal(t, []string{"*IDN?", ":DATA:WAVE:SCREEN:HEAD?", ":DMM:RANGE?"}, backend.Commands)
		encoded, err := protojson.Marshal(snapshot)
		require.NoError(t, err)
		var state map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(encoded, &state))
		var decodedChannels []map[string]json.RawMessage
		var decodedHorizontal map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(state["channels"], &decodedChannels))
		require.NoError(t, json.Unmarshal(state["horizontal"], &decodedHorizontal))
		for _, object := range []map[string]json.RawMessage{decodedChannels[0], decodedHorizontal} {
			requireRawScreenOffset(t, object, offset)
		}
	}
}

// requireRawScreenOffset checks raw numeric presence without conflating state and write domains.
//
// Example: absent and null header offsets do not manufacture a zero-valued state field.
func requireRawScreenOffset(
	t *testing.T,
	object map[string]json.RawMessage,
	offset string,
) {
	t.Helper()
	require.NotContains(t, object, "offsetDivisions")
	require.NotContains(t, object, "offset")
	if offset == "" || offset == `,"OFFSET":null` {
		require.NotContains(t, object, "screenHeaderOffset")
		return
	}
	var raw map[string]float64
	require.NoError(t, json.Unmarshal([]byte("{"+offset[1:]+"}"), &raw))
	var observed float64
	require.NoError(t, json.Unmarshal(object["screenHeaderOffset"], &observed))
	require.Equal(t, raw["OFFSET"], observed)
}

// replaceOffsetName gives horizontal fixtures the same raw value and presence as channel fixtures.
//
// Example: a null OFFSET becomes a null HOFFSET without interpreting its numeric units.
func replaceOffsetName(offset string) string {
	if offset == "" {
		return ""
	}
	return `,"HOFFSET"` + offset[len(`,"OFFSET"`):]
}
