package owonserver

import (
	"context"
	"errors"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// TestSubscriptionTerminalReleasesStagingReference verifies successful publication transfers staging ownership.
//
// Example: delivered payloads leave staging immediately; failed admission retains them only until close.
func TestSubscriptionTerminalReleasesStagingReference(t *testing.T) {
	t.Parallel()
	for _, limit := range []int{0, 1024} {
		queue, err := newSubscriptionQueueWithBudget(1, newSubscriptionBudget(limit))
		require.NoError(t, err)
		event := &pb.Event{Payload: &pb.Event_Error{Error: &pb.ServiceError{Message: "terminal"}}}
		queue.finish(event, nil)
		result := queue.nextReady()
		switch limit {
		case 0:
			require.Same(t, event, queue.terminalEvent)
			require.Nil(t, result.Event)
			requireErrorType[*ErrSubscriptionResourceExhausted](t, result.Err)
		default:
			require.Nil(t, queue.terminalEvent)
			require.Same(t, event, result.Event)
			require.NoError(t, result.Err)
		}
		require.Zero(t, queue.bytes)
		require.Nil(t, queue.events)
		queue.close()
		require.Nil(t, queue.terminalEvent)
	}
}

// TestSubscriptionQueueReclaimsStorage verifies released charges correspond to released references.
//
// Example: draining two waveforms clears their old slots and detaches the empty backing array.
func TestSubscriptionQueueReclaimsStorage(t *testing.T) {
	t.Parallel()
	budget := newSubscriptionBudget(1024)
	queue, err := newSubscriptionQueueWithBudget(2, budget)
	require.NoError(t, err)
	first := &pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: pb.Channel_CHANNEL_1, Data: []byte{1}}}}
	second := &pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: pb.Channel_CHANNEL_2, Data: []byte{2}}}}
	require.NoError(t, queue.enqueueWaveform(first))
	require.NoError(t, queue.enqueueWaveform(second))
	storage := queue.events
	result, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Same(t, first, result)
	require.Nil(t, storage[0].event)
	require.Positive(t, budget.used.Load())
	result, err = queue.next(context.Background())
	require.NoError(t, err)
	require.Same(t, second, result)
	require.Nil(t, storage[1].event)
	require.Nil(t, queue.events)
	require.Zero(t, budget.used.Load())
}

// TestSubscriptionStateReplacementReclaimsTail verifies failed replacement cannot retain uncharged data.
//
// Example: an oversized new state removes the old state but leaves a later waveform ordered and charged.
func TestSubscriptionStateReplacementReclaimsTail(t *testing.T) {
	t.Parallel()
	budget := newSubscriptionBudget(1024)
	queue, err := newSubscriptionQueueWithBudget(2, budget)
	require.NoError(t, err)
	require.NoError(t, queue.enqueueState(&pb.Event{Payload: &pb.Event_State{State: new(pb.StateSnapshot)}}))
	waveform := &pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: pb.Channel_CHANNEL_1}}}
	require.NoError(t, queue.enqueueWaveform(waveform))
	storage := queue.events
	err = queue.enqueueState(&pb.Event{Payload: &pb.Event_State{State: &pb.StateSnapshot{ScreenHeaderJson: make([]byte, 2048)}}})
	require.Error(t, err)
	require.Nil(t, storage[1].event)
	require.Len(t, queue.events, 1)
	require.Same(t, waveform, queue.events[0].event)
	require.Equal(t, int64(queue.events[0].size), budget.used.Load())
}

// TestProtocolClassificationOverridesNestedValidation verifies malformed device values remain protocol faults.
//
// Example: a finite-value validator nested under a malformed response maps to DataLoss and retryable PROTOCOL.
func TestProtocolClassificationOverridesNestedValidation(t *testing.T) {
	t.Parallel()
	cause := &owonmodel.ErrInvalidRequest{Reason: "value is not finite"}
	for _, err := range []error{
		&owonprotocol.ErrMalformedResponse{Reason: "invalid device measurement", Cause: cause},
		&owonscpi.ErrMalformedResponse{Reason: "invalid device measurement", Cause: cause},
	} {
		require.ErrorIs(t, err, cause)
		require.Equal(t, codes.DataLoss, status.Code(rpcError("read", err)))
		service := subscriptionServiceError(err)
		require.Equal(t, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, service.Category)
		require.True(t, service.Retryable)
		require.Equal(t, codes.InvalidArgument, status.Code(rpcError("write", cause)))
		require.False(t, subscriptionServiceError(cause).Retryable)
		require.Equal(t, codes.Canceled, status.Code(rpcError("read", errors.Join(err, context.Canceled))))
		require.Equal(t, codes.DeadlineExceeded, status.Code(rpcError("read", errors.Join(err, context.DeadlineExceeded))))
	}
}
