package owonserver

import (
	"context"
	"errors"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// TestSubscriptionDeadlineIsDeviceUnavailable distinguishes deadline-wrapped framing from bad data.
//
// Example: a silent ASCII reply is retryable, while a malformed completed reply remains PROTOCOL.
func TestSubscriptionDeadlineIsDeviceUnavailable(t *testing.T) {
	for _, cause := range []error{context.Canceled, context.DeadlineExceeded, errors.New("bad framing")} {
		err := &owonprotocol.ErrMalformedResponse{Reason: "read failed", Cause: cause}
		serviceError := subscriptionServiceError(err)
		if errors.Is(cause, context.DeadlineExceeded) || errors.Is(cause, context.Canceled) {
			require.Equal(t, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE, serviceError.Category)
			require.True(t, serviceError.Retryable)
			require.Equal(t, status.FromContextError(cause).Code(), status.Code(rpcError("subscription", err)))
			continue
		}
		require.Equal(t, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, serviceError.Category)
		require.Equal(t, codes.DataLoss, status.Code(rpcError("subscription", err)))
	}
}
