package owonserver

import (
	"bufio"
	"context"
	"encoding/json"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonweb"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
)

// TestScreenTraceReplayHTTPAndRPC exercises native decoding through both network boundaries.
// This replays recorded physical data; it does not exercise live USB or prove calibration.
//
// Example: a browser-shaped waveform request and SSE subscription receive the same golden trace.
func TestScreenTraceReplayHTTPAndRPC(t *testing.T) {
	fixture, err := os.ReadFile("../../owonscpi/testdata/hds2202s-screen.json")
	require.NoError(t, err)
	var capture struct {
		Data   []byte `json:"data"`
		Header []byte `json:"screen_header_json"`
	}
	require.NoError(t, json.Unmarshal(fixture, &capture))
	backend := &scriptedBackend{Responses: map[string][]byte{
		"*IDN?":                   []byte("OWON,HDS2202S,25061855,V2.6.0"),
		":DATA:WAVE:SCREEN:HEAD?": capture.Header,
		":DATA:WAVE:SCREEN:CH1?":  capture.Data,
	}}
	service := requireNewServer(t, newTestInstrument(t, backend))
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	server := grpc.NewServer(GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(server, service)
	done := make(chan error, 1)
	observability.Go(t.Context(),
		// serveReplay carries recorded device responses through real protobuf transport.
		//
		// Example: shutdown joins this server before the test releases its controller.
		func(context.Context) { done <- server.Serve(listener) })
	t.Cleanup(
		// stopReplay releases network handlers and joins the serving goroutine.
		//
		// Example: failed assertions do not leave a replay server running.
		func() { server.Stop(); require.NoError(t, <-done) })
	connection, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	t.Cleanup(
		// closeReplayClient releases reconnect ownership before server shutdown.
		//
		// Example: no client transport outlives the test.
		func() { require.NoError(t, connection.Close()) })
	client := pb.NewOwonServiceClient(connection)
	ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancel()
	waveform, err := client.GetWaveform(ctx, &pb.GetWaveformRequest{Channel: pb.Channel_CHANNEL_1, Screen: true})
	require.NoError(t, err)
	requireRecordedScreenTrace(t, waveform, capture.Data, capture.Header)
	require.Zero(t, waveform.Sequence)
	streamCtx, stopStream := context.WithCancel(ctx)
	stream, err := client.Subscribe(streamCtx, &pb.SubscribeRequest{Interval: durationpb.New(time.Hour), WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1}})
	require.NoError(t, err)
	state, err := stream.Recv()
	require.NoError(t, err)
	require.NotNil(t, state.GetState())
	event, err := stream.Recv()
	require.NoError(t, err)
	requireRecordedScreenTrace(t, event.GetWaveform(), capture.Data, capture.Header)
	require.Equal(t, uint64(1), event.GetWaveform().Sequence)
	stopStream()
	_, err = stream.Recv()
	require.Error(t, err)

	handler, err := owonweb.NewHandler(client)
	require.NoError(t, err)
	httpServer := httptest.NewServer(handler)
	t.Cleanup(httpServer.Close)
	response, err := httpServer.Client().Post(httpServer.URL+"/api/waveform", "application/json", strings.NewReader(`{"channel":"CHANNEL_1","screen":true}`))
	require.NoError(t, err)
	body, err := io.ReadAll(response.Body)
	require.NoError(t, err)
	require.NoError(t, response.Body.Close())
	require.Equal(t, http.StatusOK, response.StatusCode)
	var httpWaveform pb.Waveform
	require.NoError(t, protojson.Unmarshal(body, &httpWaveform))
	requireRecordedScreenTrace(t, &httpWaveform, capture.Data, capture.Header)

	request, err := http.NewRequestWithContext(ctx, http.MethodGet, httpServer.URL+`/api/events?request=%7B%22waveform_channels%22:%5B%22CHANNEL_1%22%5D%7D&interval=1h`, nil)
	require.NoError(t, err)
	response, err = httpServer.Client().Do(request)
	require.NoError(t, err)
	defer response.Body.Close()
	require.Equal(t, http.StatusOK, response.StatusCode)
	scanner := bufio.NewScanner(response.Body)
	for scanner.Scan() {
		if !strings.HasPrefix(scanner.Text(), "data: ") {
			continue
		}
		var streamed pb.Event
		require.NoError(t, protojson.Unmarshal([]byte(strings.TrimPrefix(scanner.Text(), "data: ")), &streamed))
		if streamed.GetWaveform() == nil {
			continue
		}
		requireRecordedScreenTrace(t, streamed.GetWaveform(), capture.Data, capture.Header)
		require.NoError(t, response.Body.Close())
		return
	}
	require.NoError(t, scanner.Err())
	t.Fatal("SSE stream ended without a screen trace")
}

// requireRecordedScreenTrace compares transport results with the captured input and golden display values.
//
// Example: raw bytes and sample metadata must remain uninterpreted alongside the display trace.
func requireRecordedScreenTrace(
	t *testing.T,
	waveform *pb.Waveform,
	data []byte,
	header []byte,
) {
	t.Helper()
	require.NotNil(t, waveform)
	require.Equal(t, data, waveform.Data)
	require.Equal(t, header, waveform.ScreenHeaderJson)
	require.Equal(t, "owon-raw-unverified", waveform.Encoding)
	require.Nil(t, waveform.Metadata.SampleCount)
	require.Equal(t, uint64(600), waveform.Metadata.DataLengthBytes)
	require.NotNil(t, waveform.ScreenTrace)
	require.Equal(t, "owon-hds2202s-screen", waveform.ScreenTrace.Profile)
	require.Equal(t, []uint32{600, 200, 12, 8}, []uint32{waveform.ScreenTrace.Width, waveform.ScreenTrace.Height, waveform.ScreenTrace.HorizontalDivisions, waveform.ScreenTrace.VerticalDivisions})
	require.Len(t, waveform.ScreenTrace.Y, 600)
	require.Equal(t, []int32{179, 179, 178, 178, 176, 176, 173, 173, 177, 177, 176, 176}, waveform.ScreenTrace.Y[:12])
	require.Equal(t, int32(178), waveform.ScreenTrace.GroundY)
	require.Empty(t, waveform.ScreenTraceUnavailableReason)
	require.NoError(t, waveform.CaptureStartedAt.CheckValid())
	require.NoError(t, waveform.CapturedAt.CheckValid())
	require.False(t, waveform.CaptureStartedAt.AsTime().IsZero())
	require.False(t, waveform.CapturedAt.AsTime().IsZero())
}

// TestScreenTraceCountsTowardWaveformWireLimit includes semantic fields in existing admission charges.
//
// Example: a capture that fits without its screen trace is rejected when that trace crosses the ceiling.
func TestScreenTraceCountsTowardWaveformWireLimit(t *testing.T) {
	waveform := &pb.Waveform{Data: make([]byte, owonrpc.MaximumGRPCMessageBytes)}
	event := &pb.Event{Payload: &pb.Event_Waveform{Waveform: waveform}}
	overflow := proto.Size(event) + maximumSequenceCharge - owonrpc.MaximumGRPCMessageBytes
	waveform.Data = waveform.Data[:len(waveform.Data)-overflow]
	require.NoError(t, validateWaveformWireSize(event))
	waveform.ScreenTrace = &pb.ScreenTrace{Profile: "owon-hds2202s-screen", Y: make([]int32, 600)}
	requireErrorType[*ErrWaveformTooLarge](t, validateWaveformWireSize(event))
	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	t.Cleanup(queue.close)
	producer := &subscriptionProducer{queue: queue, waveformCapture: make(map[pb.Channel]uint64)}
	requireErrorType[*ErrWaveformTooLarge](t, producer.enqueueWaveform(event))
	require.Zero(t, queue.bytes)
}
