package owonserver

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// defaultMaximumActiveRPCs bounds concurrent unary handlers.
	//
	// Example: the sixty-fifth unary request fails fast instead of waiting behind USB admission forever.
	defaultMaximumActiveRPCs = 64
	// maximumActiveRPCsCapacity bounds configured RPC admission memory.
	//
	// Example: a typo such as one million handlers is rejected during startup.
	maximumActiveRPCsCapacity = 1024
	// DefaultMaximumActiveSubscriptions bounds concurrent polling streams when configuration is omitted.
	//
	// Example: the thirty-third default subscription receives ResourceExhausted.
	DefaultMaximumActiveSubscriptions = 32
	// MaximumActiveSubscriptions bounds configured concurrent stream admission.
	//
	// Example: daemon flags and service construction reject more than 1024 subscriptions.
	MaximumActiveSubscriptions = 1024
)

// ServerConfig controls server-wide resource concurrency.
//
// MaxActiveRPCs applies only to unary handlers; Subscribe uses MaxActiveSubscriptions
// and the shared queue budget for its lifetime. MaxSubscriptionPollWork is the weighted
// transport-command allowance per one-second window; zero selects the safe default. Each
// gRPC connection is also bounded by MaximumGRPCConcurrentStreams.
//
// Example: MaxActiveSubscriptions=8 and MaxSubscriptionPollWork=64 bound stream count and
// aggregate estimated poll commands independently.
type ServerConfig struct {
	MaxActiveRPCs           int
	MaxActiveSubscriptions  int
	MaxSubscriptionPollWork int
}

// Server implements the gRPC API over one typed instrument.
//
// Example: register the successfully constructed server with RegisterOwonServiceServer.
type Server struct {
	pb.UnimplementedOwonServiceServer
	instrument                Instrument
	rpcAdmission              chan struct{}
	subscriptions             chan struct{}
	subscriptionBudget        *subscriptionBudget
	subscriptionPollScheduler *subscriptionPollScheduler
}

// NewServer constructs a gRPC service for one instrument.
//
// Example: a daemon handles the constructor error before registering the service.
func NewServer(instrument Instrument) (*Server, error) {
	return NewServerWithConfig(instrument, ServerConfig{})
}

// NewServerWithConfig constructs a service with explicit resource limits.
//
// Example: tests configure one active subscription to exercise admission failure.
func NewServerWithConfig(
	instrument Instrument,
	config ServerConfig,
) (*Server, error) {
	if isNilInstrument(instrument) {
		return nil, &ErrInvalidConfig{Reason: "create OWON server: instrument is nil"}
	}
	if config.MaxActiveRPCs < 0 || config.MaxActiveSubscriptions < 0 || config.MaxSubscriptionPollWork < 0 {
		return nil, &ErrInvalidConfig{Reason: "server resource counts must not be negative"}
	}
	if config.MaxActiveSubscriptions == 0 {
		config.MaxActiveSubscriptions = DefaultMaximumActiveSubscriptions
	}
	if config.MaxActiveRPCs == 0 {
		config.MaxActiveRPCs = defaultMaximumActiveRPCs
	}
	if config.MaxSubscriptionPollWork == 0 {
		config.MaxSubscriptionPollWork = defaultMaximumSubscriptionPollWork
	}
	if config.MaxActiveRPCs > maximumActiveRPCsCapacity {
		return nil, fmt.Errorf("maximum active RPCs %d exceeds %d: %w", config.MaxActiveRPCs, maximumActiveRPCsCapacity, &ErrInvalidConfig{Reason: "maximum active RPC count exceeds the configured maximum"})
	}
	if config.MaxActiveSubscriptions > MaximumActiveSubscriptions {
		return nil, fmt.Errorf("maximum active subscriptions %d exceeds %d: %w", config.MaxActiveSubscriptions, MaximumActiveSubscriptions, &ErrInvalidConfig{Reason: "maximum active subscription count exceeds the configured maximum"})
	}
	if config.MaxSubscriptionPollWork > maximumSubscriptionPollWorkCapacity {
		return nil, fmt.Errorf("maximum subscription poll work %d exceeds %d: %w", config.MaxSubscriptionPollWork, maximumSubscriptionPollWorkCapacity, &ErrInvalidConfig{Reason: "maximum poll work exceeds the configured maximum"})
	}
	pollScheduler, err := newSubscriptionPollScheduler(config.MaxSubscriptionPollWork, subscriptionPollWorkWindow)
	if err != nil {
		return nil, fmt.Errorf("create subscription poll scheduler: %w", err)
	}

	return &Server{
		instrument:                instrument,
		rpcAdmission:              make(chan struct{}, config.MaxActiveRPCs),
		subscriptions:             make(chan struct{}, config.MaxActiveSubscriptions),
		subscriptionBudget:        newSubscriptionBudget(maximumServerSubscriptionBytes),
		subscriptionPollScheduler: pollScheduler,
	}, nil
}

// acquireRPC reserves one bounded handler slot without blocking.
//
// Example: excess clients receive ResourceExhausted before waiting on USB admission.
func (server *Server) acquireRPC() error {
	if server == nil || server.rpcAdmission == nil {
		return status.Error(codes.FailedPrecondition, "RPC admission is unavailable")
	}
	select {
	case server.rpcAdmission <- struct{}{}:
		return nil
	default:
		return status.Error(codes.ResourceExhausted, "maximum active RPCs reached")
	}
}

// releaseRPC returns one bounded unary-handler slot.
//
// Example: every unary method defers release after admission.
func (server *Server) releaseRPC() {
	if server == nil || server.rpcAdmission == nil {
		return
	}
	<-server.rpcAdmission
}

// acquireSubscription reserves one server-wide stream slot without blocking.
//
// Example: exhausted admission returns ResourceExhausted immediately.
func (server *Server) acquireSubscription() error {
	if server == nil || server.subscriptions == nil {
		return status.Error(codes.FailedPrecondition, "subscription admission is unavailable")
	}
	select {
	case server.subscriptions <- struct{}{}:
		return nil
	default:
		return status.Error(codes.ResourceExhausted, "maximum active subscriptions reached")
	}
}

// releaseSubscription returns one server-wide stream slot.
//
// Example: Subscribe defers it after successful admission.
func (server *Server) releaseSubscription() {
	<-server.subscriptions
}

// serviceInstrument returns the configured instrument or a stable gRPC precondition error.
//
// Example: direct method calls on a nil server cannot panic.
func (server *Server) serviceInstrument() (Instrument, error) {
	if server == nil || isNilInstrument(server.instrument) {
		return nil, status.Error(codes.FailedPrecondition, "instrument is unavailable")
	}

	return server.instrument, nil
}

// GetDeviceInfo returns the connected instrument's current SCPI identity.
//
// Example: clients can reject a daemon connected to an unexpected serial.
func (server *Server) GetDeviceInfo(
	ctx context.Context,
	_ *emptypb.Empty,
) (*pb.DeviceInfo, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	info, err := instrument.DeviceInfo(ctx)
	if err != nil {
		return nil, rpcError("get device info", err)
	}

	return owonrpc.DeviceInfoToProto(info), nil
}

// GetState returns one coherent requested snapshot from serialized device queries.
//
// Example: clients select only measurements needed for one poll cycle.
func (server *Server) GetState(
	ctx context.Context,
	request *pb.GetStateRequest,
) (*pb.StateSnapshot, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	state, err := instrument.State(ctx, owonrpc.StateRequestFromProto(request))
	if err != nil {
		return nil, rpcError("get state", err)
	}

	return owonrpc.StateSnapshotToProto(state), nil
}

// Execute performs one validated raw command with caller-selected response framing.
//
// Example: RESPONSE_MODE_ASCII_LINE safely carries an identity query.
func (server *Server) Execute(
	ctx context.Context,
	request *pb.ExecuteRequest,
) (*pb.ExecuteResponse, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	if request == nil {
		return nil, status.Error(codes.InvalidArgument, "request is required")
	}
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	command, err := owonrpc.CommandFromProto(request)
	if err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	response, err := instrument.Execute(ctx, command)
	if err != nil {
		var invalidCommand *owonprotocol.ErrInvalidCommand
		if errors.As(err, &invalidCommand) {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}
		return nil, rpcError("execute command", err)
	}

	return &pb.ExecuteResponse{Data: response}, nil
}

// SetChannel applies a presence-aware channel patch.
//
// Example: an explicit display=false field disables the selected channel.
func (server *Server) SetChannel(
	ctx context.Context,
	request *pb.SetChannelRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetChannel(ctx, owonrpc.ChannelPatchFromProto(request)); err != nil {
		return nil, rpcError("set channel", err)
	}

	return commandResult(time.Now()), nil
}

// SetAcquisition applies a presence-aware acquisition patch.
//
// Example: callers may set supported acquisition mode without changing horizontal controls.
func (server *Server) SetAcquisition(
	ctx context.Context,
	request *pb.SetAcquisitionRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetAcquisition(ctx, owonrpc.AcquisitionPatchFromProto(request)); err != nil {
		return nil, rpcError("set acquisition", err)
	}

	return commandResult(time.Now()), nil
}

// SetHorizontal applies a presence-aware horizontal patch.
//
// Example: an explicit zero offset remains distinguishable from omission.
func (server *Server) SetHorizontal(
	ctx context.Context,
	request *pb.SetHorizontalRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetHorizontal(ctx, owonrpc.HorizontalPatchFromProto(request)); err != nil {
		return nil, rpcError("set horizontal", err)
	}

	return commandResult(time.Now()), nil
}

// SetTrigger applies a presence-aware trigger patch.
//
// Example: source, slope, and level can be updated in one ordered request.
func (server *Server) SetTrigger(
	ctx context.Context,
	request *pb.SetTriggerRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetTrigger(ctx, owonrpc.TriggerPatchFromProto(request)); err != nil {
		return nil, rpcError("set trigger", err)
	}

	return commandResult(time.Now()), nil
}

// SetMeasurement applies measurement-display configuration.
//
// Example: unsupported replacement requests return Unimplemented rather than guessing SCPI.
func (server *Server) SetMeasurement(
	ctx context.Context,
	request *pb.SetMeasurementRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetMeasurement(ctx, owonrpc.MeasurementPatchFromProto(request)); err != nil {
		return nil, rpcError("set measurement", err)
	}

	return commandResult(time.Now()), nil
}

// SetGenerator applies a presence-aware waveform-generator patch.
//
// Example: output=false explicitly disables generator output.
func (server *Server) SetGenerator(
	ctx context.Context,
	request *pb.SetGeneratorRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetGenerator(ctx, owonrpc.GeneratorPatchFromProto(request)); err != nil {
		return nil, rpcError("set generator", err)
	}

	return commandResult(time.Now()), nil
}

// SetDmm applies a presence-aware multimeter patch.
//
// Example: clients can select voltage and enable automatic range.
func (server *Server) SetDmm(
	ctx context.Context,
	request *pb.SetDmmRequest,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.SetDMM(ctx, owonrpc.DMMPatchFromProto(request)); err != nil {
		return nil, rpcError("set DMM", err)
	}

	return commandResult(time.Now()), nil
}

// GetDmmMeasurement returns the current parsed and raw DMM reading.
//
// Example: clients retain Raw for diagnostics while using Value for metrics.
func (server *Server) GetDmmMeasurement(
	ctx context.Context,
	_ *emptypb.Empty,
) (*pb.DmmMeasurement, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	measurement, err := instrument.DMMMeasurement(ctx)
	if err != nil {
		return nil, rpcError("get DMM measurement", err)
	}

	return owonrpc.DMMMeasurementToProto(measurement), nil
}

// Run starts continuous acquisition.
//
// Example: it returns only after the command reaches the USB endpoint.
func (server *Server) Run(
	ctx context.Context,
	_ *emptypb.Empty,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.Run(ctx); err != nil {
		return nil, rpcError("run acquisition", err)
	}

	return commandResult(time.Now()), nil
}

// Stop stops acquisition.
//
// Example: it does not modify trigger or timebase settings.
func (server *Server) Stop(
	ctx context.Context,
	_ *emptypb.Empty,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.Stop(ctx); err != nil {
		return nil, rpcError("stop acquisition", err)
	}

	return commandResult(time.Now()), nil
}

// Single arms one acquisition.
//
// Example: it uses the trigger settings already configured on the device.
func (server *Server) Single(
	ctx context.Context,
	_ *emptypb.Empty,
) (*pb.CommandResult, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	if err := instrument.Single(ctx); err != nil {
		return nil, rpcError("single acquisition", err)
	}

	return commandResult(time.Now()), nil
}

// GetWaveform returns raw waveform bytes and verified metadata.
//
// Example: sample bytes remain uninterpreted until device encoding is proven.
func (server *Server) GetWaveform(
	ctx context.Context,
	request *pb.GetWaveformRequest,
) (*pb.Waveform, error) {
	if err := server.acquireRPC(); err != nil {
		return nil, err
	}
	defer server.releaseRPC()
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return nil, instrumentErr
	}
	waveform, err := instrument.Waveform(ctx, owonrpc.WaveformRequestFromProto(request))
	if err != nil {
		return nil, rpcError("get waveform", err)
	}

	result := owonrpc.WaveformToProto(waveform)
	if err := validateWaveformWireSize(&pb.Event{Timestamp: result.CapturedAt, Payload: &pb.Event_Waveform{Waveform: result}}); err != nil {
		return nil, rpcError("get waveform", err)
	}
	return result, nil
}

// commandResult returns an application timestamp after a successful control mutation.
//
// Example: setters use this result after the final SCPI write succeeds.
func commandResult(now time.Time) *pb.CommandResult {
	return &pb.CommandResult{AppliedAt: timestamppb.New(now)}
}

// ErrInvalidInput identifies invalid RPC server input.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrInvalidInput struct {
	Reason string
	Cause  error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrInvalidInput) Error() string {
	if err == nil {
		return "invalid RPC server input"
	}
	detail := err.Reason
	if detail == "" {
		detail = "invalid RPC server input"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrInvalidInput) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}

// ErrInvalidConfig identifies invalid RPC server configuration.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrInvalidConfig struct {
	Reason string
	Cause  error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrInvalidConfig) Error() string {
	if err == nil {
		return "invalid RPC server configuration"
	}
	detail := err.Reason
	if detail == "" {
		detail = "invalid RPC server configuration"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrInvalidConfig) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}

// ErrUnavailable identifies RPC server resource unavailable.
//
// Example: callers can distinguish local RPC failures through errors.As.
type ErrUnavailable struct {
	Operation string
	Resource  string
	Reason    string
	Cause     error
}

// Error describes the local failure and retains useful cause text.
//
// Example: logging the error identifies the failed RPC boundary.
func (err *ErrUnavailable) Error() string {
	if err == nil {
		return "RPC server resource unavailable"
	}
	detail := err.Reason
	if err.Operation != "" || err.Resource != "" {
		detail = fmt.Sprintf("%s: %s %s", err.Operation, err.Resource, detail)
	}
	if detail == "" {
		detail = "RPC server resource unavailable"
	}
	if err.Cause != nil {
		return fmt.Sprintf("%s: %v", detail, err.Cause)
	}
	return detail
}

// Unwrap exposes the originating failure.
//
// Example: errors.Is follows a preserved context cancellation cause.
func (err *ErrUnavailable) Unwrap() error {
	if err == nil {
		return nil
	}
	return err.Cause
}
