package owonserver

import (
	"context"
	"net"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonrpc/owonclient"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
)

// TestSubscribeValidationRejectsPolicyBeforeAdmission verifies invalid intervals and capacities cannot acquire a slot.
//
// Example: an invalid request reports InvalidArgument even when every stream slot is already occupied.
func TestSubscribeValidationRejectsPolicyBeforeAdmission(t *testing.T) {
	backend := new(scriptedBackend)
	server, err := NewServerWithConfig(newTestInstrument(t, backend), ServerConfig{MaxActiveSubscriptions: 1})
	require.NoError(t, err)
	require.NoError(t, server.acquireSubscription())
	defer server.releaseSubscription()
	client := newSubscribeTCPClient(t, server)
	ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancel()
	for _, request := range []*pb.SubscribeRequest{
		{Interval: durationpb.New(0)},
		{Interval: durationpb.New(-time.Second)},
		{Interval: durationpb.New(19 * time.Millisecond)},
		{Interval: &durationpb.Duration{Seconds: 1, Nanos: -1}},
		{Interval: &durationpb.Duration{Seconds: 315576000001}},
		{QueueCapacity: 1025},
	} {
		stream, err := client.Subscribe(ctx, request)
		require.NoError(t, err)
		_, err = stream.Recv()
		require.Equal(t, codes.InvalidArgument, status.Code(err), request)
		require.Len(t, server.subscriptions, 1)
	}
	require.Empty(t, backend.Commands)
	stream, err := client.Subscribe(ctx, &pb.SubscribeRequest{})
	require.NoError(t, err)
	_, err = stream.Recv()
	require.Equal(t, codes.ResourceExhausted, status.Code(err), "valid requests still obey admission")
	require.Empty(t, backend.Commands)
	t.Log("actual TCP: invalid policy -> InvalidArgument with occupied slot unchanged and zero backend calls; valid request -> ResourceExhausted")
}

// TestSubscribeTCPAcceptsCoreDefaultsAndLongIntervals verifies valid requests still produce state.
//
// Example: the core accepts a two-hour interval even though the browser applies a one-hour ceiling.
func TestSubscribeTCPAcceptsCoreDefaultsAndLongIntervals(t *testing.T) {
	for _, interval := range []*durationpb.Duration{nil, durationpb.New(20 * time.Millisecond), durationpb.New(2 * time.Hour)} {
		backend := &scriptedBackend{Responses: map[string][]byte{"*IDN?": []byte("OWON,HDS2202S,25061855,V2.6.0")}}
		server := requireNewServer(t, newTestInstrument(t, backend))
		client := newSubscribeTCPClient(t, server)
		ctx, cancel := context.WithTimeout(t.Context(), 5*time.Second)
		defer cancel()
		stream, err := client.Subscribe(ctx, &pb.SubscribeRequest{Interval: interval})
		require.NoError(t, err)
		event, err := stream.Recv()
		require.NoError(t, err)
		require.Equal(t, "25061855", event.GetState().GetDevice().GetSerial())
		require.EqualValues(t, 1, event.Sequence)
		cancel()
	}
	t.Log("actual TCP: omitted defaults, 20ms minimum and 2h interval each publish parsed state")
}

// TestSubscribeValidatorDomain verifies selectors, presence and both valid interval/capacity boundaries.
//
// Example: fourteen unique measurements and a two-hour interval pass without normalization.
func TestSubscribeValidatorDomain(t *testing.T) {
	selector := &pb.MeasurementSelector{Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY}
	var allMeasurements []*pb.MeasurementSelector
	for _, channel := range []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2} {
		for kind := pb.MeasurementKind_MEASUREMENT_KIND_MAXIMUM; kind <= pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY; kind++ {
			allMeasurements = append(allMeasurements, &pb.MeasurementSelector{Channel: channel, Kind: kind})
		}
	}
	for _, testCase := range []struct {
		Name    string
		Request *pb.SubscribeRequest
		Valid   bool
	}{
		{Name: "nil request"},
		{Name: "nil lists and defaults", Request: &pb.SubscribeRequest{}, Valid: true},
		{Name: "empty lists", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{}, WaveformChannels: []pb.Channel{}}, Valid: true},
		{Name: "nil selector element", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{nil}}},
		{Name: "one measurement", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{selector}}, Valid: true},
		{Name: "fourteen measurements", Request: &pb.SubscribeRequest{Measurements: allMeasurements}, Valid: true},
		{Name: "fifteen measurements", Request: &pb.SubscribeRequest{Measurements: append(append([]*pb.MeasurementSelector{}, allMeasurements...), selector)}},
		{Name: "duplicate measurement", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{selector, selector}}},
		{Name: "unknown measurement channel", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{{Channel: pb.Channel(99), Kind: selector.Kind}}}},
		{Name: "unspecified measurement kind", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{{Channel: selector.Channel}}}},
		{Name: "unknown measurement kind", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{{Channel: selector.Channel, Kind: pb.MeasurementKind_MEASUREMENT_KIND_UNKNOWN}}}},
		{Name: "unsupported measurement kind", Request: &pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{{Channel: selector.Channel, Kind: pb.MeasurementKind(99)}}}},
		{Name: "one waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1}}, Valid: true},
		{Name: "two waveforms", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2}}, Valid: true},
		{Name: "duplicate waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_1}}},
		{Name: "three waveforms", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2, pb.Channel_CHANNEL_1}}},
		{Name: "unknown waveform", Request: &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel(99)}}},
		{Name: "minimum interval", Request: &pb.SubscribeRequest{Interval: durationpb.New(20 * time.Millisecond)}, Valid: true},
		{Name: "one hour", Request: &pb.SubscribeRequest{Interval: durationpb.New(time.Hour)}, Valid: true},
		{Name: "above browser ceiling", Request: &pb.SubscribeRequest{Interval: durationpb.New(2 * time.Hour)}, Valid: true},
		{Name: "maximum protobuf interval", Request: &pb.SubscribeRequest{Interval: &durationpb.Duration{Seconds: 315576000000}}, Valid: true},
		{Name: "capacity one", Request: &pb.SubscribeRequest{QueueCapacity: 1}, Valid: true},
		{Name: "capacity maximum", Request: &pb.SubscribeRequest{QueueCapacity: 1024}, Valid: true},
	} {
		t.Run(testCase.Name,
			// validateWithoutNormalization preserves defaults and optional-field presence on either outcome.
			//
			// Example: absent interval remains nil after a successful validation.
			func(t *testing.T) {
				before := proto.Clone(testCase.Request)
				err := owonrpc.ValidateSubscribeRequest(testCase.Request)
				if testCase.Valid {
					require.NoError(t, err)
				} else {
					requireErrorType[*owonrpc.ErrInvalidInput](t, err)
				}
				require.True(t, proto.Equal(before, testCase.Request))
			})
	}
	defaults := new(pb.SubscribeRequest)
	require.NoError(t, owonrpc.ValidateSubscribeRequest(defaults))
	require.Nil(t, defaults.Interval)
	require.Nil(t, defaults.Measurements)
	require.Nil(t, defaults.WaveformChannels)
	require.Zero(t, defaults.QueueCapacity)
	queue, err := newSubscriptionQueue(defaults.QueueCapacity)
	require.NoError(t, err)
	defer queue.close()
	require.Equal(t, 8, queue.capacity)
	require.Equal(t, 100*time.Millisecond, owonrpc.DefaultSubscriptionInterval)
}

// newSubscribeTCPClient connects the public client to a production server on a kernel TCP listener.
//
// Example: validation and admission status travel through protobuf and gRPC, with no fake stream context.
func newSubscribeTCPClient(
	t *testing.T,
	service *Server,
) *owonclient.Client {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	server := grpc.NewServer(GRPCServerOptions()...)
	pb.RegisterOwonServiceServer(server, service)
	done := make(chan error, 1)
	observability.Go(t.Context(),
		// serveSubscriptions owns the listener until fixture cleanup stops the server.
		//
		// Example: the buffered result allows shutdown to join without a detached accept loop.
		func(context.Context) { done <- server.Serve(listener) })
	t.Cleanup(
		// stopSubscriptions terminates all handlers and joins the accept loop on failed assertions too.
		//
		// Example: no production goroutine survives the test fixture.
		func() {
			server.Stop()
			require.NoError(t, <-done)
		})
	connection, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)
	t.Cleanup(
		// closeSubscriptionClient releases reconnect ownership before server shutdown.
		//
		// Example: the client connection cannot outlive the test.
		func() { require.NoError(t, connection.Close()) })
	client, err := owonclient.NewClient(connection)
	require.NoError(t, err)
	return client
}
