package owonserver

import (
	"context"
	"errors"
	"io"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// TestSubscriptionQueueCoalescesState verifies only the freshest unsent state is retained.
//
// Example: a slow client receives only the latest state as publication sequence one.
func TestSubscriptionQueueCoalescesState(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	require.NoError(t, queue.enqueueState(&pb.Event{Payload: &pb.Event_State{State: new(pb.StateSnapshot)}}))
	require.NoError(t, queue.enqueueState(&pb.Event{Payload: &pb.Event_State{State: new(pb.StateSnapshot)}}))

	event, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(1), event.Sequence)
}

// TestSubscriptionQueueRejectsUnavailableNotifier verifies zero-value misuse is immediate.
//
// Example: a queue assembled outside its constructor returns a typed state error instead of blocking.
func TestSubscriptionQueueRejectsUnavailableNotifier(t *testing.T) {
	t.Parallel()

	_, err := (&subscriptionQueue{}).next(context.Background())
	var resourceState *ErrUnavailable
	require.ErrorAs(t, err, &resourceState)
	require.Equal(t, "queue", resourceState.Resource)
}

// TestSubscriptionQueueRejectsNilWaveformEvent verifies malformed producer input cannot panic.
//
// Example: a nil event returns ErrInvalidInput before payload inspection.
func TestSubscriptionQueueRejectsNilWaveformEvent(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	err = queue.enqueueWaveform(nil)
	requireErrorType[*ErrInvalidInput](t, err)
}

// TestSubscriptionQueueRejectsNonStateEvents verifies queue entry points preserve event kinds.
//
// Example: a waveform cannot silently enter the state FIFO and corrupt stream ordering.
func TestSubscriptionQueueRejectsNonStateEvents(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	err = queue.enqueueState(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: pb.Channel_CHANNEL_1}}})
	requireErrorType[*ErrInvalidInput](t, err)
}

// TestSubscriptionQueueReportsWaveformDrops verifies bounded overflow becomes an explicit gap.
//
// Example: dropping sequence two produces one gap before sequence three.
func TestSubscriptionQueueReportsWaveformDrops(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	channel := pb.Channel_CHANNEL_1
	require.NoError(t, queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: channel, Sequence: 1}}}))
	require.NoError(t, queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: channel, Sequence: 2}}}))
	first, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(1), first.Sequence)
	require.NoError(t, queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: channel, Sequence: 3}}}))
	gap, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(2), gap.GetWaveformGap().FirstMissingSequence)
	require.Equal(t, uint64(2), gap.GetWaveformGap().LastMissingSequence)
	require.Equal(t, uint64(1), gap.GetWaveformGap().MissingCount)
	third, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(3), third.Sequence)
}

// TestSubscriptionClassifiesNonRetryableErrors verifies caller defects are not device outages.
//
// Example: an unsupported control produces a non-retryable UNSUPPORTED stream event.
func TestSubscriptionClassifiesNonRetryableErrors(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	producer := &subscriptionProducer{queue: queue}
	producer.finishWithError(new(owonscpi.ErrUnsupportedControl))

	event, err := queue.next(context.Background())
	require.NoError(t, err)
	require.False(t, event.GetError().Retryable)
	require.Equal(t, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_UNSUPPORTED, event.GetError().Category)
}

// TestSubscriptionQueuePreservesTerminalFIFO verifies errors never overtake queued data.
//
// Example: a waveform is delivered before the terminal ServiceError and error result.
func TestSubscriptionQueuePreservesTerminalFIFO(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	require.NoError(t, queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: pb.Channel_CHANNEL_1, Sequence: 7}}}))
	producer := &subscriptionProducer{queue: queue}
	producer.finishWithError(new(owonscpi.ErrUnsupportedControl))

	waveform, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(1), waveform.Sequence)
	require.Equal(t, uint64(7), waveform.GetWaveform().Sequence)
	serviceError, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(2), serviceError.Sequence)
	require.NotNil(t, serviceError.GetError())
	_, err = queue.next(context.Background())
	requireErrorType[*owonscpi.ErrUnsupportedControl](t, err)
}

// TestSubscriptionQueueFlushesPendingGap verifies termination publishes known loss first.
//
// Example: a dropped capture is reported before a clean end-of-stream result.
func TestSubscriptionQueueFlushesPendingGap(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	channel := pb.Channel_CHANNEL_2
	require.NoError(t, queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: channel, Sequence: 1}}}))
	require.NoError(t, queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{Channel: channel, Sequence: 2}}}))
	queue.finish(nil, nil)

	first, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(1), first.Sequence)
	gap, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Equal(t, uint64(2), gap.Sequence)
	require.Equal(t, uint64(2), gap.GetWaveformGap().FirstMissingSequence)
	_, err = queue.next(context.Background())
	require.ErrorIs(t, err, io.EOF)
	require.Zero(t, queue.bytes)
}

// TestSubscriptionQueueRejectsOversizedEvent verifies the per-event serialized-charge bound.
//
// Example: a payload above the thirty-two MiB serialized ceiling cannot enter the queue.
func TestSubscriptionQueueRejectsOversizedEvent(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	err = queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{
		Channel:  pb.Channel_CHANNEL_1,
		Sequence: 1,
		Data:     make([]byte, maximumSubscriptionEventBytes+1),
	}}})
	require.Error(t, err)
	requireErrorType[*ErrSubscriptionResourceExhausted](t, err)
}

// TestSubscriptionQueueAcceptsMaximumRawWaveform verifies raw and wire ceilings differ.
//
// Example: an exact sixteen-MiB device payload plus its protobuf envelope remains publishable.
func TestSubscriptionQueueAcceptsMaximumRawWaveform(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	err = queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{
		Channel:  pb.Channel_CHANNEL_1,
		Sequence: 1,
		Data:     make([]byte, owonprotocol.DefaultMaximumResponseBytes),
	}}})
	require.NoError(t, err)
	event, err := queue.next(context.Background())
	require.NoError(t, err)
	require.Len(t, event.GetWaveform().Data, int(owonprotocol.DefaultMaximumResponseBytes))
	require.Equal(t, uint64(1), event.Sequence)
	require.Zero(t, queue.bytes)
}

// TestSubscriptionQueueEnforcesAggregateByteBudget verifies serialized charges are cumulative.
//
// Example: an event cannot enter when fewer bytes remain than its encoded representation.
func TestSubscriptionQueueEnforcesAggregateByteBudget(t *testing.T) {
	t.Parallel()

	queue, err := newSubscriptionQueue(2)
	require.NoError(t, err)
	queue.bytes = maximumSubscriptionBytes - 1
	err = queue.enqueueWaveform(&pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{
		Channel:  pb.Channel_CHANNEL_1,
		Sequence: 1,
		Data:     []byte{1},
	}}})
	requireErrorType[*ErrSubscriptionResourceExhausted](t, err)
}

// TestSubscriptionQueuesShareAndReleaseServerBudget verifies cross-stream accounting.
//
// Example: dequeueing from one stream allows another stream to publish the same charge.
func TestSubscriptionQueuesShareAndReleaseServerBudget(t *testing.T) {
	t.Parallel()

	event := &pb.Event{Payload: &pb.Event_Waveform{Waveform: &pb.Waveform{
		Channel: pb.Channel_CHANNEL_1, Sequence: 1, Data: []byte{1},
	}}}
	charge := proto.Size(event) + maximumSequenceCharge
	budget := newSubscriptionBudget(charge)
	first, err := newSubscriptionQueueWithBudget(1, budget)
	require.NoError(t, err)
	second, err := newSubscriptionQueueWithBudget(1, budget)
	require.NoError(t, err)
	require.NoError(t, first.enqueueWaveform(event))
	requireErrorType[*ErrSubscriptionResourceExhausted](t, second.enqueueWaveform(event))
	_, err = first.next(context.Background())
	require.NoError(t, err)
	require.NoError(t, second.enqueueWaveform(event))
	second.close()
}

// TestSubscriptionQueueRejectsExcessCapacity verifies the hard event-count limit.
//
// Example: a requested capacity of 1025 is rejected before allocating a queue.
func TestSubscriptionQueueRejectsExcessCapacity(t *testing.T) {
	t.Parallel()

	_, err := newSubscriptionQueue(owonrpc.MaximumSubscriptionCapacity + 1)
	requireErrorType[*owonrpc.ErrInvalidInput](t, err)
}

// TestValidateSubscribeRequestEnforcesSelectorCardinality verifies bounded unique polling work.
//
// Example: duplicate channels, duplicate measurements, and a fifteenth selector are rejected.
func TestValidateSubscribeRequestEnforcesSelectorCardinality(t *testing.T) {
	t.Parallel()

	requireErrorType[*owonrpc.ErrInvalidInput](t, owonrpc.ValidateSubscribeRequest(&pb.SubscribeRequest{
		WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_1},
	}))
	selector := &pb.MeasurementSelector{Channel: pb.Channel_CHANNEL_1, Kind: pb.MeasurementKind_MEASUREMENT_KIND_FREQUENCY}
	requireErrorType[*owonrpc.ErrInvalidInput](t, owonrpc.ValidateSubscribeRequest(&pb.SubscribeRequest{Measurements: []*pb.MeasurementSelector{selector, selector}}))
	selectors := make([]*pb.MeasurementSelector, owonmodel.MaximumMeasurementSelectors+1)
	for index := range selectors {
		selectors[index] = selector
	}
	requireErrorType[*owonrpc.ErrInvalidInput](t, owonrpc.ValidateSubscribeRequest(&pb.SubscribeRequest{Measurements: selectors}))
}

// TestServerBoundsActiveSubscriptions verifies admission is server-wide and nonblocking.
//
// Example: a configured limit of one rejects the second concurrent reservation.
func TestServerBoundsActiveSubscriptions(t *testing.T) {
	t.Parallel()

	server, err := NewServerWithConfig(newTestInstrument(t, new(scriptedBackend)), ServerConfig{MaxActiveSubscriptions: 1})
	require.NoError(t, err)
	require.NoError(t, server.acquireSubscription())
	require.Equal(t, codes.ResourceExhausted, status.Code(server.acquireSubscription()))
	server.releaseSubscription()
	require.NoError(t, server.acquireSubscription())
	server.releaseSubscription()
}

// TestServerBoundsSubscriptionPollWork verifies the weighted scheduler limit is configured.
//
// Example: an impossible aggregate command budget is rejected before serving streams.
func TestServerBoundsSubscriptionPollWork(t *testing.T) {
	t.Parallel()

	_, err := NewServerWithConfig(
		newTestInstrument(t, new(scriptedBackend)),
		ServerConfig{MaxSubscriptionPollWork: maximumSubscriptionPollWorkCapacity + 1},
	)
	requireErrorType[*ErrInvalidConfig](t, err)
}

// TestSubscribeDoesNotConsumeUnaryRPCAdmission verifies subscriptions have independent admission.
//
// Example: a held MaxActiveRPCs slot does not prevent a valid stream from starting and canceling.
func TestSubscribeDoesNotConsumeUnaryRPCAdmission(t *testing.T) {
	t.Parallel()

	backend := &scriptedBackend{Responses: map[string][]byte{
		"*IDN?": []byte("OWON,HDS2202S,25061855,V2.6.0"),
	}}
	server, err := NewServerWithConfig(
		newTestInstrument(t, backend),
		ServerConfig{MaxActiveRPCs: 1, MaxActiveSubscriptions: 1},
	)
	require.NoError(t, err)
	require.NoError(t, server.acquireRPC())
	defer server.releaseRPC()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	client := newControlClientForServer(t, server)
	stream, err := client.Subscribe(ctx, &pb.SubscribeRequest{})
	require.NoError(t, err)
	event, err := stream.Recv()
	require.NoError(t, err)
	require.NotNil(t, event.GetState())
	cancel()
	_, err = stream.Recv()
	require.Equal(t, codes.Canceled, status.Code(err))
}

// TestSubscribeWaitsForProducerAfterSendError verifies child cancellation and producer join ordering.
//
// Example: a failed stream send cancels a blocked waveform query before Subscribe releases its slot.
func TestSubscribeWaitsForProducerAfterSendError(t *testing.T) {
	t.Parallel()

	backend := newSubscriptionCancellationBackend()
	server, err := NewServerWithConfig(
		newTestInstrument(t, backend),
		ServerConfig{MaxActiveSubscriptions: 1},
	)
	require.NoError(t, err)
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	result := make(chan error, 1)
	failure := subscriptionSendFailure{WaitForBackend: backend.headerEntered, Cause: errors.New("send failed"), Result: result}
	client := newControlClientForServer(t, server, grpc.StreamInterceptor(failure.intercept))
	stream, err := client.Subscribe(ctx, &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1}})
	require.NoError(t, err)

	<-backend.cancelObserved
	select {
	case err := <-result:
		require.FailNow(t, "Subscribe returned before the blocked producer completed", err)
	default:
	}
	close(backend.releaseAfterCancel)
	require.ErrorContains(t, <-result, "send failed")
	_, err = stream.Recv()
	require.ErrorContains(t, err, "send failed")
}

// subscriptionCancellationBackend blocks one waveform header until its child context is canceled.
//
// Example: a send failure can be staged while the producer remains inside backend I/O.
type subscriptionCancellationBackend struct {
	headerEntered      chan struct{}
	cancelObserved     chan struct{}
	releaseAfterCancel chan struct{}
	headerOnce         sync.Once
	cancelOnce         sync.Once
}

// newSubscriptionCancellationBackend constructs a channel-controlled subscription backend.
//
// Example: tests release the backend only after observing producer cancellation.
func newSubscriptionCancellationBackend() *subscriptionCancellationBackend {
	return &subscriptionCancellationBackend{
		headerEntered:      make(chan struct{}),
		cancelObserved:     make(chan struct{}),
		releaseAfterCancel: make(chan struct{}),
	}
}

// Exchange returns identity and blocks the waveform header until cancellation.
//
// Example: the first state event can reach Send while the next producer operation remains blocked.
func (backend *subscriptionCancellationBackend) Exchange(
	ctx context.Context,
	command owonprotocol.Command,
) ([]byte, error) {
	switch command.Text {
	case "*IDN?":
		return []byte("OWON,HDS2202S,25061855,V2.6.0"), nil
	case ":DATA:WAVE:SCREEN:HEAD?":
		backend.headerOnce.Do(
			// signalHeaderEntered publishes the exact blocking backend boundary.
			//
			// Example: the send-failure fixture waits until a waveform read is active.
			func() {
				close(backend.headerEntered)
			})
		<-ctx.Done()
		backend.cancelOnce.Do(
			// signalCancellation publishes that the producer saw its child context.
			//
			// Example: the test releases cleanup only after cancellation reaches the backend.
			func() {
				close(backend.cancelObserved)
			})
		<-backend.releaseAfterCancel
		return nil, ctx.Err()
	default:
		return []byte(`{"CHANNEL":[]}`), nil
	}
}

// ReopenAndValidate satisfies Backend without reopening a staged subscription session.
//
// Example: no transport recovery is needed before the blocked header query.
func (backend *subscriptionCancellationBackend) ReopenAndValidate(
	context.Context,
	owonmodel.SerialNumber,
) error {
	return nil
}

// Close satisfies Backend without owning external resources.
//
// Example: channel cleanup is owned by the test and not by transport shutdown.
func (backend *subscriptionCancellationBackend) Close(context.Context) error {
	return nil
}

// subscriptionSendFailure injects one send error while retaining real gRPC stream ownership.
//
// Example: the interceptor reports when Subscribe has finished joining its canceled producer.
type subscriptionSendFailure struct {
	WaitForBackend <-chan struct{}
	Cause          error
	Result         chan<- error
}

// intercept delegates to the generated handler with a stream that fails at the staged backend boundary.
//
// Example: the real stream supplies cancellation without storing a context in test fixtures.
func (failure subscriptionSendFailure) intercept(
	service any,
	stream grpc.ServerStream,
	_ *grpc.StreamServerInfo,
	handler grpc.StreamHandler,
) error {
	err := handler(service, &subscriptionFailingSend{ServerStream: stream, Failure: failure})
	failure.Result <- err
	return err
}

// subscriptionFailingSend replaces only outbound messages on a real server stream.
//
// Example: receiving the request and exposing its context still use the native gRPC stream.
type subscriptionFailingSend struct {
	grpc.ServerStream
	Failure subscriptionSendFailure
}

// SendMsg waits for the blocked backend query before returning the selected error.
//
// Example: the failure must cancel and join that query before the handler returns.
func (stream *subscriptionFailingSend) SendMsg(any) error {
	<-stream.Failure.WaitForBackend
	return stream.Failure.Cause
}

// scriptedBackend records transport activity and returns deterministic results.
//
// Example: tests configure one timeout followed by one successful exchange.
type scriptedBackend struct {
	Commands       []string
	ExchangeErrors []error
	ReopenCalls    int
	ReopenedSerial owonmodel.SerialNumber
	ReopenError    error
	Responses      map[string][]byte
	CloseErrors    []error
	CloseCalls     int
}

// Exchange records one command and returns its scripted response.
//
// Example: a configured first error models an ambiguous USB transfer.
func (backend *scriptedBackend) Exchange(
	_ context.Context,
	command owonprotocol.Command,
) ([]byte, error) {
	backend.Commands = append(backend.Commands, command.Text)
	if len(backend.ExchangeErrors) > 0 {
		err := backend.ExchangeErrors[0]
		backend.ExchangeErrors = backend.ExchangeErrors[1:]
		if err != nil {
			return nil, err
		}
	}
	return append([]byte(nil), backend.Responses[command.Text]...), nil
}

// ReopenAndValidate records the expected serial and returns its scripted error.
//
// Example: recovery tests assert that serial validation precedes a new write.
func (backend *scriptedBackend) ReopenAndValidate(
	_ context.Context,
	serial owonmodel.SerialNumber,
) error {
	backend.ReopenCalls++
	backend.ReopenedSerial = serial
	return backend.ReopenError
}

// Close satisfies Backend for deterministic tests.
//
// Example: no resources are owned by this in-memory backend.
func (backend *scriptedBackend) Close(_ context.Context) error {
	backend.CloseCalls++
	if len(backend.CloseErrors) == 0 {
		return nil
	}
	err := backend.CloseErrors[0]
	backend.CloseErrors = backend.CloseErrors[1:]

	return err
}
