package owonserver

import (
	"context"
	"fmt"
	"sync"
	"testing"
	"testing/synctest"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owoncontrol"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonsession"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/durationpb"
)

// saturatedStreamBackend stages actual producer captures behind an observable first-send barrier.
//
// Example: capture 1025 makes a pending gap contend with the full hard-cap FIFO.
type saturatedStreamBackend struct {
	SendEntered <-chan struct{}
	Captured    chan<- struct{}
	captures    int
}

// Exchange supplies identity and screen waveforms while signaling the final capture boundary.
//
// Example: the first header cannot run ahead of the consumer's blocked first Send.
func (backend *saturatedStreamBackend) Exchange(
	ctx context.Context,
	command owonprotocol.Command,
) ([]byte, error) {
	switch command.Text {
	case "*IDN?":
		return []byte("OWON,HDS2202S,25061855,V2.6.0"), nil
	case ":DATA:WAVE:SCREEN:HEAD?":
		select {
		case <-backend.SendEntered:
			return []byte(`{"SAMPLE":{"DATALEN":1}}`), nil
		case <-ctx.Done():
			return nil, ctx.Err()
		}
	case ":DATA:WAVE:SCREEN:CH1?":
		backend.captures++
		if backend.captures == owonrpc.MaximumSubscriptionCapacity+1 {
			close(backend.Captured)
		}
		return []byte{1}, nil
	default:
		return nil, fmt.Errorf("unexpected stream command %q", command.Text)
	}
}

// ReopenAndValidate rejects an unexpected recovery in the queue-only failure scenario.
//
// Example: backpressure never poisons an otherwise successful backend exchange.
func (*saturatedStreamBackend) ReopenAndValidate(
	context.Context,
	owonmodel.SerialNumber,
) error {
	return fmt.Errorf("unexpected stream recovery")
}

// Close releases the resource-free controlled backend.
//
// Example: all fixture synchronization is owned by the test's bubble.
func (*saturatedStreamBackend) Close(context.Context) error { return nil }

// heldFirstSend preserves the real gRPC stream while blocking its first publication.
//
// Example: production polling can fill its queue independently of a slow client send.
type heldFirstSend struct {
	grpc.ServerStream
	Entered chan<- struct{}
	Release <-chan struct{}
	once    sync.Once
}

// SendMsg holds the first send and forwards every message through the real transport.
//
// Example: releasing the barrier publishes the original state before queued captures.
func (stream *heldFirstSend) SendMsg(message any) error {
	stream.once.Do(
		// holdPublication exposes the slow consumer independently of producer timing.
		//
		// Example: the test releases only after the producer is durably stopped.
		func() { close(stream.Entered); <-stream.Release })
	return stream.ServerStream.SendMsg(message)
}

// TestSubscribeDrainsSaturatedFIFO exercises production Subscribe and the public client with explicit barriers.
//
// Example: a 1024-entry FIFO publishes all captures, exact loss metadata and a terminal status in order.
func TestSubscribeDrainsSaturatedFIFO(t *testing.T) {
	synctest.Test(t,
		// exerciseSlowConsumer advances only virtual polling time while the first native stream send is held.
		//
		// Example: synchronization channels, not scheduler sleeps, establish saturation before release.
		func(t *testing.T) {
			entered, release, captured := make(chan struct{}), make(chan struct{}), make(chan struct{})
			backend := &saturatedStreamBackend{SendEntered: entered, Captured: captured}
			server, err := NewServerWithConfig(newTestInstrument(t, backend), ServerConfig{MaxSubscriptionPollWork: 4096})
			require.NoError(t, err)
			client := newControlClientForServer(t, server, grpc.StreamInterceptor(
				// holdFirstStreamSend wraps only outbound publication; generated request handling is unchanged.
				//
				// Example: production Subscribe remains the handler under test.
				func(
					service any,
					stream grpc.ServerStream,
					_ *grpc.StreamServerInfo,
					handler grpc.StreamHandler,
				) error {
					return handler(service, &heldFirstSend{ServerStream: stream, Entered: entered, Release: release})
				}))
			stream, err := client.Subscribe(t.Context(), &pb.SubscribeRequest{Interval: durationpb.New(owonrpc.MinimumSubscriptionInterval), QueueCapacity: owonrpc.MaximumSubscriptionCapacity, WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1}})
			require.NoError(t, err)
			<-captured
			synctest.Wait()
			close(release)
			for sequence := uint64(1); sequence <= owonrpc.MaximumSubscriptionCapacity+3; sequence++ {
				event, err := stream.Recv()
				require.NoError(t, err)
				require.Equal(t, sequence, event.Sequence)
				switch sequence {
				case 1, owonrpc.MaximumSubscriptionCapacity + 1:
					require.NotNil(t, event.GetState())
				case owonrpc.MaximumSubscriptionCapacity + 2:
					gap := event.GetWaveformGap()
					require.NotNil(t, gap)
					require.Equal(t, uint64(1024), gap.FirstMissingSequence)
					require.Equal(t, uint64(1025), gap.LastMissingSequence)
					require.Equal(t, uint64(2), gap.MissingCount)
				case owonrpc.MaximumSubscriptionCapacity + 3:
					require.Equal(t, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_BACKPRESSURE, event.GetError().Category)
				default:
					require.Equal(t, sequence-1, event.GetWaveform().Sequence)
				}
			}
			_, err = stream.Recv()
			require.Equal(t, codes.ResourceExhausted, status.Code(err))
			require.Zero(t, server.subscriptionBudget.used.Load())
		})
}

// newTestInstrument constructs an instrument backed by one deterministic recorder.
//
// Example: control tests use it to assert the exact SCPI command sequence.
func newTestInstrument(
	t *testing.T,
	backend owonsession.Backend,
) *owoncontrol.Controller {
	t.Helper()
	transport, err := owonsession.New(backend, owonsession.Config{ExpectedSerial: "25061855"})
	require.NoError(t, err)
	instrument, err := owoncontrol.New(transport, owonmodel.DeviceIdentity{})
	require.NoError(t, err)

	return instrument
}
