package owonserver

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/xaionaro-go/observability"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"github.com/xaionaro-go/owon/pkg/owonscpi"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// subscriptionProducer polls one instrument and fills one ordered bounded queue.
//
// Example: observability.Go runs Run while the RPC handler sends FIFO events.
type subscriptionProducer struct {
	instrument      Instrument
	request         *pb.SubscribeRequest
	queue           *subscriptionQueue
	pollScheduler   *subscriptionPollScheduler
	pollWeight      int
	interval        time.Duration
	waveformCapture map[pb.Channel]uint64
}

// subscriptionProducerRunner owns the completion signal for one producer goroutine.
//
// Example: Run closes done after production ends and stages its terminal outcome, not after publication.
type subscriptionProducerRunner struct {
	Producer *subscriptionProducer
	Done     chan<- struct{}
}

// waitSubscriptionProducer cancels a producer and waits for it to stop and stage its terminal outcome.
//
// Example: Subscribe uses it during deferred stream cleanup before releasing queue state.
func waitSubscriptionProducer(
	cancel context.CancelFunc,
	done <-chan struct{},
) {
	cancel()
	<-done
}

// Run polls immediately and at each interval until cancellation or failure.
//
// Example: queue dequeue assigns publication sequence while capture counters remain per channel.
func (producer *subscriptionProducer) Run(ctx context.Context) {
	if err := producer.poll(ctx); err != nil {
		producer.finishWithError(err)
		return
	}
	ticker := time.NewTicker(producer.interval)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			producer.queue.finish(nil, ctx.Err())
			return
		case <-ticker.C:
		}
		if err := producer.poll(ctx); err != nil {
			producer.finishWithError(err)
			return
		}
	}
}

// poll captures state and requested waveforms without holding USB during network sends.
//
// Example: each channel advances its capture sequence before queue admission.
func (producer *subscriptionProducer) poll(ctx context.Context) error {
	if err := producer.pollScheduler.acquire(ctx, producer.pollWeight); err != nil {
		return fmt.Errorf("admit subscription poll work: %w", err)
	}
	state, err := producer.instrument.State(ctx, owonrpc.StateRequestFromProto(&pb.GetStateRequest{
		Measurements: producer.request.Measurements, IncludeScreenHeader: producer.request.IncludeScreenHeader, IncludeControls: producer.request.IncludeControls,
	}))
	if err != nil {
		return fmt.Errorf("poll subscription state: %w", err)
	}
	if err := producer.queue.enqueueState(&pb.Event{Timestamp: timestamppb.Now(), Payload: &pb.Event_State{State: owonrpc.StateSnapshotToProto(state)}}); err != nil {
		return err
	}
	for _, channel := range producer.request.WaveformChannels {
		capture, waveformErr := producer.instrument.Waveform(ctx, &owonmodel.WaveformRequest{Channel: owonmodel.Channel(channel), Screen: true})
		if waveformErr != nil {
			return fmt.Errorf("poll subscription waveform %s: %w", channel, waveformErr)
		}
		waveform := owonrpc.WaveformToProto(capture)
		if err := producer.enqueueWaveform(&pb.Event{Timestamp: timestamppb.Now(), Payload: &pb.Event_Waveform{Waveform: waveform}}); err != nil {
			return err
		}
	}

	return nil
}

// enqueueWaveform assigns the capture counter before validating and admitting its wire representation.
//
// Example: capture sequence bytes count toward the frame limit before the queue separately charges publication bytes.
func (producer *subscriptionProducer) enqueueWaveform(event *pb.Event) error {
	waveform := event.GetWaveform()
	producer.waveformCapture[waveform.Channel]++
	waveform.Sequence = producer.waveformCapture[waveform.Channel]
	if err := validateWaveformWireSize(event); err != nil {
		return err
	}
	return producer.queue.enqueueWaveform(event)
}

// subscriptionPollWeight estimates one poll's transport command count.
//
// Example: identity plus one measurement and one waveform costs four command units.
func subscriptionPollWeight(request *pb.SubscribeRequest) int {
	if request == nil {
		return 0
	}
	weight := 1 + len(request.Measurements)
	if request.IncludeScreenHeader || request.IncludeControls {
		weight++
	}
	weight += 2 * len(request.WaveformChannels)

	return weight
}

// finishWithError stages one classified terminal ServiceError for conditional queue admission.
//
// Example: if metadata admission succeeds, a disconnect follows older FIFO events and loss metadata.
func (producer *subscriptionProducer) finishWithError(err error) {
	producer.queue.finish(&pb.Event{Timestamp: timestamppb.Now(), Payload: &pb.Event_Error{Error: subscriptionServiceError(err)}}, err)
}

// subscriptionServiceError classifies a terminal producer error for stream consumers.
//
// Example: unsupported controls are non-retryable while device failures may recover.
func subscriptionServiceError(err error) *pb.ServiceError {
	if err == nil {
		return &pb.ServiceError{
			Operation: "subscription poll",
			Message:   "subscription ended without an error",
		}
	}
	result := &pb.ServiceError{Operation: "subscription poll", Message: err.Error(), Retryable: true, Category: pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_DEVICE_UNAVAILABLE}
	var invalidRequest *owonmodel.ErrInvalidRequest
	var invalidSetting *owonscpi.ErrInvalidSetting
	var dialectMalformed *owonscpi.ErrMalformedResponse
	var waveformTooLarge *ErrWaveformTooLarge
	var invalidInput *ErrInvalidInput
	var rpcInvalidInput *owonrpc.ErrInvalidInput
	var invalidConfig *ErrInvalidConfig
	var invalidCommand *owonprotocol.ErrInvalidCommand
	var unsupportedControl *owonscpi.ErrUnsupportedControl
	var criticalBackpressure *ErrCriticalBackpressure
	var subscriptionResourceExhausted *ErrSubscriptionResourceExhausted
	var malformedResponse *owonprotocol.ErrMalformedResponse
	var responseTooLarge *owonprotocol.ErrResponseTooLarge
	var surplusResponse *owonprotocol.ErrSurplusResponse
	// A malformed reply may wrap a request validator; its device origin determines retryability.
	switch {
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		// A framing read can wrap device silence; its deadline is not evidence of malformed bytes.
	case errors.As(err, &malformedResponse), errors.As(err, &responseTooLarge), errors.As(err, &surplusResponse), errors.As(err, &dialectMalformed), errors.As(err, &waveformTooLarge):
		result.Category = pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL
	case errors.As(err, &invalidRequest), errors.As(err, &invalidCommand), errors.As(err, &invalidSetting), errors.As(err, &invalidInput), errors.As(err, &rpcInvalidInput), errors.As(err, &invalidConfig):
		result.Retryable = false
		result.Category = pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_INVALID_REQUEST
	case errors.As(err, &unsupportedControl):
		result.Retryable = false
		result.Category = pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_UNSUPPORTED
	case errors.As(err, &criticalBackpressure), errors.As(err, &subscriptionResourceExhausted):
		result.Retryable = false
		result.Category = pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_BACKPRESSURE
	}

	return result
}

// Subscribe streams bounded FIFO events until cancellation or producer failure.
//
// Subscribe consumes its stream slot, shared queue budget, and weighted poll-work
// scheduler; it does not hold a unary RPC admission token for the stream lifetime.
//
// Example: state coalescing never allows a newer state to overtake older waveforms.
func (server *Server) Subscribe(
	request *pb.SubscribeRequest,
	stream pb.OwonService_SubscribeServer,
) error {
	if stream == nil {
		return status.Error(codes.InvalidArgument, "stream is required")
	}
	if err := owonrpc.ValidateSubscribeRequest(request); err != nil {
		return rpcError("validate subscription", err)
	}
	instrument, instrumentErr := server.serviceInstrument()
	if instrumentErr != nil {
		return instrumentErr
	}
	if err := server.acquireSubscription(); err != nil {
		return err
	}
	defer server.releaseSubscription()
	interval := owonrpc.DefaultSubscriptionInterval
	if request.Interval != nil {
		interval = request.Interval.AsDuration()
	}
	queue, err := newSubscriptionQueueWithBudget(request.QueueCapacity, server.subscriptionBudget)
	if err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	defer queue.close()
	producer := &subscriptionProducer{
		instrument:      instrument,
		request:         request,
		queue:           queue,
		pollScheduler:   server.subscriptionPollScheduler,
		pollWeight:      subscriptionPollWeight(request),
		interval:        interval,
		waveformCapture: make(map[pb.Channel]uint64),
	}
	producerCtx, cancel := context.WithCancel(stream.Context())
	done := make(chan struct{})
	defer waitSubscriptionProducer(cancel, done)
	observability.Go(producerCtx, subscriptionProducerRunner{Producer: producer, Done: done}.Run)
	for {
		event, nextErr := queue.next(producerCtx)
		if nextErr != nil {
			return rpcError("subscription ended", nextErr)
		}
		if err := stream.Send(event); err != nil {
			return rpcError("send subscription event", err)
		}
	}
}

// Run executes one producer and closes its completion signal after terminal staging.
//
// Example: Subscribe waits on done before releasing the queue budget.
func (runner subscriptionProducerRunner) Run(ctx context.Context) {
	defer close(runner.Done)
	runner.Producer.Run(ctx)
}
