package owonserver

import (
	"context"
	"errors"
	"fmt"
	"io"
	"sync"
	"sync/atomic"

	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// defaultSubscriptionCapacity bounds ordinary queued events when capacity is omitted.
	//
	// Example: a default queue admits at most eight ordinary events at once.
	defaultSubscriptionCapacity = 8
	// maximumSubscriptionBytes bounds queued serialized-event charges per subscriber.
	//
	// Example: queued waveform payloads together cannot exceed 64 MiB.
	maximumSubscriptionBytes = 64 << 20
	// maximumServerSubscriptionBytes bounds queued serialized-event charges across streams.
	//
	// Example: all queues together can reserve at most 256 MiB of serialized-event charges.
	maximumServerSubscriptionBytes = 256 << 20
	// maximumSubscriptionEventBytes matches the gRPC serialized message ceiling.
	//
	// Example: a serialized event larger than 32 MiB terminates its subscription.
	maximumSubscriptionEventBytes = owonrpc.MaximumGRPCMessageBytes
	// maximumSequenceCharge reserves the protobuf tag and largest uint64 encoding.
	//
	// Example: queue accounting remains conservative before publication assigns sequence.
	maximumSequenceCharge = 11
)

// waveformDrop records bounded per-channel capture-sequence loss metadata.
//
// Example: interleaved channel drops retain first, last, and count without a sequence slice.
type waveformDrop struct {
	first uint64
	last  uint64
	count uint64
}

// queuedSubscriptionEvent stores one event and its serialized budget charge.
//
// Example: dequeue subtracts size from the subscriber's 64 MiB budget.
type queuedSubscriptionEvent struct {
	event    *pb.Event
	size     int
	critical bool
}

// subscriptionQueue is one ordered FIFO with state coalescing and deferred waveform gaps.
//
// Example: replacing a pending state appends the latest state after all older events.
type subscriptionQueue struct {
	mu sync.Mutex

	capacity        int
	budget          *subscriptionBudget
	events          []queuedSubscriptionEvent
	bytes           int
	nextPublication uint64
	drops           map[pb.Channel]waveformDrop
	finished        bool
	terminal        error
	terminalEvent   *pb.Event
	terminalReady   bool
	notify          chan struct{}
}

// queueNextResult contains one immediately available queue result.
//
// Example: a zero result tells next to wait on the notification channel.
type queueNextResult struct {
	Event *pb.Event
	Err   error
}

// subscriptionBudget accounts queued serialized-event charges shared by one server.
// Charges are released at dequeue, before Send. They exclude in-flight sends, producer
// payloads, terminal staging, serialization allocations, and Go object overhead.
//
// Example: one slow subscriber cannot multiply the per-queue limit without consuming the global budget.
type subscriptionBudget struct {
	limit int
	used  atomic.Int64
}

// newSubscriptionBudget constructs one server-wide queued serialized-charge allowance.
//
// Example: a daemon starts with a 256 MiB aggregate queue allowance.
func newSubscriptionBudget(limit int) *subscriptionBudget {
	return &subscriptionBudget{limit: limit}
}

// reserve charges one serialized event to the shared budget.
//
// Example: a charge over the remaining allowance fails before retaining the event.
func (budget *subscriptionBudget) reserve(size int) bool {
	if budget == nil {
		return true
	}
	if size < 0 {
		return false
	}
	charge := int64(size)
	for {
		used := budget.used.Load()
		if charge > int64(budget.limit)-used {
			return false
		}
		if budget.used.CompareAndSwap(used, used+charge) {
			return true
		}
	}
}

// release returns one serialized event charge to the shared budget.
//
// Example: dequeueing a waveform makes room for another stream's event.
func (budget *subscriptionBudget) release(size int) {
	if budget == nil || size == 0 {
		return
	}
	charge := int64(size)
	for {
		used := budget.used.Load()
		// An owned charge cannot underflow; clamping would hide a duplicate release and admit unbudgeted data.
		if charge < 0 || charge > used {
			panic(&ErrUnavailable{Operation: "release subscription budget", Resource: "charge", Reason: fmt.Sprintf("%d is outside outstanding balance %d", size, used)})
		}
		if budget.used.CompareAndSwap(used, used-charge) {
			return
		}
	}
}

// newSubscriptionQueue constructs an ordered queue with bounded event counts and serialized charges.
//
// Example: zero capacity selects eight while values above 1024 fail.
func newSubscriptionQueue(capacity uint32) (*subscriptionQueue, error) {
	return newSubscriptionQueueWithBudget(capacity, nil)
}

// newSubscriptionQueueWithBudget links one queue to server-wide serialized-event accounting.
//
// Example: Subscribe passes its shared budget while unit tests can retain an isolated queue.
func newSubscriptionQueueWithBudget(
	capacity uint32,
	budget *subscriptionBudget,
) (*subscriptionQueue, error) {
	if err := owonrpc.ValidateSubscriptionCapacity(capacity); err != nil {
		return nil, err
	}
	if capacity == 0 {
		capacity = defaultSubscriptionCapacity
	}

	return &subscriptionQueue{
		capacity: int(capacity), budget: budget, drops: make(map[pb.Channel]waveformDrop), notify: make(chan struct{}, 1),
	}, nil
}

// enqueueState coalesces an older pending state and appends the latest state in FIFO order.
//
// Example: an older waveform remains before a replacement state.
func (queue *subscriptionQueue) enqueueState(event *pb.Event) error {
	if queue == nil {
		return &ErrUnavailable{Operation: "enqueue subscription state", Resource: "queue", Reason: "is unavailable"}
	}
	if event == nil {
		return fmt.Errorf("enqueue state without payload: %w", &ErrInvalidInput{Reason: "event is nil"})
	}
	if event.GetState() == nil {
		return fmt.Errorf("enqueue state without payload: %w", &ErrInvalidInput{Reason: "state payload is nil"})
	}
	queue.mu.Lock()
	defer queue.mu.Unlock()
	if queue.finished {
		return io.ErrClosedPipe
	}
	for index := 0; index < len(queue.events); index++ {
		if queue.events[index].event.GetState() == nil {
			continue
		}
		queue.bytes -= queue.events[index].size
		queue.budget.release(queue.events[index].size)
		copy(queue.events[index:], queue.events[index+1:])
		queue.events[len(queue.events)-1] = queuedSubscriptionEvent{}
		queue.events = queue.events[:len(queue.events)-1]
		break
	}
	if err := queue.appendLocked(event, false); err != nil {
		return err
	}
	queue.signalLocked()

	return nil
}

// enqueueWaveform appends a waveform after its pending per-channel gap or records a drop.
//
// Example: capture sequence three follows a gap describing dropped capture sequence two.
func (queue *subscriptionQueue) enqueueWaveform(event *pb.Event) error {
	if queue == nil {
		return &ErrUnavailable{Operation: "enqueue subscription waveform", Resource: "queue", Reason: "is unavailable"}
	}
	if event == nil {
		return fmt.Errorf("enqueue waveform without payload: %w", &ErrInvalidInput{Reason: "event is nil"})
	}
	waveform := event.GetWaveform()
	if waveform == nil {
		return fmt.Errorf("enqueue waveform without payload: %w", &ErrInvalidInput{Reason: "waveform payload is nil"})
	}
	queue.mu.Lock()
	defer queue.mu.Unlock()
	if queue.finished {
		return io.ErrClosedPipe
	}
	if drop, found := queue.drops[waveform.Channel]; found {
		if err := queue.appendLocked(gapEvent(waveform.Channel, drop), true); err != nil {
			queue.recordDropLocked(waveform.Channel, waveform.Sequence)
			return err
		}
		delete(queue.drops, waveform.Channel)
	}
	if err := queue.appendLocked(event, false); err != nil {
		var criticalBackpressure *ErrCriticalBackpressure
		if errors.As(err, &criticalBackpressure) {
			queue.recordDropLocked(waveform.Channel, waveform.Sequence)
			return nil
		}
		return err
	}
	queue.signalLocked()

	return nil
}

// finish stages one terminal event and error for admission after the ordinary FIFO drains.
// Pending gaps precede the terminal event only if each can be admitted. Admission failure
// ends the stream with the original and resource errors; close releases unpublished staging.
//
// Example: with sufficient allowance, a device failure publishes loss before its ServiceError.
func (queue *subscriptionQueue) finish(
	event *pb.Event,
	err error,
) {
	if queue == nil {
		return
	}
	queue.mu.Lock()
	defer queue.mu.Unlock()
	if queue.finished {
		return
	}
	queue.finished = true
	queue.terminal = err
	queue.terminalEvent = event
	queue.signalLocked()
}

// close releases queued event charges when a stream stops before draining its FIFO.
//
// Example: a canceled client cannot strand its reserved share of the server budget.
func (queue *subscriptionQueue) close() {
	if queue == nil {
		return
	}
	queue.mu.Lock()
	defer queue.mu.Unlock()
	queue.budget.release(queue.bytes)
	queue.bytes = 0
	queue.events = nil
	queue.drops = make(map[pb.Channel]waveformDrop)
	queue.finished = true
	queue.terminalReady = true
	queue.terminal = nil
	queue.terminalEvent = nil
}

// next returns events strictly in FIFO publication order, then the terminal error.
//
// Example: a terminal ServiceError cannot overtake an already queued waveform.
func (queue *subscriptionQueue) next(ctx context.Context) (*pb.Event, error) {
	if queue == nil {
		return nil, &ErrUnavailable{Operation: "read subscription queue", Resource: "queue", Reason: "is unavailable"}
	}
	if ctx == nil {
		return nil, &ErrUnavailable{Operation: "read subscription queue", Resource: "context", Reason: "is nil"}
	}
	if queue.notify == nil {
		return nil, &ErrUnavailable{Operation: "read subscription queue", Resource: "queue", Reason: "is not initialized"}
	}
	for {
		result := queue.nextReady()
		if result.Event != nil || result.Err != nil {
			return result.Event, result.Err
		}
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-queue.notify:
		}
	}
}

// nextReady removes one ready item while holding queue.mu for one invariant.
//
// Example: the caller can wait without retaining the mutex across a channel receive.
func (queue *subscriptionQueue) nextReady() queueNextResult {
	if queue == nil {
		return queueNextResult{Err: &ErrUnavailable{Operation: "read subscription queue", Resource: "queue", Reason: "is unavailable"}}
	}
	queue.mu.Lock()
	defer queue.mu.Unlock()
	if len(queue.events) == 0 && queue.finished && !queue.terminalReady {
		queue.prepareTerminalLocked()
	}
	if len(queue.events) != 0 {
		queued := queue.events[0]
		// Clear the slot before releasing its charge so the backing array cannot retain unbudgeted payloads.
		queue.events[0] = queuedSubscriptionEvent{}
		queue.events = queue.events[1:]
		if len(queue.events) == 0 {
			queue.events = nil
		}
		queue.bytes -= queued.size
		queue.budget.release(queued.size)
		queue.nextPublication++
		queued.event.Sequence = queue.nextPublication

		return queueNextResult{Event: queued.event}
	}
	if queue.finished && queue.terminalReady {
		if queue.terminal == nil {
			return queueNextResult{Err: io.EOF}
		}

		return queueNextResult{Err: queue.terminal}
	}

	return queueNextResult{}
}

// appendLocked validates and appends one event while queue.mu is held.
//
// Example: ordinary waveform overflow is converted by its caller into a capture gap.
func (queue *subscriptionQueue) appendLocked(
	event *pb.Event,
	critical bool,
) error {
	if event == nil {
		return fmt.Errorf("enqueue nil event: %w", &ErrInvalidInput{Reason: "event is nil"})
	}
	event.Sequence = 0
	size := proto.Size(event) + maximumSequenceCharge
	if size > maximumSubscriptionEventBytes {
		return fmt.Errorf("subscription event is %d bytes, maximum is %d: %w", size, maximumSubscriptionEventBytes, new(ErrSubscriptionResourceExhausted))
	}
	ordinary := 0
	for _, queued := range queue.events {
		if !queued.critical {
			ordinary++
		}
	}
	if queue.bytes+size > maximumSubscriptionBytes {
		return new(ErrSubscriptionResourceExhausted)
	}
	if len(queue.events) >= owonrpc.MaximumSubscriptionCapacity || (!critical && ordinary >= queue.capacity) {
		return new(ErrCriticalBackpressure)
	}
	if !queue.budget.reserve(size) {
		return new(ErrSubscriptionResourceExhausted)
	}
	queue.events = append(queue.events, queuedSubscriptionEvent{event: event, size: size, critical: critical})
	queue.bytes += size

	return nil
}

// prepareTerminalLocked admits one pending gap or terminal event after the preceding FIFO drains.
//
// Example: each of two channel gaps releases its charge before the final ServiceError is admitted.
func (queue *subscriptionQueue) prepareTerminalLocked() {
	// Admit incrementally so metadata can reuse released capacity instead of competing for it.
	var firstChannel pb.Channel
	var hasDrop bool
	for channel := range queue.drops {
		if !hasDrop || channel < firstChannel {
			firstChannel, hasDrop = channel, true
		}
	}
	if hasDrop {
		if err := queue.appendLocked(gapEvent(firstChannel, queue.drops[firstChannel]), true); err != nil {
			queue.terminal = errors.Join(queue.terminal, err)
			queue.terminalReady = true
			return
		}
		delete(queue.drops, firstChannel)
		return
	}
	if queue.terminalEvent != nil {
		if err := queue.appendLocked(queue.terminalEvent, true); err != nil {
			// External budget exhaustion fails fast; close still owns the unpublished staging reference.
			queue.terminal = errors.Join(queue.terminal, err)
			queue.terminalReady = true
			return
		}
		queue.terminalEvent = nil
	}
	queue.terminalReady = true
}

// recordDropLocked accumulates one missing per-channel waveform capture sequence.
//
// Example: capture sequences two and four produce first=2, last=4, count=2.
func (queue *subscriptionQueue) recordDropLocked(
	channel pb.Channel,
	sequence uint64,
) {
	drop, found := queue.drops[channel]
	if !found {
		drop.first = sequence
	}
	drop.last = sequence
	drop.count++
	queue.drops[channel] = drop
}

// signalLocked wakes the consumer without accumulating redundant notifications.
//
// Example: several producer updates require at most one buffered wake-up.
func (queue *subscriptionQueue) signalLocked() {
	select {
	case queue.notify <- struct{}{}:
	default:
	}
}

// gapEvent constructs capture-loss metadata without assigning publication sequence.
//
// Example: dequeue later assigns the event-wide FIFO publication sequence.
func gapEvent(
	channel pb.Channel,
	drop waveformDrop,
) *pb.Event {
	return &pb.Event{Timestamp: timestamppb.Now(), Payload: &pb.Event_WaveformGap{WaveformGap: &pb.WaveformGap{
		Channel: channel, FirstMissingSequence: drop.first, MissingCount: drop.count, LastMissingSequence: drop.last,
	}}}
}

// ErrCriticalBackpressure identifies exhaustion of non-droppable subscription capacity.
//
// Example: a state event that cannot fit terminates the stream visibly.
type ErrCriticalBackpressure struct{}

// Error returns the critical-backpressure classification.
//
// Example: gRPC maps this error to ResourceExhausted.
func (*ErrCriticalBackpressure) Error() string {
	return "critical subscription capacity exhausted"
}

// Unwrap returns no lower-level cause because this error is a leaf classification.
//
// Example: errors.As matches ErrCriticalBackpressure through queue insertion context.
func (*ErrCriticalBackpressure) Unwrap() error {
	return nil
}

// ErrSubscriptionResourceExhausted identifies exhausted serialized-event charges or poll-work allowance.
//
// Example: one serialized event larger than the queue budget returns this error.
type ErrSubscriptionResourceExhausted struct{}

// Error returns the subscription resource classification.
//
// Example: gRPC maps this error to ResourceExhausted.
func (*ErrSubscriptionResourceExhausted) Error() string {
	return "subscription resource limit exhausted"
}

// Unwrap returns no lower-level cause because this error is a leaf classification.
//
// Example: errors.As matches ErrSubscriptionResourceExhausted through a stream error.
func (*ErrSubscriptionResourceExhausted) Unwrap() error {
	return nil
}
