package owonserver

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

const (
	// weightedStressCapacity bounds the mixed-weight scheduler test allowance.
	//
	// Example: weight four and weight three consume one complete allowance.
	weightedStressCapacity = 7
)

// TestSubscriptionSchedulerRejectsInvalidBudgets verifies invalid work cannot enter the scheduling FIFO.
//
// Example: a poll larger than the configured allowance fails without delaying the next valid poll.
func TestSubscriptionSchedulerRejectsInvalidBudgets(t *testing.T) {
	t.Parallel()
	for _, config := range []struct {
		Capacity int
		Window   time.Duration
	}{{0, time.Second}, {1, 0}, {2, time.Nanosecond}} {
		scheduler, err := newSubscriptionPollScheduler(config.Capacity, config.Window)
		require.Nil(t, scheduler)
		requireErrorType[*ErrInvalidConfig](t, err)
	}
	scheduler, err := newSubscriptionPollScheduler(1, time.Second)
	require.NoError(t, err)
	requireErrorType[*ErrUnavailable](t, (*subscriptionPollScheduler)(nil).acquire(t.Context(), 1))
	requireErrorType[*ErrUnavailable](t, scheduler.acquire(nil, 1))
	requireErrorType[*ErrInvalidInput](t, scheduler.acquire(t.Context(), 0))
	requireErrorType[*ErrSubscriptionResourceExhausted](t, scheduler.acquire(t.Context(), 2))
	require.Empty(t, scheduler.queue)
	require.NoError(t, scheduler.acquire(t.Context(), 1))
	require.Empty(t, scheduler.queue)
	requireErrorType[*ErrUnavailable](t, (*subscriptionPollScheduler)(nil).wait(t.Context(), nil))
	requireErrorType[*ErrUnavailable](t, scheduler.wait(nil, nil))
	requireErrorType[*ErrInvalidInput](t, scheduler.wait(t.Context(), nil))
}

// TestSubscriptionPollWeightCountsVerifiedCommands verifies every poll charge matches its reads.
//
// Example: identity, two measurements, one state header, and two waveforms cost eight commands.
func TestSubscriptionPollWeightCountsVerifiedCommands(t *testing.T) {
	t.Parallel()

	request := &pb.SubscribeRequest{
		Measurements:        make([]*pb.MeasurementSelector, 2),
		IncludeScreenHeader: true,
		WaveformChannels:    []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2},
	}
	require.Equal(t, 8, subscriptionPollWeight(request))
	require.Equal(t, 1, subscriptionPollWeight(&pb.SubscribeRequest{}))
	require.Equal(t, maximumSubscriptionPollWeight, subscriptionPollWeight(&pb.SubscribeRequest{
		Measurements:        make([]*pb.MeasurementSelector, owonmodel.MaximumMeasurementSelectors),
		IncludeScreenHeader: true,
		IncludeControls:     true,
		WaveformChannels:    []pb.Channel{pb.Channel_CHANNEL_1, pb.Channel_CHANNEL_2},
	}))
}

// TestSubscriptionPollSchedulerPreservesWeightedFIFO verifies a large request cannot be bypassed.
//
// Example: after a two-unit holder leaves one unit, a later one-unit request waits behind two units.
func TestSubscriptionPollSchedulerPreservesWeightedFIFO(t *testing.T) {
	t.Parallel()

	scheduler, err := newSubscriptionPollScheduler(3, time.Hour)
	require.NoError(t, err)
	holder, err := scheduler.enqueue(2)
	require.NoError(t, err)
	requireSubscriptionPollGranted(t, holder)
	heavy, err := scheduler.enqueue(2)
	require.NoError(t, err)
	light, err := scheduler.enqueue(1)
	require.NoError(t, err)
	requireSubscriptionPollNotGranted(t, heavy)
	requireSubscriptionPollNotGranted(t, light)

	scheduler.dispatch(heavy.readyAt)
	requireSubscriptionPollGranted(t, heavy)
	requireSubscriptionPollNotGranted(t, light)
	scheduler.dispatch(light.readyAt)
	requireSubscriptionPollGranted(t, light)
}

// TestSubscriptionPollSchedulerLimitsEachWindow verifies weighted admission is rate bounded.
//
// Example: synthetic rate advancement admits no more than three command units per interval.
func TestSubscriptionPollSchedulerLimitsEachWindow(t *testing.T) {
	t.Parallel()

	scheduler, err := newSubscriptionPollScheduler(3, time.Hour)
	require.NoError(t, err)
	first, err := scheduler.enqueue(2)
	require.NoError(t, err)
	requireSubscriptionPollGranted(t, first)
	second, err := scheduler.enqueue(2)
	require.NoError(t, err)
	requireSubscriptionPollNotGranted(t, second)
	scheduler.dispatch(second.readyAt.Add(-time.Nanosecond))
	requireSubscriptionPollNotGranted(t, second)
	scheduler.dispatch(second.readyAt)
	requireSubscriptionPollGranted(t, second)
}

// TestSubscriptionPollSchedulerCancellationReleasesQueuedWork verifies queued cancellation removes work.
//
// Example: canceling the first queued request lets the next request use its released rate slot.
func TestSubscriptionPollSchedulerCancellationReleasesQueuedWork(t *testing.T) {
	t.Parallel()

	scheduler, err := newSubscriptionPollScheduler(1, time.Hour)
	require.NoError(t, err)
	holder, err := scheduler.enqueue(1)
	require.NoError(t, err)
	requireSubscriptionPollGranted(t, holder)
	canceled, err := scheduler.enqueue(1)
	require.NoError(t, err)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	require.ErrorIs(t, scheduler.wait(ctx, canceled), context.Canceled)
	retained, err := scheduler.enqueue(1)
	require.NoError(t, err)
	requireSubscriptionPollNotGranted(t, canceled)
	scheduler.dispatch(retained.readyAt)
	requireSubscriptionPollGranted(t, retained)
}

// TestSubscriptionPollSchedulerWeightedStress verifies aggregate budget and FIFO progress.
//
// Example: a mixed stream of weighted requests eventually grants every request without a burst.
func TestSubscriptionPollSchedulerWeightedStress(t *testing.T) {
	t.Parallel()

	scheduler, err := newSubscriptionPollScheduler(weightedStressCapacity, time.Hour)
	require.NoError(t, err)
	weights := []int{3, 2, 1, 4, 2, 1, 3, 2, 1, 4, 2}
	requests := make([]*subscriptionPollRequest, 0, len(weights))
	for _, weight := range weights {
		request, enqueueErr := scheduler.enqueue(weight)
		require.NoError(t, enqueueErr)
		requests = append(requests, request)
	}

	for index, request := range requests {
		if index != 0 {
			requireSubscriptionPollNotGranted(t, request)
			scheduler.dispatch(request.readyAt.Add(-time.Nanosecond))
			requireSubscriptionPollNotGranted(t, request)
			require.Equal(t, requests[index-1].endAt, request.readyAt)
		}
		scheduler.dispatch(request.readyAt)
		requireSubscriptionPollGranted(t, request)
		require.Equal(t, time.Duration(weights[index])*(time.Hour/weightedStressCapacity), request.endAt.Sub(request.readyAt))
		for _, later := range requests[index+1:] {
			requireSubscriptionPollNotGranted(t, later)
		}
	}
}

// requireSubscriptionPollGranted asserts one scheduler request was admitted.
//
// Example: unit tests consume a closed grant signal without waiting on wall-clock time.
func requireSubscriptionPollGranted(
	t *testing.T,
	request *subscriptionPollRequest,
) {
	t.Helper()
	select {
	case <-request.granted:
	default:
		require.FailNow(t, "subscription poll request was not granted")
	}
}

// requireSubscriptionPollNotGranted asserts one scheduler request remains queued.
//
// Example: strict FIFO tests prove a light request cannot jump a blocked heavy request.
func requireSubscriptionPollNotGranted(
	t *testing.T,
	request *subscriptionPollRequest,
) {
	t.Helper()
	select {
	case <-request.granted:
		require.FailNow(t, "subscription poll request was granted too early")
	default:
	}
}

// TestSubscriptionPollSchedulerAcquireHonorsCancellation verifies the public wait path rejects canceled work.
//
// Example: a canceled context never admits even a request that would otherwise fit.
func TestSubscriptionPollSchedulerAcquireHonorsCancellation(t *testing.T) {
	t.Parallel()

	scheduler, err := newSubscriptionPollScheduler(1, time.Hour)
	require.NoError(t, err)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	require.ErrorIs(t, scheduler.acquire(ctx, 1), context.Canceled)
}

// requireErrorType verifies that an error chain contains one concrete error type.
//
// Example: requireErrorType[*ErrInvalidRequest](t, err) checks a validation result.
func requireErrorType[T error](
	t *testing.T,
	err error,
) {
	t.Helper()
	var typed T
	require.ErrorAs(t, err, &typed)
}
