package owonserver

import (
	"fmt"

	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/protobuf/proto"
)

// validateWaveformWireSize reserves room for both unary replies and streamed events.
//
// Example: two individually valid sixteen-MiB device frames are rejected before they
// become a thirty-two-MiB-plus protobuf message that gRPC or a subscription cannot send.
func validateWaveformWireSize(event *pb.Event) error {
	if event.GetWaveform() == nil {
		return fmt.Errorf("validate waveform wire size: %w", &ErrInvalidInput{Reason: "waveform is nil"})
	}
	size := proto.Size(event) + maximumSequenceCharge
	if size > owonrpc.MaximumGRPCMessageBytes {
		return &ErrWaveformTooLarge{Size: size, Limit: owonrpc.MaximumGRPCMessageBytes}
	}

	return nil
}

// ErrWaveformTooLarge identifies a protobuf waveform envelope exceeding RPC limits.
//
// Example: individually valid device frames can exceed the aggregate event budget.
type ErrWaveformTooLarge struct {
	Size  int
	Limit int
}

// Error reports the complete envelope charge and configured maximum.
//
// Example: operators can distinguish wire-envelope overflow from device framing.
func (err *ErrWaveformTooLarge) Error() string {
	if err == nil {
		return "waveform event exceeds RPC message limit"
	}
	return fmt.Sprintf("waveform event is %d bytes, maximum is %d", err.Size, err.Limit)
}

// Unwrap returns nil because an envelope budget failure is a leaf classification.
//
// Example: errors.As identifies the RPC budget error without a device-frame cause.
func (*ErrWaveformTooLarge) Unwrap() error { return nil }
