package owonserver

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonmodel"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	"github.com/xaionaro-go/owon/pkg/owonrpc"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// TestWaveformCaptureSequenceIsChargedBeforeAdmission checks the last bytes at the wire ceiling.
//
// Example: an otherwise admissible waveform cannot hide its added capture counter from validation.
func TestWaveformCaptureSequenceIsChargedBeforeAdmission(t *testing.T) {
	waveform := &pb.Waveform{Channel: pb.Channel_CHANNEL_1, Data: make([]byte, owonrpc.MaximumGRPCMessageBytes)}
	event := &pb.Event{Payload: &pb.Event_Waveform{Waveform: waveform}}
	overflow := proto.Size(event) + maximumSequenceCharge - owonrpc.MaximumGRPCMessageBytes
	waveform.Data = waveform.Data[:len(waveform.Data)-overflow]
	require.Equal(t, owonrpc.MaximumGRPCMessageBytes, proto.Size(event)+maximumSequenceCharge)
	require.NoError(t, validateWaveformWireSize(event))
	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	t.Cleanup(queue.close)
	producer := &subscriptionProducer{queue: queue, waveformCapture: map[pb.Channel]uint64{pb.Channel_CHANNEL_1: 1 << 63}}
	err = producer.enqueueWaveform(event)
	requireErrorType[*ErrWaveformTooLarge](t, err)
	require.Equal(t, uint64(1<<63)+1, waveform.Sequence)
	require.Zero(t, queue.bytes)
}

// TestWaveformPublicationTimestampIsCharged checks the actual event rather than a reconstructed envelope.
//
// Example: a longer publication timestamp cannot hide behind the shorter capture timestamp.
func TestWaveformPublicationTimestampIsCharged(t *testing.T) {
	waveform := &pb.Waveform{Channel: pb.Channel_CHANNEL_1, Sequence: 1, CapturedAt: &timestamppb.Timestamp{Seconds: 1}, Data: make([]byte, owonrpc.MaximumGRPCMessageBytes)}
	event := &pb.Event{Timestamp: waveform.CapturedAt, Payload: &pb.Event_Waveform{Waveform: waveform}}
	overflow := proto.Size(event) + maximumSequenceCharge - owonrpc.MaximumGRPCMessageBytes
	waveform.Data = waveform.Data[:len(waveform.Data)-overflow]
	require.Equal(t, owonrpc.MaximumGRPCMessageBytes, proto.Size(event)+maximumSequenceCharge)
	require.NoError(t, validateWaveformWireSize(event))
	event.Timestamp = &timestamppb.Timestamp{Seconds: 253402300799, Nanos: 999999999}
	queue, err := newSubscriptionQueue(1)
	require.NoError(t, err)
	t.Cleanup(queue.close)
	producer := &subscriptionProducer{queue: queue, waveformCapture: make(map[pb.Channel]uint64)}
	requireErrorType[*ErrWaveformTooLarge](t, producer.enqueueWaveform(event))
	require.Zero(t, queue.bytes)
}

// TestWaveformRPCRejectsAggregateOversize verifies wire limits belong to both outbound server paths.
//
// Example: two valid sixteen-MiB frames remain native captures but exceed one RPC envelope.
func TestWaveformRPCRejectsAggregateOversize(t *testing.T) {
	header := append([]byte("{}"), bytes.Repeat([]byte(" "), int(owonprotocol.DefaultMaximumResponseBytes)-2)...)
	backend := &scriptedBackend{Responses: map[string][]byte{
		"*IDN?":                   []byte("OWON,HDS2202S,25061855,V2.6.0"),
		":DATA:WAVE:SCREEN:HEAD?": header,
		":DATA:WAVE:SCREEN:CH1?":  make([]byte, owonprotocol.DefaultMaximumResponseBytes),
	}}
	instrument := newTestInstrument(t, backend)
	capture, err := instrument.Waveform(t.Context(), &owonmodel.WaveformRequest{Channel: owonmodel.Channel1, Screen: true})
	require.NoError(t, err)
	require.Len(t, capture.Data, int(owonprotocol.DefaultMaximumResponseBytes))
	require.Len(t, capture.ScreenHeaderJSON, int(owonprotocol.DefaultMaximumResponseBytes))
	service, err := NewServer(instrument)
	require.NoError(t, err)
	client := newSubscribeTCPClient(t, service)
	waveform, err := client.Waveform(t.Context(), &pb.GetWaveformRequest{Channel: pb.Channel_CHANNEL_1, Screen: true})
	require.Nil(t, waveform)
	require.Equal(t, codes.DataLoss, status.Code(err))
	require.Contains(t, err.Error(), "waveform event")
	stream, err := client.Subscribe(t.Context(), &pb.SubscribeRequest{WaveformChannels: []pb.Channel{pb.Channel_CHANNEL_1}})
	require.NoError(t, err)
	state, err := stream.Recv()
	require.NoError(t, err)
	require.NotNil(t, state.GetState())
	terminal, err := stream.Recv()
	require.NoError(t, err)
	require.Equal(t, pb.ServiceErrorCategory_SERVICE_ERROR_CATEGORY_PROTOCOL, terminal.GetError().GetCategory())
	require.Contains(t, terminal.GetError().GetMessage(), "waveform event")
	require.Nil(t, terminal.GetWaveform())
	_, err = stream.Recv()
	require.Equal(t, codes.DataLoss, status.Code(err))
}

// TestHeaderDecodingBecomesRPCDataLoss preserves protocol origin across native validation and conversion.
//
// Example: malformed screen tokens never become InvalidArgument even when they wrap native validators.
func TestHeaderDecodingBecomesRPCDataLoss(t *testing.T) {
	for _, header := range []string{
		`{"SAMPLE":{"TYPE":"unknown"}}`,
		`{"SAMPLE":{"TYPE":"SAMPle"},"TIMEBASE":{"SCALE":"20us"},"CHANNEL":[{"NAME":"CH1","DISPLAY":"ON","COUPLING":"DC","PROBE":"NaNX"}]}`,
		`{"SAMPLE":{"TYPE":"SAMPle"},"TIMEBASE":{"SCALE":"20us"},"Trig":{"Mode":"unknown"}}`,
	} {
		backend := &scriptedBackend{Responses: map[string][]byte{"*IDN?": []byte("OWON,HDS2202S,25061855,V2.6.0"), ":DATA:WAVE:SCREEN:HEAD?": []byte(header)}}
		state, err := newControlClient(t, backend).State(t.Context(), &pb.GetStateRequest{IncludeControls: true})
		require.Nil(t, state)
		require.Equal(t, codes.DataLoss, status.Code(err), header)
	}
}
