package execute

import (
	"io"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/owon/pkg/owonctl"
	"github.com/xaionaro-go/owon/pkg/owonprotocol"
	pb "github.com/xaionaro-go/owon/pkg/owonrpc/autogenerated"
)

// TestResponseModeMapsExplicitFraming verifies every supported CLI spelling.
//
// Example: both binary spellings select OWON's length-prefixed response mode.
func TestResponseModeMapsExplicitFraming(t *testing.T) {
	tests := []struct {
		Name  string
		Value string
		Want  owonprotocol.ResponseMode
	}{
		{Name: "none", Value: "none", Want: owonprotocol.ResponseModeNone},
		{Name: "ascii", Value: "ascii", Want: owonprotocol.ResponseModeASCII},
		{Name: "binary", Value: "binary", Want: owonprotocol.ResponseModeLengthPrefixed},
		{Name: "length-prefixed", Value: "length-prefixed", Want: owonprotocol.ResponseModeLengthPrefixed},
	}
	for _, test := range tests {
		t.Run(test.Name,
			// verifyResponseModeCase checks one supported spelling and enum result.
			//
			// Example: the binary alias maps to length-prefixed framing.
			func(t *testing.T) {
				mode, err := responseMode(test.Value)
				require.NoError(t, err)
				require.Equal(t, pb.ResponseMode(test.Want), mode)
			})
	}
}

// TestResponseModeRejectsImplicitFraming verifies unsupported mode values fail before RPC use.
//
// Example: automatic framing cannot silently change the device transaction contract.
func TestResponseModeRejectsImplicitFraming(t *testing.T) {
	_, err := responseMode("auto")
	var arguments *owonctl.ErrCommandArguments
	require.ErrorAs(t, err, &arguments)
}

// TestCommandValidatesArgumentsBeforeClientUse verifies local CLI errors do not require a daemon.
//
// Example: Cobra rejects an omitted SCPI operand before client configuration is used.
func TestCommandValidatesArgumentsBeforeClientUse(t *testing.T) {
	command := NewCommand(nil)
	command.SetOut(io.Discard)
	command.SetArgs([]string{"--mode", "ascii"})
	err := command.ExecuteContext(t.Context())
	require.ErrorContains(t, err, "accepts 1 arg(s)")
}
